In [8]:
import os
import pandas as pd
import json
import pandas as pd
import requests
import base64
import numpy as np
import os
import math
from dotenv import load_dotenv
from datetime import timedelta

In [58]:
df_s = pd.read_csv("../test.csv", sep = "|")

/Users/valen/.pyenv/versions/3.8.13/envs/lewagon/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3457: DtypeWarning: Columns (5,25) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [59]:
df_s

,artist_name,album_name,track_name,timestamp,song_key,followers,artist_popularity,genre_1,genre_2,genre_3,...,mode,speechiness,tempo,track_duration,track_popularity,valence,new_artist_yn,new_recurring_artist_yn,new_track_yn,new_recurring_track_yn
0,Passion Pit,Chunk of Change,Sleepyhead,2023-08-31 09:07:00+00:00,Sleepyhead /: Passion Pit,1253329,59.0,indie rock,indietronica,modern rock,...,1,0.11,106.052,175080.0,44,0.764,0,0,0,0
1,The Paper Kites,On the Train Ride Home,Only One,2023-08-31 08:10:00+00:00,Only One /: The Paper Kites,642170,71.0,australian indie folk,indie folk,stomp and holler,...,0,0.0297,96.912,251746.0,36,0.184,0,0,0,0
2,Penguin Cafe Orchestra,Union Cafe,LifeBoat (Lovers Rock),2023-08-31 08:03:00+00:00,LifeBoat (Lovers Rock) /: Penguin Cafe Orchestra,118410,42.0,bow pop,compositional ambient,NaN,...,1,0.0407,178.94,435680.0,37,0.356,0,0,1,0
3,Real Estate,Days,It's Real,2023-08-31 07:55:00+00:00,It's Real /: Real Estate,386691,53.0,chillwave,dreamo,indie pop,...,1,0.0298,152.009,168493.0,50,0.721,0,0,0,0
4,Kurt Vile,Bottle It In,Loading Zones,2023-08-31 07:51:00+00:00,Loading Zones /: Kurt Vile,480872,58.0,indie rock,modern folk rock,neo-psychedelic,...,0,0.0302,112.22,203133.0,52,0.757,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269377,Eminem,Relapse: Refill,Hell Breaks Loose,2013-10-19 14:17:00+00:00,Hell Breaks Loose /: Eminem,67633798,94.0,detroit hip hop,hip hop,rap,...,0,0.188,79.901,244133.0,11,0.922,0,0,1,0
269378,Eminem,Relapse: Refill,Drop The Bomb On 'Em,2013-10-19 14:16:00+00:00,Drop The Bomb On 'Em /: Eminem,67633798,94.0,detroit hip hop,hip hop,rap,...,0,0.215,91.989,287266.0,48,0.357,0,0,1,0
269379,Eminem,Relapse: Refill,Medicine Ball,2013-10-19 14:14:00+00:00,Medicine Ball /: Eminem,67633798,94.0,detroit hip hop,hip hop,rap,...,1,0.257,119.858,237346.0,49,0.695,0,0,1,0
269380,Eminem,Relapse: Refill,We Made You,2013-10-19 14:14:00+00:00,We Made You /: Eminem,67633798,94.0,detroit hip hop,hip hop,rap,...,1,0.0778,114.01,269626.0,20,0.654,0,0,1,0
269381,Eminem,Rap God,Rap God,2013-10-19 14:12:00+00:00,Rap God /: Eminem,67633798,94.0,detroit hip hop,hip hop,rap,...,1,0.327,148.222,363521.0,48,0.615,1,0,1,0

In [55]:
df = pd.read_csv("../files/processed_files/lfm_processed.csv", sep = '|')

/Users/valen/.pyenv/versions/3.8.13/envs/lewagon/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3457: DtypeWarning: Columns (5,25) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [56]:
df

,artist_name,album_name,track_name,timestamp,song_key,followers,artist_popularity,genre_1,genre_2,genre_3,...,tempo,track_duration,track_popularity,valence,new_artist_yn,new_recurring_artist_yn,new_track_yn,new_recurring_track_yn,skip_next_track_,completion_
0,Passion Pit,Chunk of Change,Sleepyhead,2023-08-31 09:07:00+00:00,Sleepyhead /: Passion Pit,1253329,59.0,indie rock,indietronica,modern rock,...,106.052,175080.0,44,0.764,0,0,0,0,0,1.00
1,The Paper Kites,On the Train Ride Home,Only One,2023-08-31 08:10:00+00:00,Only One /: The Paper Kites,642170,71.0,australian indie folk,indie folk,stomp and holler,...,96.912,251746.0,36,0.184,0,0,0,0,4,1.00
2,Penguin Cafe Orchestra,Union Cafe,LifeBoat (Lovers Rock),2023-08-31 08:03:00+00:00,LifeBoat (Lovers Rock) /: Penguin Cafe Orchestra,118410,42.0,bow pop,compositional ambient,NaN,...,178.94,435680.0,37,0.356,0,0,1,0,7,1.00
3,Real Estate,Days,It's Real,2023-08-31 07:55:00+00:00,It's Real /: Real Estate,386691,53.0,chillwave,dreamo,indie pop,...,152.009,168493.0,50,0.721,0,0,0,0,2,1.00
4,Kurt Vile,Bottle It In,Loading Zones,2023-08-31 07:51:00+00:00,Loading Zones /: Kurt Vile,480872,58.0,indie rock,modern folk rock,neo-psychedelic,...,112.22,203133.0,52,0.757,0,0,0,0,3,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269377,Eminem,Relapse: Refill,Hell Breaks Loose,2013-10-19 14:17:00+00:00,Hell Breaks Loose /: Eminem,67633798,94.0,detroit hip hop,hip hop,rap,...,79.901,244133.0,11,0.922,0,0,1,0,4,1.00
269378,Eminem,Relapse: Refill,Drop The Bomb On 'Em,2013-10-19 14:16:00+00:00,Drop The Bomb On 'Em /: Eminem,67633798,94.0,detroit hip hop,hip hop,rap,...,91.989,287266.0,48,0.357,0,0,1,0,1,0.20
269379,Eminem,Relapse: Refill,Medicine Ball,2013-10-19 14:14:00+00:00,Medicine Ball /: Eminem,67633798,94.0,detroit hip hop,hip hop,rap,...,119.858,237346.0,49,0.695,0,0,1,0,2,0.50
269380,Eminem,Relapse: Refill,We Made You,2013-10-19 14:14:00+00:00,We Made You /: Eminem,67633798,94.0,detroit hip hop,hip hop,rap,...,114.01,269626.0,20,0.654,0,0,1,0,0,0.00
269381,Eminem,Rap God,Rap God,2013-10-19 14:12:00+00:00,Rap God /: Eminem,67633798,94.0,detroit hip hop,hip hop,rap,...,148.222,363521.0,48,0.615,1,0,1,0,2,0.33

In [61]:
def compute_completion(df):
    """Adds a column "completion" to the df, to see what percentage of the song was listened t before skipping"""
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    df['skip_next_track_'] = 0
    df['completion_'] = 0
    for i in range(1, len(df)):
        curr_row = df.loc[i]
        prev_row = df.loc[i-1]
        time_diff = prev_row['timestamp'] - curr_row['timestamp']
        minutes_diff = time_diff.total_seconds() / 60
        original_duration = curr_row['track_duration']/1000/60
        if (isinstance(curr_row['track_duration'], (int, float))) & (curr_row['track_duration'] == curr_row['track_duration']):
            duration = math.floor(curr_row['track_duration']/1000/60)
        else:
            duration = 0 
        if time_diff >= timedelta(minutes=duration):
            df.at[i, 'skip_next_track_'] = duration
            df.at[i, 'completion_'] = 100
        elif duration > 0:
            if minutes_diff != minutes_diff:
                continue
            df.at[i, 'skip_next_track_'] = minutes_diff
            df.at[i, 'completion_'] = (minutes_diff / original_duration)*100
    # Set the last row's completion to 1 since there's no row below it
    df.at[0, 'skip_next_track_'] = 0
    df.at[0, 'completion_'] = 100
    df['completion_'] = df['completion_']/100
    return df

In [62]:
df_n = compute_completion(df_s)
df_n["track_duration"] = df_n["track_duration"]/1000/60

In [63]:
df_n#[["track_name", "timestamp", "track_duration", "completion_", "skip_next_track_"]].tail(30)

,artist_name,album_name,track_name,timestamp,song_key,followers,artist_popularity,genre_1,genre_2,genre_3,...,tempo,track_duration,track_popularity,valence,new_artist_yn,new_recurring_artist_yn,new_track_yn,new_recurring_track_yn,skip_next_track_,completion_
0,Passion Pit,Chunk of Change,Sleepyhead,2023-08-31 09:07:00+00:00,Sleepyhead /: Passion Pit,1253329,59.0,indie rock,indietronica,modern rock,...,106.052,2.918000,44,0.764,0,0,0,0,0,1.00
1,The Paper Kites,On the Train Ride Home,Only One,2023-08-31 08:10:00+00:00,Only One /: The Paper Kites,642170,71.0,australian indie folk,indie folk,stomp and holler,...,96.912,4.195767,36,0.184,0,0,0,0,4,1.00
2,Penguin Cafe Orchestra,Union Cafe,LifeBoat (Lovers Rock),2023-08-31 08:03:00+00:00,LifeBoat (Lovers Rock) /: Penguin Cafe Orchestra,118410,42.0,bow pop,compositional ambient,NaN,...,178.94,7.261333,37,0.356,0,0,1,0,7,1.00
3,Real Estate,Days,It's Real,2023-08-31 07:55:00+00:00,It's Real /: Real Estate,386691,53.0,chillwave,dreamo,indie pop,...,152.009,2.808217,50,0.721,0,0,0,0,2,1.00
4,Kurt Vile,Bottle It In,Loading Zones,2023-08-31 07:51:00+00:00,Loading Zones /: Kurt Vile,480872,58.0,indie rock,modern folk rock,neo-psychedelic,...,112.22,3.385550,52,0.757,0,0,0,0,3,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269377,Eminem,Relapse: Refill,Hell Breaks Loose,2013-10-19 14:17:00+00:00,Hell Breaks Loose /: Eminem,67633798,94.0,detroit hip hop,hip hop,rap,...,79.901,4.068883,11,0.922,0,0,1,0,4,1.00
269378,Eminem,Relapse: Refill,Drop The Bomb On 'Em,2013-10-19 14:16:00+00:00,Drop The Bomb On 'Em /: Eminem,67633798,94.0,detroit hip hop,hip hop,rap,...,91.989,4.787767,48,0.357,0,0,1,0,1,0.20
269379,Eminem,Relapse: Refill,Medicine Ball,2013-10-19 14:14:00+00:00,Medicine Ball /: Eminem,67633798,94.0,detroit hip hop,hip hop,rap,...,119.858,3.955767,49,0.695,0,0,1,0,2,0.50
269380,Eminem,Relapse: Refill,We Made You,2013-10-19 14:14:00+00:00,We Made You /: Eminem,67633798,94.0,detroit hip hop,hip hop,rap,...,114.01,4.493767,20,0.654,0,0,1,0,0,0.00
269381,Eminem,Rap God,Rap God,2013-10-19 14:12:00+00:00,Rap God /: Eminem,67633798,94.0,detroit hip hop,hip hop,rap,...,148.222,6.058683,48,0.615,1,0,1,0,2,0.33

# Spotify test

In [6]:
import os
import pandas as pd
import json

In [7]:
folder_path = '../files/exports/spotify_exports/'

In [18]:
artist_names = []
album_names = []
track_names = []
timestamps = []

In [19]:
for filename in os.listdir(folder_path):
    if filename.endswith('.json'):
        print(filename)
        with open(os.path.join(folder_path, filename), 'r') as json_file:
            data = json.load(json_file)
            tracks = len(data)
            for t in range(tracks):
                artist_names.append(data[t]['master_metadata_album_artist_name'])
                album_names.append(data[t]['master_metadata_album_album_name'])
                track_names.append(data[t]['master_metadata_track_name'])
                timestamps.append(data[t]['ts'])

Streaming_History_Audio_2013-2017_0.json
Streaming_History_Audio_2021-2022_13.json
Streaming_History_Audio_2023_16.json
Streaming_History_Audio_2018_5.json
Streaming_History_Audio_2020_10.json
Streaming_History_Audio_2018_4.json
Streaming_History_Audio_2017_1.json
Streaming_History_Audio_2019_7.json
Streaming_History_Audio_2019-2020_9.json
Streaming_History_Audio_2022-2023_14.json
Streaming_History_Audio_2018-2019_6.json
Streaming_History_Audio_2020-2021_11.json
Streaming_History_Audio_2019_8.json
Streaming_History_Audio_2017-2018_3.json
Streaming_History_Audio_2017_2.json
Streaming_History_Audio_2021_12.json
Streaming_History_Audio_2023_15.json

In [83]:
data_dict = {
    'artist_name': artist_names,
    'album_name': album_names,
    'track_name': track_names,
    'timestamp' : timestamps
}

df_spot = pd.DataFrame(data_dict)
df_spot['timestamp'] = pd.to_datetime(df_spot['timestamp'], utc = True)
max_timestamp = df_spot["timestamp"].max()

In [85]:
df_spot.track_name.nunique()

12052

In [74]:
df_spot[df_spot['timestamp'] == max_timestamp]

,artist_name,album_name,track_name,timestamp,Source
35751,Phantastic Ferniture,Phantastic Ferniture,Fuckin 'N' Rollin,2023-08-24 09:53:05+00:00,Spotify

In [69]:
df = pd.read_csv(f"../files/exports/lfm_exports/lfm_export.csv", header = None)
df.columns = ['artist_name', 'album_name', 'track_name', 'timestamp']
#df["Source"] = "Last.FM"
df["timestamp"] = pd.to_datetime(df["timestamp"], utc = True)

In [70]:
filtered_df = df[df["timestamp"] > max_timestamp]

In [71]:
filtered_df

,artist_name,album_name,track_name,timestamp,Source
1,Passion Pit,Chunk of Change,Sleepyhead,2023-08-31 01:07:00+00:00,Last.FM
2,The Paper Kites,On the Train Ride Home,Only One,2023-08-31 00:10:00+00:00,Last.FM
3,Penguin Cafe Orchestra,Union Cafe,LifeBoat (Lovers Rock),2023-08-31 00:03:00+00:00,Last.FM
4,Real Estate,Days,It's Real,2023-08-30 23:55:00+00:00,Last.FM
5,Kurt Vile,Bottle It In,Loading Zones,2023-08-30 23:51:00+00:00,Last.FM
...,...,...,...,...,...
209,Men at Work,The Best Of Men At Work: Contraband,Down Under,2023-08-25 07:31:00+00:00,Last.FM
210,Wolf Alice,Spotify Singles,Don’t Delete the Kisses - Recorded at Strongro...,2023-08-25 07:27:00+00:00,Last.FM
211,The Killers,Battle Born,From Here on Out,2023-08-25 07:23:00+00:00,Last.FM
212,Mac Miller,Best Day Ever (5th Anniversary Remastered Edit...,Donald Trump,2023-08-25 07:20:00+00:00,Last.FM
213,Foals,What Went Down,London Thunder,2023-08-25 07:18:00+00:00,Last.FM

In [79]:
n_df = pd.concat([df_spot,filtered_df], ignore_index = True)

In [80]:
n_df['timestamp'] = pd.to_datetime(n_df['timestamp'], utc = True).dt.floor('T')

In [81]:
n_df

,artist_name,album_name,track_name,timestamp,Source
0,Eminem,Rap God,Rap God,2013-10-19 13:12:00+00:00,Spotify
1,Eminem,Relapse: Refill,We Made You,2013-10-19 13:14:00+00:00,Spotify
2,Eminem,Relapse: Refill,Medicine Ball,2013-10-19 13:14:00+00:00,Spotify
3,Eminem,Relapse: Refill,Drop The Bomb On 'Em,2013-10-19 13:16:00+00:00,Spotify
4,Eminem,Relapse: Refill,Hell Breaks Loose,2013-10-19 13:17:00+00:00,Spotify
...,...,...,...,...,...
269377,Men at Work,The Best Of Men At Work: Contraband,Down Under,2023-08-25 07:31:00+00:00,Last.FM
269378,Wolf Alice,Spotify Singles,Don’t Delete the Kisses - Recorded at Strongro...,2023-08-25 07:27:00+00:00,Last.FM
269379,The Killers,Battle Born,From Here on Out,2023-08-25 07:23:00+00:00,Last.FM
269380,Mac Miller,Best Day Ever (5th Anniversary Remastered Edit...,Donald Trump,2023-08-25 07:20:00+00:00,Last.FM
269381,Foals,What Went Down,London Thunder,2023-08-25 07:18:00+00:00,Last.FM

In [82]:
n_df.sort_values(by = "timestamp", ascending = False).drop_duplicates().drop

,artist_name,album_name,track_name,timestamp,Source
269170,Passion Pit,Chunk of Change,Sleepyhead,2023-08-31 01:07:00+00:00,Last.FM
269171,The Paper Kites,On the Train Ride Home,Only One,2023-08-31 00:10:00+00:00,Last.FM
269172,Penguin Cafe Orchestra,Union Cafe,LifeBoat (Lovers Rock),2023-08-31 00:03:00+00:00,Last.FM
269173,Real Estate,Days,It's Real,2023-08-30 23:55:00+00:00,Last.FM
269174,Kurt Vile,Bottle It In,Loading Zones,2023-08-30 23:51:00+00:00,Last.FM
...,...,...,...,...,...
4,Eminem,Relapse: Refill,Hell Breaks Loose,2013-10-19 13:17:00+00:00,Spotify
3,Eminem,Relapse: Refill,Drop The Bomb On 'Em,2013-10-19 13:16:00+00:00,Spotify
2,Eminem,Relapse: Refill,Medicine Ball,2013-10-19 13:14:00+00:00,Spotify
1,Eminem,Relapse: Refill,We Made You,2013-10-19 13:14:00+00:00,Spotify
0,Eminem,Rap God,Rap God,2013-10-19 13:12:00+00:00,Spotify

# Kindle test

In [2]:
import pandas as pd
import numpy as np

In [21]:
df = pd.read_csv("../files/processed_files/kindle_gr_processed.csv", sep = '|', encoding = 'utf-16')\
       .reset_index().rename(columns = {"index" : "rowNum"})

In [22]:
def duration(df, time, title, rowNum):
    max_time = df[df["Title"] == title].Timestamp.max()
    max_row = df[(df["Title"] == title) & (df["Timestamp"] == max_time)].rowNum.min()
    if (time == max_time) & (rowNum == max_row):
        return df[df["Title"] == title].reading_duration.max()
    else: 
        return np.nan
df["reading_duration"] = df.apply(lambda x: duration(df, x.Timestamp, x.Title, x.rowNum), axis = 1)

In [23]:
df[df.Title == 'The Grapes of Wrath']

,rowNum,Book Id,Title,Author,Original Publication Year,My Rating,Average Rating,Genre,Fiction_yn,reading_duration,Number of Pages,Timestamp,page_split,Seconds,Source,ASIN,NewSession,SessionDuration,duration
7824,7824,18114322,The Grapes of Wrath,John Steinbeck,1939.0,5.0,4.0,classics,non-fiction,10.0,479.0,2023-02-16 12:29:00,0.436187,31.0,Kindle,B09G6WDZ9J,0.0,0.516667,NaN
7825,7825,18114322,The Grapes of Wrath,John Steinbeck,1939.0,5.0,4.0,classics,non-fiction,NaN,479.0,2023-02-16 12:29:00,0.661551,9.1,Kindle,B09G6WDZ9J,1.0,NaN,NaN
7826,7826,18114322,The Grapes of Wrath,John Steinbeck,1939.0,5.0,4.0,classics,non-fiction,NaN,479.0,2023-02-16 12:27:00,0.844533,15.0,Kindle,B09G6WDZ9J,0.0,27.250000,NaN
7827,7827,18114322,The Grapes of Wrath,John Steinbeck,1939.0,5.0,4.0,classics,non-fiction,NaN,479.0,2023-02-16 12:26:00,0.844533,60.0,Kindle,B09G6WDZ9J,0.0,NaN,NaN
7828,7828,18114322,The Grapes of Wrath,John Steinbeck,1939.0,5.0,4.0,classics,non-fiction,NaN,479.0,2023-02-16 12:25:00,0.844533,60.0,Kindle,B09G6WDZ9J,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8426,8426,18114322,The Grapes of Wrath,John Steinbeck,1939.0,5.0,4.0,classics,non-fiction,NaN,479.0,2023-02-09 21:42:00,0.676586,60.0,Kindle,B09G6WDZ9J,0.0,NaN,NaN
8427,8427,18114322,The Grapes of Wrath,John Steinbeck,1939.0,5.0,4.0,classics,non-fiction,NaN,479.0,2023-02-09 21:41:00,0.676586,60.0,Kindle,B09G6WDZ9J,0.0,NaN,NaN
8428,8428,18114322,The Grapes of Wrath,John Steinbeck,1939.0,5.0,4.0,classics,non-fiction,NaN,479.0,2023-02-09 21:40:00,0.676586,60.0,Kindle,B09G6WDZ9J,0.0,NaN,NaN
8429,8429,18114322,The Grapes of Wrath,John Steinbeck,1939.0,5.0,4.0,classics,non-fiction,NaN,479.0,2023-02-09 21:39:00,0.676586,60.0,Kindle,B09G6WDZ9J,0.0,NaN,NaN
8430,8430,18114322,The Grapes of Wrath,John Steinbeck,1939.0,5.0,4.0,classics,non-fiction,NaN,479.0,2023-02-09 21:38:00,0.676586,20.0,Kindle,B09G6WDZ9J,1.0,NaN,NaN

In [133]:
df = df.iloc[5:]

In [136]:
df.reset_index(drop=True, inplace = True)

In [137]:
df

,ASIN,Book Id,Title,Timestamp,Seconds,page_split,Source,NewSession,SessionDuration
0,B0B6Z4SVTH,61714633.0,"The Wager: A Tale of Shipwreck, Mutiny and Murder",2023-07-26 21:56:00,60.0,3.183025,Kindle,0,0.000000
1,B0B6Z4SVTH,61714633.0,"The Wager: A Tale of Shipwreck, Mutiny and Murder",2023-07-26 21:55:00,60.0,3.183025,Kindle,0,0.000000
2,B0B6Z4SVTH,61714633.0,"The Wager: A Tale of Shipwreck, Mutiny and Murder",2023-07-26 21:54:00,60.0,3.183025,Kindle,0,0.000000
3,B0B6Z4SVTH,61714633.0,"The Wager: A Tale of Shipwreck, Mutiny and Murder",2023-07-26 21:53:00,60.0,3.183025,Kindle,0,0.000000
4,B0B6Z4SVTH,61714633.0,"The Wager: A Tale of Shipwreck, Mutiny and Murder",2023-07-26 21:52:00,60.0,3.183025,Kindle,0,0.000000
...,...,...,...,...,...,...,...,...,...
9200,B09G6WDZ9J,18114322.0,The Grapes of Wrath,2023-02-09 21:40:00,60.0,0.676586,Kindle,0,0.000000
9201,B09G6WDZ9J,18114322.0,The Grapes of Wrath,2023-02-09 21:39:00,60.0,0.676586,Kindle,0,0.000000
9202,B09G6WDZ9J,18114322.0,The Grapes of Wrath,2023-02-09 21:38:00,20.0,0.676586,Kindle,1,0.000000
9203,B09WDY29NM,60882951.0,Le Mage du Kremlin,2023-02-07 21:13:00,2.5,1.719347,Kindle,0,0.041667
9204,B09WDY29NM,60882951.0,Le Mage du Kremlin,2023-02-07 21:13:00,6.6,6.877389,Kindle,1,0.000000

In [128]:
def session_split(df, index):
    try:
        value = int((df["Timestamp"].iloc[index] - df["Timestamp"].iloc[index + 1]).seconds > 60)
    except IndexError:
        value = 1
    return value

In [129]:
def session_duration(df, rownum):
    new_df = df[df["RowNum"] >= rownum]
    session_duration = 0
    if rownum == 0:
        for _, row in new_df.iterrows():
            if row["NewSession"] == 0:
                session_duration += row["Seconds"] 
            else: 
                break
    elif (df[df["RowNum"] == rownum]["NewSession"][rownum] == 0) & (df[df["RowNum"] == rownum - 1]["NewSession"][rownum - 1] == 1):
        for _, row in new_df.iterrows():
            if row["NewSession"] == 0:
                session_duration += row["Seconds"] 
            else: 
                break
    return session_duration/60

In [130]:
df['Timestamp'] = pd.to_datetime(df['Timestamp'])
df['NewSession'] = df.apply(lambda x: session_split(df, x.RowNum), axis = 1)
df['SessionDuration'] = df.apply(lambda x: session_duration(df, x.RowNum), axis = 1)

In [131]:
df.drop("RowNum", axis = 1, inplace = True)

In [132]:
df

,ASIN,Book Id,Title,Timestamp,Seconds,page_split,Source,NewSession,SessionDuration
0,B0B6Z4SVTH,61714633.0,"The Wager: A Tale of Shipwreck, Mutiny and Murder",2023-07-26 22:00:00,4.7,0.722532,Kindle,0,0.318333
1,B004W2UBYW,11084145.0,Steve Jobs,2023-07-26 21:59:00,10.1,0.587770,Kindle,0,0.000000
2,B0B6Z4SVTH,61714633.0,"The Wager: A Tale of Shipwreck, Mutiny and Murder",2023-07-26 21:59:00,4.3,0.722532,Kindle,0,0.000000
3,B0B6Z4SVTH,61714633.0,"The Wager: A Tale of Shipwreck, Mutiny and Murder",2023-07-26 21:59:00,8.8,0.722532,Kindle,1,0.000000
4,B0B6Z4SVTH,61714633.0,"The Wager: A Tale of Shipwreck, Mutiny and Murder",2023-07-26 21:57:00,59.0,3.183025,Kindle,0,30.900000
...,...,...,...,...,...,...,...,...,...
9205,B09G6WDZ9J,18114322.0,The Grapes of Wrath,2023-02-09 21:40:00,60.0,0.676586,Kindle,0,0.000000
9206,B09G6WDZ9J,18114322.0,The Grapes of Wrath,2023-02-09 21:39:00,60.0,0.676586,Kindle,0,0.000000
9207,B09G6WDZ9J,18114322.0,The Grapes of Wrath,2023-02-09 21:38:00,20.0,0.676586,Kindle,1,0.000000
9208,B09WDY29NM,60882951.0,Le Mage du Kremlin,2023-02-07 21:13:00,2.5,1.719347,Kindle,0,0.041667
9209,B09WDY29NM,60882951.0,Le Mage du Kremlin,2023-02-07 21:13:00,6.6,6.877389,Kindle,1,0.000000

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('processed_files/offscreen_processed.csv', sep = '|')
df2 = pd.read_csv('processed_files/garmin_sleep_processed.csv', sep = '|')

In [62]:
df['date'] = pd.to_datetime(df.date).dt.tz_localize(None)
df['sleepDate'] = df.date.apply(lambda x: x - pd.Timedelta(days = 1) if x.hour < 6 else x).dt.date
df['sleepDate'] = pd.to_datetime(df.sleepDate).dt.tz_localize(None)

In [64]:
df2['sleepDate'] = pd.to_datetime(df2.calendarDate).dt.tz_localize(None) - pd.Timedelta(days = 1)

In [65]:
# Merge df and df2 based on a common identifier (e.g., date)
merged_df = pd.merge(df, df2[['sleepDate', "sleepStartTimestampLocal"]], on='sleepDate', how='left')

In [77]:
merged_df['time_diff'] = pd.to_datetime(merged_df['sleepStartTimestampLocal']) - merged_df['date']

In [78]:
merged_df['within_hour_before_sleep'] = merged_df['time_diff'].apply(lambda x: 1 if x <= pd.Timedelta(hours=1) else 0)

In [83]:
merged_df[merged_df['within_hour_before_sleep'] == 1]

,date,screen_time,pickups,sleepDate,sleepStartTimestampLocal,time_diff,within_hour_before_sleep
86,2023-04-25 22:58:00,0.0,1.0,2023-04-25,2023-04-25 23:44:00,0 days 00:46:00,1
87,2023-04-25 22:59:00,15.0,0.0,2023-04-25,2023-04-25 23:44:00,0 days 00:45:00,1
221,2023-04-26 23:51:00,54.0,1.0,2023-04-26,2023-04-27 00:18:00,0 days 00:27:00,1
222,2023-04-26 23:52:00,60.0,0.0,2023-04-26,2023-04-27 00:18:00,0 days 00:26:00,1
223,2023-04-26 23:53:00,60.0,0.0,2023-04-26,2023-04-27 00:18:00,0 days 00:25:00,1
...,...,...,...,...,...,...,...
10589,2023-06-09 23:35:00,6.0,0.0,2023-06-09,2023-06-10 00:18:00,0 days 00:43:00,1
10590,2023-06-09 23:39:00,4.0,1.0,2023-06-09,2023-06-10 00:18:00,0 days 00:39:00,1
10591,2023-06-09 23:40:00,1.0,0.0,2023-06-09,2023-06-10 00:18:00,0 days 00:38:00,1
10592,2023-06-09 23:51:00,39.0,1.0,2023-06-09,2023-06-10 00:18:00,0 days 00:27:00,1
10593,2023-06-09 23:52:00,10.0,0.0,2023-06-09,2023-06-10 00:18:00,0 days 00:26:00,1

In [82]:
import requests

# Specify the API endpoint and the UUID of the podcast episode
api_url = 'https://api.taddyfordevelopers.com/api/podcasts/episodes/'
episode_uuid = '06890e00-627f-0134-787d-4ffec63d9550'

# Specify your API key
api_key = 'b72185f10b5c9f04917ebe0878a8ce2c6e3d020258ab779277a818b7c4a316d7910dcac3fa5df0611a077143c7b41cd0ad'

# Set the headers with the API key
headers = {
    'Authorization': f'Bearer {api_key}'
}

# Send the API request with headers
response = requests.get(api_url + episode_uuid, headers=headers)

# Check if the request was successful (status code 200)
if response.status_code == 200:
    episode_data = response.json()
    # Process the retrieved episode data as needed
    print("Podcast Episode Title:", episode_data['title'])
    print("Podcast Episode Description:", episode_data['description'])
    # Add any other desired information extraction or processing

else:
    print("Error occurred while fetching the podcast episode:", response.status_code)

ConnectionError: HTTPSConnectionPool(host='api.taddyfordevelopers.com', port=443): Max retries exceeded with url: /api/podcasts/episodes/06890e00-627f-0134-787d-4ffec63d9550 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10b866dc0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

In [ ]:
import pandas as pd
pd.set_option('display.max_column',None)

In [ ]:
df_gr = pd.read_csv('processed_files/gr_processed.csv', sep ='|')

In [ ]:
df_kl = pd.read_csv('processed_files/kindle_processed.csv', sep = '|')

In [ ]:
df_kl['Source'] = 'Kindle'
df_gr['Source'] = 'GoodReads'

In [ ]:
import numpy as np
df_gr['Seconds'] = np.nan
df_kl.rename(columns = {'Pages' : 'page_split'}, inplace = True)

In [ ]:
columns = list(df_gr.columns[2:-4])
columns.append('Book Id')
df[columns]

,Author,Original Publication Year,My Rating,Average Rating,reading_duration,Number of Pages,Book Id
567495,William L. Shirer,1960.0,5.0,4.19,30.0,1614.0,767171.0
567496,William L. Shirer,1960.0,5.0,4.19,30.0,1614.0,767171.0
567497,William L. Shirer,1960.0,5.0,4.19,30.0,1614.0,767171.0
567498,William L. Shirer,1960.0,5.0,4.19,30.0,1614.0,767171.0
567499,William L. Shirer,1960.0,5.0,4.19,30.0,1614.0,767171.0
...,...,...,...,...,...,...,...
567557,Carol Leonnig,2021.0,3.0,4.40,NaN,476.0,58412441.0
567558,Emmanuel Carrère,2011.0,5.0,4.12,NaN,489.0,12151198.0
567559,Vincent Hugeux,NaN,4.0,3.00,NaN,359.0,36556984.0
567560,Gérard Davet,NaN,4.0,3.67,NaN,638.0,59341911.0
567561,Peter Thomas Fornatale,2007.0,5.0,4.38,NaN,412.0,1300234.0

In [ ]:
enhanced_kl=pd.merge(df_kl, df_gr[columns], on = 'Book Id', how = 'left')
dd = pd.concat([df_gr, enhanced_kl], ignore_index = True)

In [ ]:
# Group the dataframe by book title
groups = dd.groupby(['Title'])
gr_only = [g['Title'].values[0] for index, g in groups if all(g['Source'] == 'GoodReads')]
gr_df = dd[dd['Title'].isin(gr_only)]
kl_df = dd[dd['Source'] == 'Kindle']
df = pd.concat([kl_df, gr_df], ignore_index=True).sort_values('Timestamp')

# Garmin Training history

In [ ]:
def extract_fit_files_path(folder_path):
    """
    Returns a list of paths to all .fit files in the specified folder and its subfolders.
    """
    fit_files = []
    for root, _, filenames in os.walk(folder_path):
        for filename in fnmatch.filter(filenames, '*.fit'):
            fit_files.append(os.path.join(root, filename))
    return fit_files

In [ ]:
folder_path = "exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1"

In [ ]:
dict_files_checked = {}
for file in fit_files:
    dict_files_checked[file] = 'Yes'
df = pd.DataFrame(dict_files_checked, index = [0]).transpose().reset_index()
df.columns = ['file', 'checked']
df.to_csv('work_files/processed_fit_files.csv', sep = '|', index = False)

In [ ]:
len(new_fit_files)

552

In [ ]:
list(df_stress_level.file_name.unique())

['exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180671160815.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181497016788.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175335384999.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179728414555.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176629551939.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179713965920.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180814096568.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175650203439.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181626313788.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176186784763.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180065904191.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175131402109.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178529789703.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175874923111.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182583168233.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_183263264474.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176244588221.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178091185956.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182092295654.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176380609106.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177929248110.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174981891014.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176185862145.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177400511267.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174894176567.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177086038291.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175004452961.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175268208271.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178260750735.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175580328972.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181953798797.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181626797686.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182092140980.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180738317486.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174893137406.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179713941649.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179728553792.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177864816091.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175485934109.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176341904973.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178529809291.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176937377768.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176394685891.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175354505733.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175354921754.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179174299602.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178394880384.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175874949251.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179728771761.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180031279840.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176937384391.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180051353278.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179173071029.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179174234224.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182466703259.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176761230845.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175649279901.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180987339610.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181953776159.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179403387267.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175938365141.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175724424423.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175948984293.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176657682490.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175724251542.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174893524617.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175029271058.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_183101453542.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175649917764.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178218136009.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180352851049.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175485919573.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180995271283.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178394906755.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175112898304.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181625675863.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175029225543.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178091154836.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177084777071.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179403576763.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_183101476306.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181953806264.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177586251789.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182266768560.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174959604532.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177084787977.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180032313772.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180670873436.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184507515424.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182583150245.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179713980315.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184074942212.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175354155807.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175889706405.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177252064470.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175891618840.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180664399163.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177586281220.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174893282931.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181626202384.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175647515093.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184248812325.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178789773843.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180031293631.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176185873366.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184823446419.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180994711861.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175267897200.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184823412510.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_183413394136.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181495952975.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174958566196.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180664359378.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175031488952.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175649959963.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179713926473.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184074407919.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184107418743.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179417961109.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177586279413.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175666283500.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179714039973.fit',

In [ ]:
'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181497016788.fit' in list(df_stress_level.file_name.unique())

True

In [ ]:
fit_files = extract_fit_files_path(folder_path)
data = []
fit_file_name = []
df_stress_level = pd.read_csv('processed_files/garmin_stress_level_processed.csv', sep = '|')
new_fit_files = []
for fit_file in fit_files:
    print(fit_file)
    if fit_file not in list(df_stress_level.file_name.unique()):
        new_fit_files.append(fit_file)
new_fit_files

exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178789782410.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_183413433407.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181497017694.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180671161289.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174892938107.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175874972361.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180671160815.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181626393566.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182266779395.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184074433775.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175874952270.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181497016788.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_183413439466.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175335384999.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179728414555.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177084789052.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176629551939.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176109260084.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180031323974.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175649676871.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178529810472.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179713965920.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176500578494.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176937385672.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179728772046.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178789783493.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181495978308.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176629558316.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180814096568.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175354922106.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178091190141.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184074442239.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181495979957.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175650203439.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181626313788.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176186784763.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175916263670.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181626394142.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184507517455.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180065904191.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181953745917.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181953810300.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179403401004.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175029292217.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180031323154.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180032314531.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180352361707.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184074438386.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182583348398.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174892938674.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176500570397.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179173185813.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175131402109.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178529789703.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177864827116.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177864831990.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175874923111.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175579075581.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178218159646.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182583168233.fit

exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175485935561.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_183263264474.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177864838585.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181496016298.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176244588221.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178091185956.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175874949928.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175724267052.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177586313902.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180352851821.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184107087031.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182583170050.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182745248258.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182092295654.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174893723413.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_183101478374.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176380609106.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177929248110.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174981891014.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177720558138.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175028156886.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180670874925.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177720536434.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180830550703.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176185862145.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184074436035.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175666284039.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177400511267.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184507515692.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176500570828.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174894176567.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176380610053.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178091187946.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177086038291.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177586295347.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175004452961.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181495981630.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175724425403.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176629560714.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175889723580.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175354156174.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182466741083.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179713982549.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179403429412.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175268208271.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174893137765.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182895406243.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176380614231.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178789755164.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177586282398.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178260750735.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175112927802.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175889723976.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176937397304.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180051354313.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175579076462.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180738324267.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179417963384.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177864827503.fit

exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175580328972.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176380609664.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177400511854.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181495982507.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181953798797.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175487000136.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180352333899.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181626797686.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182092140980.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180738317486.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174893137406.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176394687458.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180065907139.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179713941649.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179728553792.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178218173691.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177864816091.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178091187016.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177084791168.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179173200441.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181953809051.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175485934109.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176341921265.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176341904973.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178529809291.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175579094009.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180670874471.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175485938519.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180352341410.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176937377768.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176394685891.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184507527431.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175354505733.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184254120209.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181953809709.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175354921754.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174894177695.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175649789136.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179174299602.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179728415921.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182583138589.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181953829234.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178394880384.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175874949251.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181953772403.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184248571691.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179417965523.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180994712265.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179728771761.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176380610479.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180031279840.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179713983084.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178091186531.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182466742173.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184823501308.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179173186700.fit

exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184823492212.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176185875403.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176033107661.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175029433081.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177252089176.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179714013110.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176937384391.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180051353278.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179173071029.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182092158935.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175112911829.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179174234224.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182466703259.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182266757508.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175649749994.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175874953469.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175649280787.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182092143433.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180814110183.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176761230845.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175580329572.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175874904055.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184823462019.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184248601948.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176629556172.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176757645215.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175649279901.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181495983318.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181953824010.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179174300290.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180987339610.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181953807420.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180994710398.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175666284448.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181953776159.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175647130395.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180352335532.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181495992758.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180738318075.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179403387267.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182092142880.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174893283383.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175938365141.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179728415007.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180994712983.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175724424423.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175948984293.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175354506103.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176657682490.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175724251542.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184107084001.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178260754443.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179728554098.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174893524617.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176573377526.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179173184950.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180031322229.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175938365592.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184074510131.fit

exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175029271058.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181625688867.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_183101453542.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178218159169.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178789783234.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179417959120.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178394911571.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_183263289760.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175649917764.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182466754824.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178218136009.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180352851049.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179713999657.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176341920678.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179728964129.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182266778599.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175335386493.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179713981973.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178218158077.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180987359246.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176757658119.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175485919573.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180995271283.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178394909300.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178394906755.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177720538296.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175029271700.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181495976609.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175112898304.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179729595289.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176033092408.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182266947986.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_183263266412.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180352334439.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181625675863.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175029225543.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178091154836.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180664418186.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177084777071.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178529811240.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175889707252.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_183101501831.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_183101477031.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177252077145.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182266779727.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179403576763.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175335385990.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_183101476306.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181626798289.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175199560141.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179713981379.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177720535638.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179403421411.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176109259658.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181953806264.fit

exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178789782707.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177586251789.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175267901846.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182266768560.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174959604532.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177084787977.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180814110803.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180032313772.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180670873436.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184507515424.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176186786909.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181495979117.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182905063307.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175874950600.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182583150245.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180352334986.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179713980315.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184074942212.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176185879338.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175335370882.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180664419128.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178091150704.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175354155807.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182745246603.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179713990462.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179403402233.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175889706405.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175647515643.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177586312887.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174959639072.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184248603787.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177252064470.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175004456194.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179417948348.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181953808073.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175891618840.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180664399163.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178394879557.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180814121239.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175028145446.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177586281220.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184507516909.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175650204332.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175874965094.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176341920093.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174893282931.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175267898535.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181626202384.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182905068119.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177720501567.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176657687277.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175647515093.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182895394040.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175622675056.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184248812325.fit

exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178789773843.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179403404723.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182092151232.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180031293631.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182583187534.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178218400776.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175622668205.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176185874423.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180987358148.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176185873366.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184823446419.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175028410063.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176629556573.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175649918137.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180994711861.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175267897200.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175891619397.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177400513616.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178091187507.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181626202972.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178260751311.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182269833066.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184823412510.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177252077547.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175131403099.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_183413394136.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179728412630.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181495952975.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176109259139.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178218132690.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174958566196.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175649280423.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180352333350.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180065906246.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175485934578.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175666285790.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182583171303.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_183101477751.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179403403489.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180664359378.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175031488952.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180987367542.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175649959963.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179403405953.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179713926473.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180814114256.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176761231424.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184074407919.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184107418743.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175200966081.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180664420797.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175485915616.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182266787038.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180670875531.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179173502247.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184823460420.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180352258876.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179417961109.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175916260243.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177586279413.fit

exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176244588664.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180830549616.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175666283500.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181953810974.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175916355550.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179714039973.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182092296903.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175112910754.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178789759040.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184107083148.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179421504042.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_183101655140.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179417967039.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182092129595.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175112911258.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184074432549.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180065910399.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174892937666.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175647123690.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176573378190.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175485916500.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180352332730.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184107419336.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175874980980.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181639544194.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175724267563.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177929248839.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180664380400.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179729178894.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179714040876.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181639544618.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176657683234.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179417964848.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181639543836.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175335394698.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184823459871.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182895394675.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175029432509.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181496055450.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182895414206.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184823460969.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175199567778.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_183413459306.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175354157950.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175112912618.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_183413430415.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182269832407.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179729594956.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182745270354.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182092296282.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184507517207.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178091207429.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179403399867.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181953808447.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177086040194.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174958586870.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182466772624.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174958579126.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184248572900.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175199559694.fit

exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176033091929.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180353131140.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_183101655989.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180987378134.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178218400357.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181953813846.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179403349703.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175580330363.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178789793400.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180065900412.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176500569094.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184074496773.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175647131095.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179728415540.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180031319698.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181639543148.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182466740536.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179714021535.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175268209263.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178218160641.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176185873977.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181495980829.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175891619825.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175485936771.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180830546094.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180352370139.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181625665926.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175647129793.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175579057763.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178394907872.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177720534665.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175131405828.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179728963843.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184074477407.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179417964095.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182092141549.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176244595627.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174959605423.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174958571782.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180664416776.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181953782404.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179418070235.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175004453608.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184074434937.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175889975616.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180352272514.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184507506870.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184074440867.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181495977527.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182266778187.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175267897801.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175649960333.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179417965984.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175486999571.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182745233134.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175267910588.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174893403098.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180031349733.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179421502780.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180830551665.fit

exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180051356787.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180671904377.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177720537220.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184507516083.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182466741610.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174893403715.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178789797688.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181639541028.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175579074746.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184507488325.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174893722979.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181955980354.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180678586988.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176657683811.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177252076120.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176937385019.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177252076646.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179173187265.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175485920880.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181955980036.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181495843278.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179417966678.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176757658869.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176629555930.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184248600866.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182745247717.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175874933387.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176573377105.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176757643520.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180664417482.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176109242896.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182583169425.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176500569694.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177084806467.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175268208797.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184074437232.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184507517759.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184823461508.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178394912908.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180994712636.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175724281550.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175028152496.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182745260751.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175916259757.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176185886084.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179174327390.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175029226284.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178789785258.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174981893875.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175948984922.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180352336023.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175647133691.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180814108845.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184107074671.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176573385596.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177252082303.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175579082789.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178789781771.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174899469973.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180031344995.fit

exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175622667316.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175649748852.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180830550196.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174958579647.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176033098077.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174981891681.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184248598676.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174893525101.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179403407778.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175622655171.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184074301973.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176109258670.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177400534563.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175889976144.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179173501720.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181495863682.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184823470891.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179174234956.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175938369300.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184507490650.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179418069729.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175579077175.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175028153881.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181496040942.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180664419781.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175948985864.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175622668644.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177864826809.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182745215196.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175889708652.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182895393346.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175203094396.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180671905018.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174958592247.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179729178613.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182583170701.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180065905292.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182266793368.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178529812709.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175649788755.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184250985647.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180814109532.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180065908577.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177586283103.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176033076057.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175203094977.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174900068920.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175666280269.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180031357637.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182905067326.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174892936136.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175031489559.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184507516636.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174900068505.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174900557516.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179173248839.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175485939150.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180353130639.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180678586455.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174959604954.fit

exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179174327929.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184248813069.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182266947668.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184248603111.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179173183064.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176761231918.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178529811821.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176109269121.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180995271570.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175335385455.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177400514303.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_183263273920.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180987357605.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175724270282.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176033089718.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179173130682.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175649676476.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182745247176.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182895392701.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177084790119.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184074942693.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175028153505.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177084798550.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182583347857.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179174966552.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181953806742.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184107085160.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184250987053.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175485948804.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175647128954.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177928341943.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184074439496.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174900559128.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182745246080.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180664429085.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181639543513.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180031320480.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179713980838.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176341930370.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175724268023.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179174967089.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176394689055.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175200965645.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179173184285.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180987358696.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184254119653.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175650356584.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180675704361.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181495975753.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177720545028.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175029292625.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174958582862.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180031308122.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178394910366.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177864827867.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175650357113.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184074460849.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177928334738.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182905069318.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175267884956.fit

exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180664451853.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181495984590.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184074338306.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174981891353.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_183413429691.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175112919932.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177400520935.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184248599694.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176500554824.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175028151869.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180675703768.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175028409611.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176033091185.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175131402715.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175724266181.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180670872632.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176500591007.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178394924612.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181639541710.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180031321374.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175485935183.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174899470926.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174959639555.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180830549048.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180664460906.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178218157538.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184074440150.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184507531884.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178789782973.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175916355124.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175874954009.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_183413431140.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180051358247.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174899470265.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179417962938.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177252075462.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176937386229.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178529823840.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181626314375.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_183101487025.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175029225883.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177928335433.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182583168772.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184250986216.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182583178577.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176341919083.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181495907473.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175889706915.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184248616240.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181625677177.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180031330858.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179403347429.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177586283729.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176341939958.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178789782018.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176244589130.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181625685281.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179403577389.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176186786145.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176380601596.fit

exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182266779005.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178218158620.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184823459195.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180664441539.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184074433181.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179173233136.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_183263265837.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182895379566.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180352314828.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176033064250.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_183263234517.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177720513095.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181625676532.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176937391781.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_183263265228.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177086039180.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179403407096.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177400495430.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176757645864.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184074370142.fit
exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176757644561.fit

['exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178789782410.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_183413433407.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181497017694.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180671161289.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174892938107.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175874972361.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181626393566.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182266779395.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184074433775.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175874952270.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_183413439466.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177084789052.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176109260084.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180031323974.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175649676871.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178529810472.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176500578494.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176937385672.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179728772046.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178789783493.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181495978308.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176629558316.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175354922106.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178091190141.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184074442239.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181495979957.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175916263670.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181626394142.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184507517455.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181953745917.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181953810300.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179403401004.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175029292217.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180031323154.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180032314531.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180352361707.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184074438386.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182583348398.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174892938674.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176500570397.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179173185813.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177864827116.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177864831990.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175579075581.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178218159646.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175485935561.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177864838585.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181496016298.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175874949928.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175724267052.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177586313902.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180352851821.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184107087031.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182583170050.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182745248258.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174893723413.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_183101478374.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177720558138.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175028156886.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180670874925.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177720536434.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180830550703.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184074436035.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175666284039.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184507515692.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176500570828.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176380610053.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178091187946.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177586295347.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181495981630.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175724425403.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176629560714.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175889723580.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175354156174.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182466741083.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179713982549.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179403429412.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174893137765.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182895406243.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176380614231.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178789755164.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177586282398.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175112927802.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175889723976.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176937397304.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180051354313.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175579076462.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180738324267.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179417963384.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177864827503.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176380609664.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177400511854.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181495982507.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175487000136.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180352333899.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176394687458.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180065907139.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178218173691.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178091187016.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_177084791168.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179173200441.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181953809051.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176341921265.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175579094009.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180670874471.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175485938519.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180352341410.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184507527431.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184254120209.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181953809709.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_174894177695.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_175649789136.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179728415921.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_182583138589.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181953829234.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_181953772403.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_184248571691.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179417965523.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_180994712265.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_176380610479.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_179713983084.fit',
 'exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/UploadedFiles_0-_Part1/valentin.herinckx@gmail.com_178091186531.fit',

In [ ]:
for fit_file in new_fit_files:
        fitfile = fitparse.FitFile(fit_file)
        for record in fitfile.get_messages("stress_level"):
            r = record.get_values()
            data.append(r)
            fit_file_name.append(fit_file)
if len(data) > 0:
    df = pd.DataFrame(data)
    df['file_name'] = fit_file_name
    df_stress_level = pd.concat([df_stress_level,df], ignore_index=True).reset_index(drop = True).sort_values('stress_level_time').drop_duplicates()
df_stress_level.to_csv('processed_files/garmin_stress_level_processed.csv', sep = '|', index = False)

In [ ]:

df = pd.read_csv('/Users/valen/code/VaHerinckx/LifeLog_Project/exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness-Uploaded-Files/cleaned_raw.csv', sep = '|')

In [ ]:
from selenium import webdriver

DRIVER_PATH = ''
driver = webdriver.Chrome(executable_path= 'chromedriver_mac64(2)/chromedriver')
driver.get("https://www.nintendo.com/")
print(driver.page_source)
driver.quit()

/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_99196/68384337.py:4: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(executable_path= 'chromedriver_mac64(2)/chromedriver')

<html lang="en-us" class="js-focus-visible svg cssanimations flexboxlegacy fontface csstransforms supports csstransforms3d csstransitions inlinesvg alps-os-mac" data-js-focus-visible="" style="--app-height:887px;"><head><meta charset="utf-8"><title>Nintendo Official Site: Consoles, Games, News, and More</title><link rel="canonical" href="https://www.nintendo.com/"><meta http-equiv="Accept-CH" content="DPR, Width"><meta name="description" content="Visit the official Nintendo site to shop for Nintendo Switch™ systems and video games, read the latest news, find fun gear and gifts with a Nintendo twist, and much more."><meta name="twitter:card" content="summary_large_image"><meta name="twitter:site" content="@nintendoamerica"><meta property="og:type" content="website"><meta property="og:title" name="twitter:title" content="Nintendo Official Site: Consoles, Games, News, and More"><meta property="og:description" name="twitter:description" content="Visit the official Nintendo site to shop for Nintendo Switch™ systems and video games, read the latest news, find fun gear and gifts with a Nintendo twist, and much more."><meta property="og:image" name="twitter:image" content="https://assets.nintendo.com/image/upload/v1643742733/ncom/global/social-share.jpg"><meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=yes"><meta name="msvalidate.01" content="CD9A42A71E67EDC970DE6AD9919B5D79"><meta name="google-site-verification" content="lcC2m3GxLFXRpw4s4cKbn8Q6jDs8zHPXp9CC1xHn70c"><meta name="p:domain_verify" content="5acad0d13ae7c1954a606b71572e61ea"><meta name="ps-key" content="3623-5dc435df8b867f001f540866"><meta name="ps-country" content="US"><meta name="ps-language" content="en"><meta property="fb:app_id" content="549513175162968"><link rel="apple-touch-icon" sizes="180x180" href="https://assets.nintendo.com/image/upload/ncom/icons/fav-icons/apple-touch-icon.png"><link rel="icon" type="image/png" sizes="32x32" href="https://assets.nintendo.com/image/upload/ncom/icons/fav-icons/favicon-32x32.png"><link rel="icon" type="image/png" sizes="16x16" href="https://assets.nintendo.com/image/upload/ncom/icons/fav-icons/favicon-16x16.png"><link rel="manifest" href="https://assets.nintendo.com/raw/upload/v1666282340/ncom/icons/fav-icons/site.webmanifest"><link rel="shortcut icon" href="https://assets.nintendo.com/image/upload/ncom/icons/fav-icons/favicon.ico"><meta name="msapplication-TileColor" content="#e60012"><meta name="msapplication-config" content="https://assets.nintendo.com/image/upload/ncom/icons/fav-icons/browserconfig.xml"><meta name="theme-color" content="#e60012"><link rel="alternate" hreflang="en-us" href="https://www.nintendo.com/"><link rel="alternate" hreflang="en-ca" href="https://www.nintendo.com/en-ca/"><link rel="alternate" hreflang="fr-ca" href="https://www.nintendo.com/fr-ca/"><link rel="alternate" hreflang="es-mx" href="https://www.nintendo.com/es-mx/"><link rel="alternate" hreflang="pt-br" href="https://www.nintendo.com/pt-br/"><link rel="alternate" hreflang="es-ar" href="https://www.nintendo.com/es-ar/"><link rel="alternate" hreflang="es-cl" href="https://www.nintendo.com/es-cl/"><link rel="alternate" hreflang="es-co" href="https://www.nintendo.com/es-co/"><link rel="alternate" hreflang="es-pe" href="https://www.nintendo.com/es-pe/"><link rel="alternate" hreflang="en-sg" href="https://www.nintendo.com/sg/"><link rel="alternate" hreflang="th-th" href="https://www.nintendo.com/th/"><link rel="alternate" hreflang="en-my" href="https://www.nintendo.com/my/"><link rel="alternate" hreflang="en-ph" href="https://www.nintendo.com/ph/"><meta name="next-head-count" content="40"><link rel="preconnect" crossorigin="true" data-href="https://use.typekit.net"><link rel="preconnect" href="https://p.typekit.net"><link rel="preconnect" href="https://assets.nintendo.com/"><meta name="google-site-verification" content="4IkNV7wLiuuKZAlobHQwPcOeudYa4_2Okpyu7-eENWk"><link rel="preconnect" href="https://use.typekit.net" crossorigin=""><noscript data-n-css=""></noscript><script type="text/javascript" async="" src="https://cdn.quantummetric.com/qscripts/quantum-nintendo.js"></script><script type="text/javascript" async="" src="https://www.google-analytics.com/analytics.js"></script><script defer="" nomodule="" src="/_next/static/chunks/polyfills-c67a75d1b6f99dc8.js"></script><script src="https://polyfill.io/v3/polyfill.min.js?features=Intl%2CIntersectionObserver%2CIntl.Locale%2CIntl.NumberFormat%2CResizeObserver%2CMediaQueryList.prototype.removeEventListener%2CMediaQueryList.prototype.addEventListener" defer="" data-nscript="beforeInteractive"></script><script src="/_next/static/chunks/webpack-c1e2034911293640.js" defer=""></script><script src="/_next/static/chunks/framework-72516398fc9e6c02.js" defer=""></script><script src="/_next/static/chunks/main-efb227f904845412.js" defer=""></script><script src="/_next/static/chunks/pages/_app-1d93a6eec1f87b76.js" defer=""></script><script src="/_next/static/chunks/pages/index-7bf24286bd003f8c.js" defer=""></script><script src="/_next/static/yGIWMVXLs5GBkz0LnK71u/_buildManifest.js" defer=""></script><script src="/_next/static/yGIWMVXLs5GBkz0LnK71u/_ssgManifest.js" defer=""></script><style data-styled="active" data-styled-version="5.3.9"></style><style data-href="https://use.typekit.net/wyv1nqp.css">@import url("https://p.typekit.net/p.css?s=1&k=wyv1nqp&ht=tk&f=2005.2006.2009.2010.2011.2012.9938.9939.39002.39004.17398.17399.17400.17401.22618.22619&a=8805231&app=typekit&e=css");@font-face{font-family:"museo-sans";src:url("https://use.typekit.net/af/620bf8/00000000000000000000e7fe/27/l?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=n3&v=3") format("woff2"),url("https://use.typekit.net/af/620bf8/00000000000000000000e7fe/27/d?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=n3&v=3") format("woff"),url("https://use.typekit.net/af/620bf8/00000000000000000000e7fe/27/a?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=n3&v=3") format("opentype");font-display:auto;font-style:normal;font-weight:300;font-stretch:normal}@font-face{font-family:"museo-sans";src:url("https://use.typekit.net/af/5cca6d/00000000000000000000e802/27/l?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=i3&v=3") format("woff2"),url("https://use.typekit.net/af/5cca6d/00000000000000000000e802/27/d?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=i3&v=3") format("woff"),url("https://use.typekit.net/af/5cca6d/00000000000000000000e802/27/a?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=i3&v=3") format("opentype");font-display:auto;font-style:italic;font-weight:300;font-stretch:normal}@font-face{font-family:"museo-sans";src:url("https://use.typekit.net/af/e3ca36/00000000000000000000e805/27/l?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=n7&v=3") format("woff2"),url("https://use.typekit.net/af/e3ca36/00000000000000000000e805/27/d?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=n7&v=3") format("woff"),url("https://use.typekit.net/af/e3ca36/00000000000000000000e805/27/a?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=n7&v=3") format("opentype");font-display:auto;font-style:normal;font-weight:700;font-stretch:normal}@font-face{font-family:"museo-sans";src:url("https://use.typekit.net/af/2841b6/00000000000000000000e806/27/l?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=i7&v=3") format("woff2"),url("https://use.typekit.net/af/2841b6/00000000000000000000e806/27/d?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=i7&v=3") format("woff"),url("https://use.typekit.net/af/2841b6/00000000000000000000e806/27/a?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=i7&v=3") format("opentype");font-display:auto;font-style:italic;font-weight:700;font-stretch:normal}@font-face{font-family:"museo-sans";src:url("https://use.typekit.net/af/9cf49e/00000000000000000000e807/27/l?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=n9&v=3") format("woff2"),url("https://use.typekit.net/af/9cf49e/00000000000000000000e807/27/d?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=n9&v=3") format("woff"),url("https://use.typekit.net/af/9cf49e/00000000000000000000e807/27/a?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=n9&v=3") format("opentype");font-display:auto;font-style:normal;font-weight:900;font-stretch:normal}@font-face{font-family:"museo-sans";src:url("https://use.typekit.net/af/27c143/00000000000000000000e808/27/l?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=i9&v=3") format("woff2"),url("https://use.typekit.net/af/27c143/00000000000000000000e808/27/d?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=i9&v=3") format("woff"),url("https://use.typekit.net/af/27c143/00000000000000000000e808/27/a?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=i9&v=3") format("opentype");font-display:auto;font-style:italic;font-weight:900;font-stretch:normal}@font-face{font-family:"museo-sans-rounded";src:url("https://use.typekit.net/af/491586/00000000000000003b9b1e2d/27/l?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=n3&v=3") format("woff2"),url("https://use.typekit.net/af/491586/00000000000000003b9b1e2d/27/d?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=n3&v=3") format("woff"),url("https://use.typekit.net/af/491586/00000000000000003b9b1e2d/27/a?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=n3&v=3") format("opentype");font-display:auto;font-style:normal;font-weight:300;font-stretch:normal}@font-face{font-family:"museo-sans-rounded";src:url("https://use.typekit.net/af/9baf4a/00000000000000003b9b1e2f/27/l?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=n7&v=3") format("woff2"),url("https://use.typekit.net/af/9baf4a/00000000000000003b9b1e2f/27/d?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=n7&v=3") format("woff"),url("https://use.typekit.net/af/9baf4a/00000000000000003b9b1e2f/27/a?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=n7&v=3") format("opentype");font-display:auto;font-style:normal;font-weight:700;font-stretch:normal}@font-face{font-family:"museo-sans-rounded";src:url("https://use.typekit.net/af/0e95d9/00000000000000003b9b1e34/27/l?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=i3&v=3") format("woff2"),url("https://use.typekit.net/af/0e95d9/00000000000000003b9b1e34/27/d?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=i3&v=3") format("woff"),url("https://use.typekit.net/af/0e95d9/00000000000000003b9b1e34/27/a?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=i3&v=3") format("opentype");font-display:auto;font-style:italic;font-weight:300;font-stretch:normal}@font-face{font-family:"museo-sans-rounded";src:url("https://use.typekit.net/af/837b59/00000000000000003b9b1e36/27/l?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=i7&v=3") format("woff2"),url("https://use.typekit.net/af/837b59/00000000000000003b9b1e36/27/d?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=i7&v=3") format("woff"),url("https://use.typekit.net/af/837b59/00000000000000003b9b1e36/27/a?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=i7&v=3") format("opentype");font-display:auto;font-style:italic;font-weight:700;font-stretch:normal}@font-face{font-family:"museo-sans-condensed";src:url("https://use.typekit.net/af/da6ab2/000000000000000000012ca6/27/l?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=n3&v=3") format("woff2"),url("https://use.typekit.net/af/da6ab2/000000000000000000012ca6/27/d?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=n3&v=3") format("woff"),url("https://use.typekit.net/af/da6ab2/000000000000000000012ca6/27/a?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=n3&v=3") format("opentype");font-display:auto;font-style:normal;font-weight:300;font-stretch:normal}@font-face{font-family:"museo-sans-condensed";src:url("https://use.typekit.net/af/f58f65/000000000000000000012ca7/27/l?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=i3&v=3") format("woff2"),url("https://use.typekit.net/af/f58f65/000000000000000000012ca7/27/d?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=i3&v=3") format("woff"),url("https://use.typekit.net/af/f58f65/000000000000000000012ca7/27/a?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=i3&v=3") format("opentype");font-display:auto;font-style:italic;font-weight:300;font-stretch:normal}@font-face{font-family:"museo-sans-condensed";src:url("https://use.typekit.net/af/592eea/000000000000000000012caa/27/l?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=n7&v=3") format("woff2"),url("https://use.typekit.net/af/592eea/000000000000000000012caa/27/d?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=n7&v=3") format("woff"),url("https://use.typekit.net/af/592eea/000000000000000000012caa/27/a?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=n7&v=3") format("opentype");font-display:auto;font-style:normal;font-weight:700;font-stretch:normal}@font-face{font-family:"museo-sans-condensed";src:url("https://use.typekit.net/af/9c0805/000000000000000000012cab/27/l?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=i7&v=3") format("woff2"),url("https://use.typekit.net/af/9c0805/000000000000000000012cab/27/d?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=i7&v=3") format("woff"),url("https://use.typekit.net/af/9c0805/000000000000000000012cab/27/a?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=i7&v=3") format("opentype");font-display:auto;font-style:italic;font-weight:700;font-stretch:normal}@font-face{font-family:"museo-sans-display";src:url("https://use.typekit.net/af/2f6e0d/00000000000000003b9ad11f/27/l?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=n4&v=3") format("woff2"),url("https://use.typekit.net/af/2f6e0d/00000000000000003b9ad11f/27/d?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=n4&v=3") format("woff"),url("https://use.typekit.net/af/2f6e0d/00000000000000003b9ad11f/27/a?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=n4&v=3") format("opentype");font-display:auto;font-style:normal;font-weight:400;font-stretch:normal}@font-face{font-family:"museo-sans-display";src:url("https://use.typekit.net/af/b4d456/00000000000000003b9ad11e/27/l?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=n8&v=3") format("woff2"),url("https://use.typekit.net/af/b4d456/00000000000000003b9ad11e/27/d?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=n8&v=3") format("woff"),url("https://use.typekit.net/af/b4d456/00000000000000003b9ad11e/27/a?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=n8&v=3") format("opentype");font-display:auto;font-style:normal;font-weight:800;font-stretch:normal}.tk-museo-sans{font-family:"museo-sans",sans-serif}.tk-museo-sans-rounded{font-family:"museo-sans-rounded",sans-serif}.tk-museo-sans-condensed{font-family:"museo-sans-condensed",sans-serif}.tk-museo-sans-display{font-family:"museo-sans-display",sans-serif}</style><style data-emotion="css b62m3t-container" data-s="">.css-b62m3t-container{position:relative;box-sizing:border-box;}</style><style data-emotion="css 7pg0cj-a11yText" data-s="">.css-7pg0cj-a11yText{z-index:9999;border:0;clip:rect(1px, 1px, 1px, 1px);height:1px;width:1px;position:absolute;overflow:hidden;padding:0;white-space:nowrap;}</style><style data-emotion="css mif058-control" data-s="">.css-mif058-control{-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;cursor:default;display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-box-flex-wrap:wrap;-webkit-flex-wrap:wrap;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-box-pack:justify;-webkit-justify-content:space-between;justify-content:space-between;min-height:38px;outline:0!important;position:relative;-webkit-transition:all 100ms;transition:all 100ms;background-color:hsl(0, 0%, 100%);border-color:hsl(0, 0%, 80%);border-radius:0.25rem;border-style:solid;border-width:1px;box-sizing:border-box;}.css-mif058-control:hover{border-color:hsl(0, 0%, 70%);}</style><style data-emotion="css hlgwow" data-s="">.css-hlgwow{-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;display:grid;-webkit-flex:1;-ms-flex:1;flex:1;-webkit-box-flex-wrap:wrap;-webkit-flex-wrap:wrap;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-overflow-scrolling:touch;position:relative;overflow:hidden;padding:2px 8px;box-sizing:border-box;}</style><style data-emotion="css 1dimb5e-singleValue" data-s="">.css-1dimb5e-singleValue{grid-area:1/1/2/3;max-width:100%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:hsl(0, 0%, 20%);margin-left:2px;margin-right:2px;box-sizing:border-box;}</style><style data-emotion="css 1hac4vs-dummyInput" data-s="">.css-1hac4vs-dummyInput{background:0;border:0;caret-color:transparent;font-size:inherit;grid-area:1/1/2/3;outline:0;padding:0;width:1px;color:transparent;left:-100px;opacity:0;position:relative;-webkit-transform:scale(.01);-moz-transform:scale(.01);-ms-transform:scale(.01);transform:scale(.01);}</style><style data-emotion="css 1wy0on6" data-s="">.css-1wy0on6{-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-align-self:stretch;-ms-flex-item-align:stretch;align-self:stretch;display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-flex-shrink:0;-ms-flex-negative:0;flex-shrink:0;box-sizing:border-box;}</style><script src="https://alps.cdn.nintendo.net/v1/js/account_en_USA.js"></script><script defer="" data-domain-script="3cfa2a0c-9887-4f14-a162-a37b68418a76" data-document-language="true" src="https://cdn.cookielaw.org/scripttemplates/otSDKStub.js"></script><link as="script" rel="prefetch" href="/_next/static/chunks/8725-e4c6b8bcfed30846.js"><link as="script" rel="prefetch" href="/_next/static/chunks/pages/store/games/%5Bslug%5D-532980ea1f7830eb.js"><style type="text/css"></style><script src="https://assets.adobedtm.com/extensions/EPbf7b42aa08bc4f10879b1484195e80d1/AppMeasurement.min.js" async=""></script><script src="https://assets.adobedtm.com/extensions/EPbf7b42aa08bc4f10879b1484195e80d1/AppMeasurement_Module_ActivityMap.min.js" async=""></script><script type="text/javascript" async="" src="https://cdn.accounts.nintendo.com/jssdk/nintendo-jssdk-client.3.0.2.js"></script><script src="https://assets.adobedtm.com/0216612597a6/b80235efd36c/3218b9f3ee23/RC22e3862854544e04a7aaf340fd074e50-source.min.js" async=""></script><script src="https://cdn.cookielaw.org/scripttemplates/6.35.0/otBannerSdk.js" async="" type="text/javascript"></script><script async="" src="https://www.googletagmanager.com/gtm.js?id=GTM-WS6V89B"></script><script async="" src="https://www.googletagmanager.com/gtm.js?id=GTM-57PNCMD"></script><style id="onetrust-style">#onetrust-banner-sdk{-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}#onetrust-banner-sdk .onetrust-vendors-list-handler{cursor:pointer;color:#1f96db;font-size:inherit;font-weight:bold;text-decoration:none;margin-left:5px}#onetrust-banner-sdk .onetrust-vendors-list-handler:hover{color:#1f96db}#onetrust-ba

In [ ]:
df.timestamp = pd.to_datetime(df.timestamp, unit = 's', origin = 'unix')

In [ ]:
df = df[df['stress_level_value'].notna()]

In [ ]:
pd.to_datetime(df.timestamp.dt.date)

2       2003-02-14
3       2003-02-14
4       2003-02-14
5       2003-02-14
6       2003-02-14
           ...
74686   2003-03-16
74689   2003-03-16
74690   2003-03-16
74692   2003-03-16
74694   2003-03-16
Name: timestamp, Length: 41579, dtype: datetime64[ns]

In [ ]:
df.timestamp + pd.Timedelta(hours = 8)

2       2003-02-15 02:57:00
3       2003-02-15 02:58:00
4       2003-02-15 02:59:00
5       2003-02-15 03:00:00
6       2003-02-15 03:01:00
                ...
74686   2003-03-16 12:56:00
74689   2003-03-16 12:57:00
74690   2003-03-16 12:58:00
74692   2003-03-16 12:59:00
74694   2003-03-16 13:00:00
Name: timestamp, Length: 41579, dtype: datetime64[ns]

In [ ]:
df[(df.timestamp + pd.Timedelta(hours = 8)).dt.date == pd.Timestamp(year = 2003, month = 3, day = 16)].stress_level_value.mean()

/Users/valen/.pyenv/versions/3.8.13/envs/lewagon/lib/python3.8/site-packages/pandas/core/ops/array_ops.py:73: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior.  In a future version these will be considered non-comparable.Use 'ts == pd.Timestamp(date)' or 'ts.date() == date' instead.
  result = libops.scalar_compare(x.ravel(), y, op)

13.545985401459854

In [ ]:
!ls

In [ ]:
import pandas as pd
import numpy as np
import json
pd.set_option('display.max_columns', None)

In [ ]:
with open('exports/garmin_exports/garmin_export_18042023/DI_CONNECT/DI-Connect-Fitness/valentin.herinckx@gmail.com_0_summarizedActivities.json', 'r') as f:
    # Load the JSON data from the file
    data = json.load(f)
list_dict = data[0]['summarizedActivitiesExport']
overall_df = pd.DataFrame(list_dict) 
overall_df['beginTimestamp'] = pd.to_datetime(overall_df['beginTimestamp'], unit = 'ms')
overall_df['startTimeLocal'] = pd.to_datetime(overall_df['startTimeLocal'], unit = 'ms')
overall_df['startTimeGmt'] = pd.to_datetime(overall_df['startTimeGmt'], unit = 'ms')
overall_df['duration'] = overall_df['duration']/1000/60
overall_df['elapsedDuration'] = overall_df['elapsedDuration']/1000/60
overall_df['movingDuration'] = overall_df['movingDuration']/1000/60
overall_df['distance'] = overall_df['distance']/100000
overall_df.avgSpeed = overall_df.avgSpeed*38.323573596590734
overall_df.maxSpeed = overall_df.maxSpeed*38.323573596590734
overall_df.maxVerticalSpeed = overall_df.maxVerticalSpeed*38.323573596590734
overall_df['TimeDiffGMT'] = (overall_df['startTimeLocal'] - overall_df['startTimeGmt'])

In [ ]:
activity_splits_full = pd.DataFrame()
for index_activity, row in overall_df.iterrows():
    if row['activityType'] != 'running':
        continue
    activity_splits = pd.DataFrame(row['splits'])
    splits_measurements = pd.DataFrame()
    for index_split, row in activity_splits.iterrows():
        dict_measurements = {}
        dict_measurements['startTimeGMT'] = row['startTimeGMT']
        split_measurements = pd.json_normalize(row.measurements)
        for index_measurement, row in split_measurements.iterrows():
            dict_measurements[f"{row['fieldEnum']}__{row['unitEnum']}"] = row['value']
        split_measurements = pd.DataFrame(dict_measurements, index = [0])
        splits_measurements = pd.concat([splits_measurements, split_measurements], ignore_index=True)
    activity_splits = pd.merge(activity_splits, splits_measurements, on = 'startTimeGMT')
    activity_splits_full = pd.concat([activity_splits_full, activity_splits], ignore_index=True)

In [ ]:
overall_df

,activityId,uuidMsb,uuidLsb,name,activityType,userProfileId,timeZoneId,beginTimestamp,eventTypeId,rule,sportType,workoutId,startTimeGmt,startTimeLocal,duration,distance,elevationGain,elevationLoss,avgSpeed,maxSpeed,avgHr,maxHr,maxRunCadence,steps,calories,bmrCalories,startLongitude,startLatitude,aerobicTrainingEffect,avgStrideLength,avgFractionalCadence,maxFractionalCadence,vO2MaxValue,elapsedDuration,movingDuration,anaerobicTrainingEffect,deviceId,minElevation,maxElevation,avgDoubleCadence,maxDoubleCadence,locationName,summarizedDiveInfo,maxVerticalSpeed,manufacturer,lapCount,endLongitude,endLatitude,waterEstimated,aerobicTrainingEffectMessage,anaerobicTrainingEffectMessage,splitSummaries,splits,moderateIntensityMinutes,vigorousIntensityMinutes,decoDive,purposeful,autoCalcCalories,favorite,pr,elevationCorrected,atpActivity,parent,summarizedExerciseSets,activeSets,totalSets,totalReps,TimeDiffGMT
0,10912980115,4883298787290138077,-6737311715370000477,Zhongzheng District - Long Easy Run,running,111380931,135,2023-04-16 01:25:45,9,private,RUNNING,649836322.0,2023-04-16 01:25:45,2023-04-16 09:25:45,90.139966,16.701561,18186.252451,17608.373213,11.834320,17.950762,159.0,182.0,90.0,13782.0,5602.05674,582.41278,121.530939,25.035357,4.2,120.818373,0.695312,0.0,55.0,96.845052,89.857751,0.6,3414950965,-219.142032,3340.000153,153.390625,180.0,Zhongzheng District,{},33.438618,GARMIN,20,121.534173,25.013871,541.0,HIGHLY_IMPROVING_LACTATE_THRESHOLD_13,NO_ANAEROBIC_BENEFIT_0,"[{'noOfSplits': 4, 'totalAscent': 0.0, 'durati...","[{'startTimeSource': 0, 'endTimeSource': 0, 's...",1.0,95.0,False,False,False,False,False,True,True,False,NaN,NaN,NaN,NaN,0 days 08:00:00
1,10901880232,1672212473206555932,-8268351561288318437,Zhongzheng District - Speed Repeats,running,111380931,135,2023-04-14 10:01:38,9,private,RUNNING,646886518.0,2023-04-14 10:01:38,2023-04-14 18:01:38,51.000000,9.866790,16192.913871,15870.759922,12.355520,21.419046,155.0,191.0,97.0,7818.0,3083.85472,331.01158,121.531597,25.035366,3.8,124.458381,0.234375,0.0,55.0,56.295984,50.887700,3.1,3414950965,-59.050137,2479.999924,154.468750,194.0,Zhongzheng District,{},12.515364,GARMIN,30,121.532964,25.033669,306.0,IMPROVING_AEROBIC_FITNESS_2,IMPROVING_ANAEROBIC_CAPACITY_AND_POWER_8,"[{'noOfSplits': 3, 'totalAscent': 0.0, 'durati...","[{'startTimeSource': 0, 'endTimeSource': 0, 's...",2.0,53.0,False,False,False,False,False,True,True,False,NaN,NaN,NaN,NaN,0 days 08:00:00
2,10896120337,-7569323454354929659,-6595104910723282765,Zhongzheng District - Progression Run,running,111380931,135,2023-04-13 09:59:47,9,private,RUNNING,646348932.0,2023-04-13 09:59:47,2023-04-13 17:59:47,40.000000,8.263020,12562.614274,12410.704255,13.194807,17.594353,159.0,189.0,95.0,6182.0,2589.43236,259.78124,121.531603,25.035238,3.7,133.496429,0.218750,0.5,55.0,40.321468,39.982367,0.5,3414950965,25.204816,3218.029785,154.437500,191.0,Zhongzheng District,{},3.919847,GARMIN,9,121.531667,25.035338,239.0,IMPACTING_TEMPO_22,NO_ANAEROBIC_BENEFIT_0,"[{'noOfSplits': 2, 'totalAscent': 281.38999998...","[{'startTimeSource': 0, 'endTimeSource': 0, 's...",1.0,39.0,False,False,False,False,False,True,True,False,NaN,NaN,NaN,NaN,0 days 08:00:00
3,10844399403,2567535457307279478,-7984992466330274051,Zhongzheng District - Easy Run,running,111380931,135,2023-04-06 00:48:56,9,private,RUNNING,643347595.0,2023-04-06 00:48:56,2023-04-06 08:48:56,45.000000,8.295730,8615.626287,8953.949594,11.773002,15.984763,136.0,151.0,81.0,6982.0,2421.83156,289.11138,121.531330,25.035103,2.7,119.180405,0.335938,0.5,55.0,47.788668,44.553933,0.0,3414950965,-138.754940,3478.388214,154.671875,163.0,Zhongzheng District,{},25.076559,GARMIN,9,121.533813,25.030968,457.0,MAINTAINING_AEROBIC_BASE_7,NO_ANAEROBIC_BENEFIT_0,"[{'noOfSplits': 3, 'totalAscent': 0.0, 'durati...","[{'startTimeSource': 0, 'endTimeSource': 0, 's...",1.0,46.0,False,False,False,False,False,True,True,False,NaN,NaN,NaN,NaN,0 days 08:00:00
4,10837637029,-8384625523103939094,-7139950231823234873,Zhongzheng District - Speed Repeats,running,111380931,135,2023-04-05 00:13:25,9,private,RUNNING,642360482.0,2023-04-05 00:13:25,2023-04-05 08:13:25,63.000000,12.248120,18538.253473,18034.813665,12.416838,22.457615,160.0,188.0,99.0,9616.0,3930.23876,406.43194,121.531733,25.035254,4.0,126.703125,0.312500,0.0,55.0,70.260352,62.807934,2.4,3414950965,-73.573995,2760.000038,152.625000,198.0,Zhongzheng District,{},13.841727,GARMIN,27,121.532627,25.033551,378.0,HIGHLY_IMPROVING_VO2_MAX_16,MAINTAINING_ANAEROBIC_BASE_1,"[{'noOfSplits': 7, 'totalAscent': 17.239999994...","[{'startTimeSource': 0, 'endTimeSource': 0, 's...",4.0,63.0,False,False,False,False,False,True,True,False,NaN,NaN,NaN,NaN,0 days 08:00:00
5,10830411023,-3447507775214763478,-7226711259797033760,Zhongzheng District - Easy Run,running,111380931,135,2023-04-04 00:47:19,9,private,RUNNING,641855297.0,2023-04-04 00:47:19,2023-04-04 08:47:19,45.000000,8.578080,13912.724876,14016.225529,12.175400,13.980440,148.0,165.0,81.0,6916.0,2664.85272,289.11138,121.531486,25.035301,3.2,123.610288,0.101562,0.5,55.0,45.202051,44.589017,0.0,3414950965,376.099038,3352.013016,154.203125,163.0,Zhongzheng District,{},6.657326,GARMIN,9,121.534674,25.033066,270.0,IMPROVING_AEROBIC_BASE_8,NO_ANAEROBIC_BENEFIT_0,"[{'noOfSplits': 2, 'totalAscent': 0.0, 'durati...","[{'startTimeSource': 0, 'endTimeSource': 0, 's...",1.0,43.0,False,False,False,False,False,True,True,False,NaN,NaN,NaN,NaN,0 days 08:00:00
6,10816625472,9172667109249011456,-8160319888217740725,Daan District - Long Easy Run,running,111380931,135,2023-04-02 02:00:29,9,private,RUNNING,639936051.0,2023-04-02 02:00:29,2023-04-02 10:00:29,105.000000,20.246289,16535.067618,16866.292822,12.317197,18.487291,156.0,179.0,91.0,16212.0,6549.00126,674.59322,121.534115,25.033458,4.4,124.510271,0.429688,0.5,55.0,109.847347,104.905684,0.2,3414950965,34.370410,2188.247681,154.859375,183.0,Daan District,{},12.438263,GARMIN,21,121.533335,25.032403,630.0,HIGHLY_IMPROVING_LACTATE_THRESHOLD_13,NO_ANAEROBIC_BENEFIT_0,"[{'noOfSplits': 3, 'totalAscent': 527.10999999...","[{'startTimeSource': 0, 'endTimeSource': 0, 's...",1.0,106.0,False,False,False,False,False,True,True,False,NaN,NaN,NaN,NaN,0 days 08:00:00
7,10804291886,1094363680494407679,-8277852232370166801,Daan District - Stride Repeats,running,111380931,135,2023-03-31 02:03:12,9,private,RUNNING,639425952.0,2023-03-31 02:03:12,2023-03-31 10:03:12,30.927616,5.894100,9766.584811,9371.702132,12.171567,22.277494,146.0,176.0,101.0,4762.0,1747.23834,201.12096,121.534202,25.033449,3.0,124.919737,0.351562,0.0,54.0,30.980933,30.919966,1.6,3414950965,-86.049134,3759.999847,154.703125,202.0,Daan District,{},8.558931,GARMIN,26,121.533232,25.032517,185.0,IMPROVING_AEROBIC_BASE_8,MINOR_ANAEROBIC_BENEFIT_15,"[{'noOfSplits': 1, 'totalAscent': 140.25, 'dur...","[{'startTimeSource': 0, 'endTimeSource': 0, 's...",1.0,29.0,False,False,False,False,False,True,True,False,NaN,NaN,NaN,NaN,0 days 08:00:00
8,10804290998,4396787922700159346,-6014413281878815125,Strength,strength_training,111380931,135,2023-03-30 03:08:53,9,private,FITNESS_EQUIPMENT,NaN,2023-03-30 03:08:53,2023-03-30 11:08:53,3.051300,0.000000,NaN,NaN,0.000000,NaN,104.0,119.0,NaN,450.0,96.37046,20.95010,NaN,NaN,0.1,NaN,0.000000,0.0,NaN,3.051300,2.569200,0.0,3414950965,NaN,NaN,NaN,NaN,NaN,{},NaN,GARMIN,1,NaN,NaN,18.0,NO_AEROBIC_BENEFIT_18,NO_ANAEROBIC_BENEFIT_0,NaN,NaN,1.0,1.0,False,False,False,False,False,False,False,False,"[{'category': 'CARDIO', 'subCategory': 'JUMP_R...",2.0,2.0,225.0,0 days 08:00:00
9,10791045417,4535104612168385533,-4676671043763422769,Daan District - Goal Pace Run,running,111380931,135,2023-03-29 01:53:13,9,private,RUNNING,638951620.0,2023-03-29 01:53:13,2023-03-29 09:53:13,50.000000,9.793620,18575.522541,18248.305820,12.512647,17.770641,152.0,181.0,87.0,7714.0,2979.10422,322.63154,121.533094,25.033465,3.8,126.662685,0.234375,0.0,54.0,54.163835,49.923000,1.0,3414950965,-78.189468,4020.000076,154.468750,174.0,Daan District,{},48.287704,GARMIN,12,121.532987,25.033319,300.0,IMPROVING_VO2_MAX_15,MINOR_ANAEROBIC_BENEFIT_15,"[{'noOfSplits': 3, 'totalAscent': 220.40000000...","[{'startTimeSource': 0, 'endTimeSource': 0, 's...",2.0,50.0,False,False,False,False,False,True,True,False,NaN,NaN,NaN,NaN,0 days 08:00:00
10,10784420039,-6328771863506566832,-6063088232789366653,Zhongzheng District - Easy Run,running,111380931,135,2023-03-28 02:30:41,9,private,RUNNING,637939972.0,2023-03-28 02:30:41,2023-03-28 10:30:41,45.000000,8.455370,10569.226599,9403.194952,12.002943,18.560106,137.0,171.0,94.0,6902.0,2480.49184,289.11138,121.531216,25.035198,3.0,121.968986,0.015625,0.0,54.0,46.276217,44.897650,0.6,3414950965,482.720375,3740.000153,154.031250,188.0,Zhongzheng District,{},28.480164,GARMIN,9,121.532207,25.035484,269.0,IMPROVING_AEROBIC_BASE_8,NO_ANAEROBIC_BENEFIT_0,"[{'noOfSplits': 3, 'totalAscent': 298.33000001...","[{'startTimeSource': 0, 'endTimeSource': 0, 's...",1.0,44.0,False,False,False,False,False,True,True,False,NaN,NaN,NaN,NaN,0 days 08:00:00
11,10763830142,-7460754655367970595,-7946460547636296182,Zhongzheng District - Long Easy Run,running,111380931,135,2023-03-25 02:37:31,9,private,RUNNING,636627320.0,2023-03-25 02:37:31,2023-03-25 10:37:31,100.000000,19.018061,24133.339328,23315.999813,12.148573,15.984763,159.0,179.0,114.0,15410.0,6138.37930,645.26308,121.531181,25.035590,4.5,123.184610,0.179688,0.5,54.0,105.396118,99.768900,0.0,3414950965,-220.559859,6279.999924,154.359375,229.0,Zhongzheng District,{},59.339892,GARMIN,21,121.532697,25.033493,600.0,HIGHLY_IMPACTING_TEMPO_23,NO_ANAEROBIC_BENEFIT_0,"[{'noOfSplits': 4, 'totalAscent': 0.0, 'durati...","[{'startTimeSource': 0, 'endTimeSource': 0, 's...",1.0,103.0,False,False,False,False,True,True,True,False,NaN,NaN,NaN,NaN,0 days 08:00:00
12,10757635050,3515095290923798516,-5376400411961141846,Daan District - Progression Run,running,111380931,135,2023-03-24 00:49:28,9,private,RUNNING,635626407.0,2023-03-24 00:49:28,2023-03-24 08:49:28,40.000000,8.269350,8829.347920,8902.691007,13.206304,17.877947,154.0,187.0,83.0,6152.0,2484.68186,259.78124,121.532543,25.033436,3.7,133.972203,0.007812,0.5,54.0,42.919434,39.933250,0.0,3414950965,-91.871262,2465.815544,154.015625,167.0,Daan District,{},4.952677,GARMIN,9,121.536557,25.021606,239.0,IMPROVING_VO2_MAX_15,NO_ANAEROBIC_BENEFIT_0,"[{'noOfSplits': 3, 'totalAscent': 0.0, 'durati...","[{'startTimeSource': 0, 'endTimeSource': 0, 's...",1.0,41.0,False,False,False,False,False,True,True,False,NaN,NaN,NaN,NaN,0 days 08:00:00
13,10751022212,2350852557342786002,-5263552137952687986,Zhongzheng District - Speed Repeats,running,111380931,135,2023-03-23 00:23:55,9,private,RUNNING,634696464.0,2023-03-23 00:23:55,2023-03-23 08:23:55,51.000000,9.421290,32933.540174,33458.803007,11.799828,23.063127,165.0,194.0,93.0,7704.0,3213.74534,331.01158,121.532722,25.034704,4.2,120.558729,0.226562,0.0,54.0,52.474898,50.861667,3.0,3414950965,-75.617951,11780.000305,152.453125,186.0,Zhongzheng District,{},57.594155,GARMIN,30,121.531991,25.035073,306.0,HIGHLY_IMPROVING_LACTATE_THRESHOLD_13,IMPROVING_ANAEROBIC_CAPACITY_AND_POWER_8,"[{'noOfSplits': 5, 'totalAscent': 284.38999998...","[{'startTimeSource': 0, 'endTimeSource': 0, 's...",1.0,51.0,False,False,False,False,False,True,True,False,NaN,NaN,NaN,NaN,0 days 08:00:00
14,10737095353,8229434637929368078,-5877611543925122498,Daan District - Easy Run,running,111380931,135,2023-03-21 01:37:41,9,private,RUNNING,634696463.0,2023-03-21 01:37:41,2023-03-21 09:37:41,45.000000,8.609580,6684.165382,6817.299271,12.221387,14.409664,154.0,173.0,81.0,6860.0,2769.60322,289.11138,121.533588,25.033647,3.6,124.653439,0.726562,0.0,54.0,45.432349,44.902500,0.0,3414950965,-88.251287,2555.218887,153.453125,162.0,Daan District,{},6.722358,GARMIN,9,121.532555,25.033435,270.0,IMPROVING_AEROBIC_ENDURANCE_9,NO_ANAEROBIC_BENEFIT_0,"[{'noOfSplits': 2, 'totalAscent': 216.80000001...","[{'startTimeSource': 0, 'endTimeSource': 0, 's...",0.0,45.0,False,False,False,False,False,True,True,False,NaN,NaN,NaN,NaN,0 days 08:00:00
15,10724024979,7561482508265932559,-6920448109473870155,Zhongzheng District - Long Easy Run,running,111380931,135,2023-03-19 06:05:20,9,private,RUNNING,634696462.0,2023-03-19 06:05:20,2023-03-19 14:05:20,89.999984,16.775750,19691.170311,19519.943810,11.907135,17.521538,159.0,176.0,96.0,13704.0,5451.21602,578.22276,121.522213,25.020511,4.5,121.967470,0.414062,0.5,54.0,99.254549,89.506517,0.5,3414950965,-1800.000000,3540.000153,152.828125,193.0,Zhongzheng District,{},34.848961,GARMIN,18,121.534795,25.033470,960.0,HIGHLY_IMPACTING_TEMPO_23,NO_ANAEROBIC_BENEFIT_0,"[{'noOfSplits': 6, 'totalAscent': 39.370000004...","[{'startTimeSource': 0, 'endTimeSource': 0, 's...",0.0,98.0,False,False,False,False,False,True,True,False,NaN,NaN,NaN,NaN,0 days 08:00:00
16,10710499909,-3086125114758181752,-7733305899931916578,Daan District - Stride Repeats,running,111380931,135,2023-03-17 02:40:21,9,private,RUNNING,634696461.0,2023-03-17 02:40:21,2023-03-17 10:40:21,28.793451,5.509430,8113.996160,7856.129110,12.221387,21.131618,158.0,187.0,95.0,4396.0,1831.03874,184.36088,121.533103,25.033524,3.5,122.917445,0.546875,0.0,54.0,28.823649,28.738217,2.4,3414950965,-30.556607,2800.000000,155.093750,190.0,Daan District,{},20.311495,GARMIN,23,121.531240,25.033701,172.0,IMPACTING_TEMPO_22,MAINTAINING_ANAEROBIC_POWER_7,"[{'noOfSplits': 1, 'totalAscent': 172.72000002...","[{'startTimeSource': 0, 'endTimeSource': 0, 's...",1.0,27.0,False,False,False,False,False,True,True,False,NaN,NaN,NaN,NaN,0 days 08:00:00
17,10697240895,7328791503502065771,-5884681379185256259,Strength,strength_training,111380931,135,2023-03-15 03:32:29,9,private,FITNESS_EQUIPMENT,NaN,2023-03-15 03:32:29,2023-03-15 11:32:29,17.358217,0.000000,NaN,NaN,0.000000,NaN,113.0,140.0,NaN,534.0,590.79282,113.13054,NaN,NaN,0.6,NaN,0.000000,0.0,NaN,39.404317,8.293500,0.0,3414950965,NaN,NaN,NaN,NaN,NaN,{},NaN,GARMIN,1,NaN,NaN,104.0,NO_AEROBIC_BENEFIT_18,NO_ANAEROBIC_BENEFIT_0,NaN,NaN,11.0,9.0,False,False,False,False,False,False,False,False,"[{'category': 'CARDIO', 'subCategory': 'JUMP_R...",11.0,11.0,267.0,0 days 08:00:00
18,10697240681,-1187757329631589682,-6960039618805351274,Daan District - Benchmark Run,running,111380931,135,2023-03-15 03:16:44,9,private,RUNNING,634658586.0,2023-03-15 03:16:44,2023-03-15 11:16:44,9.023300,1.944680,2046.177959,1829.973507,13.765828,18.272680,157.0,180.0,84.0,1402.0,578.22276,58.66028,121.533092,25.033450,2.4,137.469061,0.914062,0.5,54.0,9.137450,9.006367,1.0,3414950965,-113.734186,2052.861023,155.828125,169.0,Daan District,{},3.577396,GARMIN,5,121.532217,25.033691,54.0,MAINTAINING_TEMPO_21,MINOR_ANAEROBIC_BENEFIT_15,"[{'noOfSplits': 2, 'totalAscent': 42.759999990...","[{'startTimeSource': 0, 'endTimeSource': 0, 's...",0.0,8.0,False,False,False,False,False,True,True,False,NaN,NaN,NaN,NaN,0 days 08:00:00
19,10696851700,7085883426564033218,-4736282332971964605,Zhongzheng District Running,running,111380931,135,2023-03-14 01:07:03,9,private,RUNNING,NaN,2023-03-14 01:07:03,2023-03-14 09:07:03,34.752515,7.324380,7365.587234,8302.445221,13.463071,18.058067,162.0,183.0,95.0,5374.0,2287.75092,226.26108,121.532416,25.034009,3.8,137.927287,0.367188,0.0,54.0,40.697701,34.277033,1.9,3414950965,201.646805,4679.999924,152.734375,190.0,Zhongzheng District,{},22.533638,GARMIN,8,121.531389,25.035340,208.0,IMPROVING_VO2_MAX_15,MINOR_ANAEROBIC_BENEFIT_15,"[{'noOfSplits': 6, 'totalAscent': 0.0, 'durati...","[{'startTimeSource': 0, 'endTimeSource': 0, 's...",1.0,38.0,False,False,False,False,False,True,False,False,NaN,NaN,NaN,NaN,0 days 08:00:00
20,10670375557,-8701946093692828739,-6757509335751103600,Xindian District Running,running,111380931,135,2023-03-11 03:11:55,9,private,RUNNING,NaN,2023-03-11 03:11:55,2023-03-11 11:11:55,29.797650,6.152080,4708.279705,5609.977818,13.187142,15.804642,176.0,194.0,105.0,4562.0,2141.10022,192.74092,121.537436,24.952927,4.1,134.191587,0.921875,0.0,54.0,29.797650,29.701033,1.5,3414950965,439.612913,3137.065315,153.843750,210.0,Xindian District,{},3.394982,GARMIN,7,121.521795,24.974810,178.0,HIGHLY_IMPROVING_VO2_MAX_16,MINOR_ANAEROBIC_BENEFIT_15,"[{'noOfSplits': 1, 'totalAscent': 0.0, 'durati...","[{'startTimeSource': 0, 'endTimeSource': 0, 's...",1.0,28.0,False,False,False,False,False,True,False,False,NaN,NaN,NaN,NaN,0 days 08:00:00
21,10653958783,-2753341983508184970,-7322922330753105158,Xindian District Running,running,111380931,135,2023-03-08 10:04:37,9,private,RUNNING,NaN,2023-03-08 10:04:37,2023-03-08 18:04:37,21.902350,5.004750,4673.753691,6346.707582,14.593617,16.268357,169.0,183.0,112.0,3386.0,1562.87746,142.46068,121.537442,24.953294,3.7,147.600411,0.398438,0.0,54.0,22.914783,21.828067,1.1,3414950965,477.090645,3952.385330,154.796875,224.0,Xindian District,{},4.256711,GARMIN,6,121.525858,24.984394,131.0,IMPROVING_VO2_MAX_15,MINOR_ANAEROBIC_BENEFIT_15,"[{'noOfSplits': 1, 'totalAscent': 0.0, 'durati...","[{'startTimeSource': 0, 'endTimeSource': 0, 's...",1.0,21.0,False,False,False,False,False,True,False,False,NaN,NaN,NaN,NaN,0 days 08:00:00
22,10646106755,-8047500754870449360,-8620902089985196054,Sanmin District Cycling,cycling,111380931,135,2023-03-07 01:58:08,9,private,CYCLING,NaN,2023-03-07 01:58:08,2023-03-07 09:58:08,20.440700,3.669100,1754.818797,2204.106593,11.466414,21.848270,77.0,90.0,NaN,NaN,272.35130,134.08064,120.298680,22.642217,0.1,NaN,0.000000,0.0,NaN,26.077834,18.683333,0.0,3414950965,-46.708333,2296.348381,NaN,NaN,Sanmin District,{},6.359112,GARMIN,1,120.285741,22.620209,122.0,NO_AEROBIC_BENEFIT_18,NO_ANAEROBIC_BENEFIT_0,NaN,NaN,NaN,NaN,False,False,False,False,False,True,False,False,NaN,NaN,NaN,NaN,0 days 08:00:00
23,10640965212,6052668846072218622,-8453598580946613260,Yancheng District Cycling,cycling,111380931,135,2023-03-06 11:48:10,9,private,CYCLING,NaN,2023-03-06 11:48:10,2023-03-06 19:48:10,16.763333,2.509650,1475.062275,1442.049122,9.561731,17.487047,86.0,101.0,NaN,NaN,305.87146,108.94052,120.282668,22.627427,0.1,NaN,0.000000,0.0,NaN,21.012134,14.783333,0.0,3414950965,510.294533,2132.500267,NaN,NaN,Yancheng District,{},3.253196,GARMIN,1,120.296387,22.639604,100.0,NO_AEROBIC_BENEFIT_18,NO_ANAEROBIC_BENEFIT_0,NaN,NaN,4.0,0.0,False,False,False,False,False,True,False,False,NaN,NaN,NaN,NaN,0 days 08:00:00
24,10624824916,114110586334170246,-5721917058241511354,Xindian District Running,running,111380931,135,2023-03-04 04:23:47,9,private,RUNNING,NaN,2023-03-04 04:23:47,2023-03-04 12:23:47,28.489484,4.507150,3491.608191,5819.759607,10.105927,12.731091,126.0,142.0,79.0,4252.0,1412.03674,184.36088,121.513166,24.959681,2.2,105.204286,0.187500,0.0,NaN,47.708565,28.395383,0.0,3414950965,414.273071,3782.955170,150.375000,158.0,Xindian District,{},3.454991,GARMIN,5,121.525848,24.984488,170.0,MINOR_AEROBIC_BENEFIT_0,NO_ANAEROBIC_BENEFIT_0,"[{'noOfSplits': 4, 'totalAscent': 90.059999998...","[{'startTimeSource': 0, 'endTimeSource': 0, 's...",1.0,32.0,False,False,False,False,False,True,False,False,NaN,NaN,NaN,NaN,0 days 08:00:00
25,10568066307,-8792682431834271809,-6385978206384055418,Lasne Running,running,111380931,124,2023-02-23 10:59:30,9,private,RUNNING,NaN,2023-02-23 10:59:30,2023-02-23 11:59:30,23.472949,5.102580,6571.548462,6993.866730,13.884630,18.130882,157.0,184.0,86.0,3670.0,1604.77766,150.84072,4.459483,50.660815,3.3,138.897412,0.265625,0.0,54.0,23.472949,23.208883,0.3,3414950965,7922.825623,13723.681641,156.531250,172.0,Lasne,{},2.052746,GARMIN,6,4.459600,50.660826,140.0,IMPACTING_TEMPO_22,NO_ANAEROBIC_BENEFIT_0,"[{'noOfSplits': 1, 'totalAscent': 0.0, 'durati...","[{'startTimeSource': 0, 'endTimeSource': 0, 's...",1.0,21.0,False,False,False,False,False,True,False,False,NaN,NaN,NaN,NaN,0 days 01:00:00

In [ ]:
activity_splits_full

,startTimeSource,endTimeSource,startTimeGMT,endTimeGMT,startLatitude,startLongitude,messageIndex,type,startIndex,endIndex,totalExerciseReps,measurements,lapIndexes,SUM_ENERGY__KILOJOULE,WEIGHTED_MEAN_RUNCADENCE__BPM,SUM_ELAPSEDDURATION__MILLISECOND,MAX_SPEED__CENTIMETERS_PER_MILLISECOND,MAX_DOUBLE_CADENCE__BPM,WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND,SUM_DISTANCE__CENTIMETER,WEIGHTED_MEAN_HEARTRATE__BPM,SUM_DURATION__MILLISECOND,WEIGHTED_MEAN_DOUBLE_CADENCE__BPM,SUM_BMR_ENERGY__KILOJOULE,LOSS_ELEVATION__CENTIMETER,MAX_RUNCADENCE__BPM,WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND,MAX_HEARTRATE__BPM,GAIN_ELEVATION__CENTIMETER,WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER,WEIGHTED_MEAN_ELAPSED_DURATION_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND,SUM_MOVINGDURATION__MILLISECOND,WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND,END_TIMESTAMP__GMT,GAIN_CORRECTED_ELEVATION__CENTIMETER,GAIN_UNCORRECTED_ELEVATION__CENTIMETER,LOSS_CORRECTED_ELEVATION__CENTIMETER,LOSS_UNCORRECTED_ELEVATION__CENTIMETER,END_LATITUDE__DECIMAL_DEGREE,END_LONGITUDE__DECIMAL_DEGREE,MAX_ELEVATION__CENTIMETER,MAX_CORRECTED_ELEVATION__CENTIMETER,MAX_UNCORRECTED_ELEVATION__CENTIMETER,MAX_FRACTIONAL_CADENCE__BPM,MAX_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND,MIN_ELEVATION__CENTIMETER,MIN_CORRECTED_ELEVATION__CENTIMETER,MIN_UNCORRECTED_ELEVATION__CENTIMETER,MIN_HEARTRATE__BPM,MIN_RUNCADENCE__BPM,MIN_SPEED__CENTIMETERS_PER_MILLISECOND,WEIGHTED_MEAN_FRACTIONAL_CADENCE__BPM,MIN_ACTIVITY_LAP_DURATION__MILLISECOND,SUM_STEP__STEP
0,0,0,1681608345000,1681608351000,25.035357,121.530939,0,18,0,3,0,"[{'field': {'id': 113, 'key': 'sumEnergy', 'co...",NaN,0.00000,23.0,7002.0,0.1754,159.0,0.20720,1451.0,76.0,7002.0,45.421875,0.00000,0.0,80.0,0.0000,76.0,0.0,273.735746,-0.011207,3000.0,0.483667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,0,1681608345000,1681608351000,25.035357,121.530939,0,18,0,3,0,"[{'field': {'id': 113, 'key': 'sumEnergy', 'co...",NaN,263.97126,73.0,403952.0,0.3546,160.0,0.31092,93276.0,128.0,300000.0,146.296875,NaN,1468.0,80.0,NaN,144.0,1138.0,127.516054,NaN,294000.0,0.317265,NaN,1138.0,15345.0,1468.0,716.0,25.029614,121.534176,2375.0,2375.0,760.0,0.0,0.113063,701.0,701.0,-9820.0,75.0,0.0,0.0,0.148438,300000.0,756.0
2,0,0,1681608345000,1681608645000,NaN,NaN,14,5,1,97,0,"[{'field': {'id': 121, 'key': 'endTimestamp', ...",[1],0.00000,23.0,7002.0,0.1754,159.0,0.20720,1451.0,76.0,7002.0,45.421875,0.00000,0.0,80.0,0.0000,76.0,0.0,273.735746,-0.011207,3000.0,0.483667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,0,1681608345000,1681608645000,NaN,NaN,14,5,1,97,0,"[{'field': {'id': 121, 'key': 'endTimestamp', ...",[1],263.97126,73.0,403952.0,0.3546,160.0,0.31092,93276.0,128.0,300000.0,146.296875,NaN,1468.0,80.0,NaN,144.0,1138.0,127.516054,NaN,294000.0,0.317265,NaN,1138.0,15345.0,1468.0,716.0,25.029614,121.534176,2375.0,2375.0,760.0,0.0,0.113063,701.0,701.0,-9820.0,75.0,0.0,0.0,0.148438,300000.0,756.0
4,0,0,1681608352000,1681608438000,25.035470,121.531074,1,17,4,40,0,"[{'field': {'id': 113, 'key': 'sumEnergy', 'co...",NaN,75.42036,78.0,105001.0,0.3546,159.0,0.32950,30687.0,120.0,93143.0,155.125000,8.38004,0.0,80.0,0.1116,142.0,10357.0,127.430583,0.005959,78000.0,0.393423,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
309,0,0,1676389151000,1676389151000,50.660711,4.459391,0,22,0,0,0,"[{'field': {'id': 111, 'key': 'weightedMeanRun...",NaN,0.00000,88.0,5000.0,0.0000,175.0,0.05780,289.0,59.0,5000.0,175.000000,0.00000,0.0,88.0,0.0000,59.0,0.0,19.817144,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
310,0,0,1676389152000,1676391525000,50.660734,4.459357,1,17,2,590,0,"[{'field': {'id': 111, 'key': 'weightedMeanRun...",NaN,2497.25192,78.0,2373000.0,0.4124,175.0,0.35230,836069.0,151.0,2373000.0,156.062500,255.59122,14906.0,88.0,0.0019,174.0,19412.0,135.455641,-0.000268,2367000.0,0.353219,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
311,0,0,1676391526000,1676391527000,50.661035,4.458446,2,22,591,591,0,"[{'field': {'id': 111, 'key': 'weightedMeanRun...",NaN,4.19002,0.0,2001.0,0.0317,0.0,0.45880,918.0,170.0,2001.0,0.000000,0.00000,0.0,0.0,0.0000,170.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
312,0,0,1676391528000,1676391528000,50.661017,4.458580,3,18,0,0,0,"[{'field': {'id': 111, 'key': 'weightedMeanRun...",NaN,0.00000,94.0,1000.0,0.3872,188.0,0.54000,540.0,170.0,1000.0,188.000000,0.00000,0.0,94.0,0.0000,170.0,0.0,172.340429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
313,0,0,1676391529000,1676391555000,50.661020,4.458640,4,17,592,601,0,"[{'field': {'id': 111, 'key': 'weightedMeanRun...",NaN,29.33014,83.0,34999.0,0.4199,188.0,0.30040,7902.0,175.0,26301.0,166.109375,4.19002,0.0,94.0,0.0185,179.0,430.0,108.523013,0.026330,26301.0,0.300445,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
for index, row in split_measurements.iterrows():
    
    dict_measurements[f"{row['fieldEnum']}__{row['unitEnum']}"] = row['value']
split_measurements_df = pd.DataFrame(dict_measurements, index = [index_split])
activity_splits = pd.merge(activity_splits, split_measurements_df,\
                                   left_index = True, right_index = True, how = "outer")
activity_splits

In [ ]:
activity_splits_full = pd.DataFrame()
for index, row in overall_df.iterrows():
    if row['activityType'] != 'running':
        continue
    activity_splits = pd.DataFrame(overall_df.loc[index].splits)
    dict_measurements = {}
    for index_split, row in activity_splits.iterrows():
        split_measurements = pd.json_normalize(activity_splits.loc[index_split].measurements)
        for index, row in split_measurements.iterrows():
            dict_measurements[f"{row['fieldEnum']}__{row['unitEnum']}"] = row['value']
        split_measurements_df = pd.DataFrame(dict_measurements, index = [index_split])
        activity_splits = pd.merge(activity_splits, split_measurements_df,\
                                   left_index = True, right_index = True, how = "outer")
        print(activity_splits)
    activity_splits_full = pd.concat([activity_splits_full, activity_splits])
activity_splits_full

    startTimeSource  endTimeSource   startTimeGMT     endTimeGMT  \
0                 0              0  1681608345000  1681608351000
1                 0              0  1681608352000  1681608438000
2                 0              0  1681608456000  1681608462000
3                 0              0  1681608463000  1681608586000
4                 0              0  1681608671000  1681608677000
5                 0              0  1681608678000  1681609687000
6                 0              0  1681609776000  1681609783000
7                 0              0  1681609784000  1681610453000
8                 0              0  1681610533000  1681610538000
9                 0              0  1681610539000  1681612613000
10                0              0  1681612716000  1681612721000
11                0              0  1681612722000  1681612735000
12                0              0  1681612759000  1681612762000
13                0              0  1681612763000  1681614156000
14                0              0  1681608345000  1681608645000
15                0              0  1681608748000  1681613850955
16                0              0  1681613850000  1681614150000
17                0              0  1681614151000  1681614155314

    startLatitude  startLongitude  messageIndex  type  startIndex  endIndex  \
0       25.035357      121.530939             0    18           0         3
1       25.035470      121.531074             1    17           4        40
2       25.033453      121.532489             2    22          42        44
3       25.033465      121.532662             3    17          45        74
4       25.030877      121.534468             4    18          76        79
5       25.030747      121.534440             5    17          80       314
6       25.010954      121.528868             6    18         316       319
7       25.011150      121.528721             7    17         320       463
8       25.022796      121.514520             8    18         465       467
9       25.022802      121.514365             9    17         468       916
10      25.018229      121.503567            10    22         918       920
11      25.018286      121.503704            11    17         921       926
12      25.018549      121.504295            12    22         928       929
13      25.018650      121.504380            13    17         930      1237
14            NaN             NaN            14     5           1        97
15            NaN             NaN            15     3          98      1173
16            NaN             NaN            16     6        1174      1237
17            NaN             NaN            17     3        1238      1239

    totalExerciseReps                                       measurements  \
0                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
1                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
2                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
3                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
4                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
5                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
6                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
7                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
8                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
9                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
10                  0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
11                  0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
12                  0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
13                  0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
14                  0  [{'field': {'id': 121, 'key': 'endTimestamp', ...
15                  0  [{'field': {'id': 121, 'key': 'endTimestamp', ...
16                  0  [{'field': {'id': 121, 'key': 'endTimestamp', ...
17                  0  [{'field': {'id': 121, 'key': 'endTimestamp', ...

                                           lapIndexes  SUM_ENERGY__KILOJOULE  \
0                                                 NaN                    0.0
1                                                 NaN                    NaN
2                                                 NaN                    NaN
3                                                 NaN                    NaN
4                                                 NaN                    NaN
5                                                 NaN                    NaN
6                                                 NaN                    NaN
7                                                 NaN                    NaN
8                                                 NaN                    NaN
9                                                 NaN                    NaN
10                                                NaN                    NaN
11                                                NaN                    NaN
12                                                NaN                    NaN
13                                                NaN                    NaN
14                                                [1]                    NaN
15  [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 1...                    NaN
16                                               [18]                    NaN
17                                           [19, 20]                    NaN

    WEIGHTED_MEAN_RUNCADENCE__BPM  SUM_ELAPSEDDURATION__MILLISECOND  \
0                            23.0                            7002.0
1                             NaN                               NaN
2                             NaN                               NaN
3                             NaN                               NaN
4                             NaN                               NaN
5                             NaN                               NaN
6                             NaN                               NaN
7                             NaN                               NaN
8                             NaN                               NaN
9                             NaN                               NaN
10                            NaN                               NaN
11                            NaN                               NaN
12                            NaN                               NaN
13                            NaN                               NaN
14                            NaN                               NaN
15                            NaN                               NaN
16                            NaN                               NaN
17                            NaN                               NaN

    MAX_SPEED__CENTIMETERS_PER_MILLISECOND  MAX_DOUBLE_CADENCE__BPM  \
0                                   0.1754                    159.0
1                                      NaN                      NaN
2                                      NaN                      NaN
3                                      NaN                      NaN
4                                      NaN                      NaN
5                                      NaN                      NaN
6                                      NaN                      NaN
7                                      NaN                      NaN
8                                      NaN                      NaN
9                                      NaN                      NaN
10                                     NaN                      NaN
11                                     NaN                      NaN
12                                     NaN                      NaN
13                                     NaN                      NaN
14                                     NaN                      NaN
15                                     NaN                      NaN
16                                     NaN                      NaN
17                                     NaN                      NaN

    WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND  \
0                                             0.2072
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN
5                                                NaN
6                                                NaN
7                                                NaN
8                                                NaN
9                                                NaN
10                                               NaN
11                                               NaN
12                                               NaN
13                                               NaN
14                                               NaN
15                                               NaN
16                                               NaN
17                                               NaN

    SUM_DISTANCE__CENTIMETER  WEIGHTED_MEAN_HEARTRATE__BPM  \
0                     1451.0                          76.0
1                        NaN                           NaN
2                        NaN                           NaN
3                        NaN                           NaN
4                        NaN                           NaN
5                        NaN                           NaN
6                        NaN                           NaN
7                        NaN                           NaN
8                        NaN                           NaN
9                        NaN                           NaN
10                       NaN                           NaN
11                       NaN                           NaN
12                       NaN                           NaN
13                       NaN                           NaN
14                       NaN                           NaN
15                       NaN                           NaN
16                       NaN                           NaN
17                       NaN                           NaN

    SUM_DURATION__MILLISECOND  WEIGHTED_MEAN_DOUBLE_CADENCE__BPM  \
0                      7002.0                          45.421875
1                         NaN                                NaN
2                         NaN                                NaN
3                         NaN                                NaN
4                         NaN                                NaN
5                         NaN                                NaN
6                         NaN                                NaN
7                         NaN                                NaN
8                         NaN                                NaN
9                         NaN                                NaN
10                        NaN                                NaN
11                        NaN                                NaN
12                        NaN                                NaN
13                        NaN                                NaN
14                        NaN                                NaN
15                        NaN                                NaN
16                        NaN                                NaN
17                        NaN                                NaN

    SUM_BMR_ENERGY__KILOJOULE  LOSS_ELEVATION__CENTIMETER  \
0                         0.0                         0.0
1                         NaN                         NaN
2                         NaN                         NaN
3                         NaN                         NaN
4                         NaN                         NaN
5                         NaN                         NaN
6                         NaN                         NaN
7                         NaN                         NaN
8                         NaN                         NaN
9                         NaN                         NaN
10                        NaN                         NaN
11                        NaN                         NaN
12                        NaN                         NaN
13                        NaN                         NaN
14                        NaN                         NaN
15                        NaN                         NaN
16                        NaN                         NaN
17                        NaN                         NaN

    MAX_RUNCADENCE__BPM  \
0                  80.0
1                   NaN
2                   NaN
3                   NaN
4                   NaN
5                   NaN
6                   NaN
7                   NaN
8                   NaN
9                   NaN
10                  NaN
11                  NaN
12                  NaN
13                  NaN
14                  NaN
15                  NaN
16                  NaN
17                  NaN

    WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND  \
0                                                 0.0
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                NaN
16                                                NaN
17                                                NaN

    MAX_HEARTRATE__BPM  GAIN_ELEVATION__CENTIMETER  \
0                 76.0                         0.0
1                  NaN                         NaN
2                  NaN                         NaN
3                  NaN                         NaN
4                  NaN                         NaN
5                  NaN                         NaN
6                  NaN                         NaN
7                  NaN                         NaN
8                  NaN                         NaN
9                  NaN                         NaN
10                 NaN                         NaN
11                 NaN                         NaN
12                 NaN                         NaN
13                 NaN                         NaN
14                 NaN                         NaN
15                 NaN                         NaN
16                 NaN                         NaN
17                 NaN                         NaN

    WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER  \
0                                273.735746
1                                       NaN
2                                       NaN
3                                       NaN
4                                       NaN
5                                       NaN
6                                       NaN
7                                       NaN
8                                       NaN
9                                       NaN
10                                      NaN
11                                      NaN
12                                      NaN
13                                      NaN
14                                      NaN
15                                      NaN
16                                      NaN
17                                      NaN

    WEIGHTED_MEAN_ELAPSED_DURATION_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND  \
0                                           -0.011207
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                NaN
16                                                NaN
17                                                NaN

    SUM_MOVINGDURATION__MILLISECOND  \
0                            3000.0
1                               NaN
2                               NaN
3                               NaN
4                               NaN
5                               NaN
6                               NaN
7                               NaN
8                               NaN
9                               NaN
10                              NaN
11                              NaN
12                              NaN
13                              NaN
14                              NaN
15                              NaN
16                              NaN
17                              NaN

    WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND
0                                            0.483667
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                NaN
16                                                NaN
17                                                NaN
    startTimeSource  endTimeSource   startTimeGMT     endTimeGMT  \
0                 0              0  1681608345000  1681608351000
1                 0              0  1681608352000  1681608438000
2                 0              0  1681608456000  1681608462000
3                 0              0  1681608463000  1681608586000
4                 0              0  1681608671000  1681608677000
5                 0              0  1681608678000  1681609687000
6                 0              0  1681609776000  1681609783000
7                 0              0  1681609784000  1681610453000
8                 0              0  1681610533000  1681610538000
9                 0              0  1681610539000  1681612613000
10                0              0  1681612716000  1681612721000
11                0              0  1681612722000  1681612735000
12                0              0  1681612759000  1681612762000
13                0              0  1681612763000  1681614156000
14                0              0  1681608345000  1681608645000
15                0              0  1681608748000  1681613850955
16                0              0  1681613850000  1681614150000
17                0              0  1681614151000  1681614155314


/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/145449955.py:12: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_ELAPSED_DURATION_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'SUM_MOVINGDURATION__MILLISECOND_x', 'SUM_BMR_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'SUM_ENERGY__KILOJOULE_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x', 'LOSS_ELEVATION__CENTIMETER_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/145449955.py:12: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_ELAPSED_DURATION_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'SUM_MOVINGDURATION__MILLISECOND_x', 'SUM_BMR_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'SUM_ENERGY__KILOJOULE_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x', 'LOSS_ELEVATION__CENTIMETER_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\

    startTimeSource  endTimeSource   startTimeGMT     endTimeGMT  \
0                 0              0  1681608345000  1681608351000
1                 0              0  1681608352000  1681608438000
2                 0              0  1681608456000  1681608462000
3                 0              0  1681608463000  1681608586000
4                 0              0  1681608671000  1681608677000
5                 0              0  1681608678000  1681609687000
6                 0              0  1681609776000  1681609783000
7                 0              0  1681609784000  1681610453000
8                 0              0  1681610533000  1681610538000
9                 0              0  1681610539000  1681612613000
10                0              0  1681612716000  1681612721000
11                0              0  1681612722000  1681612735000
12                0              0  1681612759000  1681612762000
13                0              0  1681612763000  1681614156000
14                0              0  1681608345000  1681608645000
15                0              0  1681608748000  1681613850955
16                0              0  1681613850000  1681614150000
17                0              0  1681614151000  1681614155314

    startLatitude  startLongitude  messageIndex  type  startIndex  endIndex  \
0       25.035357      121.530939             0    18           0         3
1       25.035470      121.531074             1    17           4        40
2       25.033453      121.532489             2    22          42        44
3       25.033465      121.532662             3    17          45        74
4       25.030877      121.534468             4    18          76        79
5       25.030747      121.534440             5    17          80       314
6       25.010954      121.528868             6    18         316       319
7       25.011150      121.528721             7    17         320       463
8       25.022796      121.514520             8    18         465       467
9       25.022802      121.514365             9    17         468       916
10      25.018229      121.503567            10    22         918       920
11      25.018286      121.503704            11    17         921       926
12      25.018549      121.504295            12    22         928       929
13      25.018650      121.504380            13    17         930      1237
14            NaN             NaN            14     5           1        97
15            NaN             NaN            15     3          98      1173
16            NaN             NaN            16     6        1174      1237
17            NaN             NaN            17     3        1238      1239

    totalExerciseReps                                       measurements  \
0                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
1                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
2                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
3                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
4                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
5                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
6                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
7                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
8                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
9                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
10                  0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
11                  0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
12                  0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
13                  0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
14                  0  [{'field': {'id': 121, 'key': 'endTimestamp', ...
15                  0  [{'field': {'id': 121, 'key': 'endTimestamp', ...
16                  0  [{'field': {'id': 121, 'key': 'endTimestamp', ...
17                  0  [{'field': {'id': 121, 'key': 'endTimestamp', ...

                                           lapIndexes  \
0                                                 NaN
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                [1]
15  [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 1...
16                                               [18]
17                                           [19, 20]

    SUM_ENERGY__KILOJOULE_x  WEIGHTED_MEAN_RUNCADENCE__BPM_x  \
0                       0.0                             23.0
1                       NaN                              NaN
2                       NaN                              NaN
3                       NaN                              NaN
4                       NaN                              NaN
5                       NaN                              NaN
6                       NaN                              NaN
7                       NaN                              NaN
8                       NaN                              NaN
9                       NaN                              NaN
10                      NaN                              NaN
11                      NaN                              NaN
12                      NaN                              NaN
13                      NaN                              NaN
14                      NaN                              NaN
15                      NaN                              NaN
16                      NaN                              NaN
17                      NaN                              NaN

    SUM_ELAPSEDDURATION__MILLISECOND_x  \
0                               7002.0
1                                  NaN
2                                  NaN
3                                  NaN
4                                  NaN
5                                  NaN
6                                  NaN
7                                  NaN
8                                  NaN
9                                  NaN
10                                 NaN
11                                 NaN
12                                 NaN
13                                 NaN
14                                 NaN
15                                 NaN
16                                 NaN
17                                 NaN

    MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x  MAX_DOUBLE_CADENCE__BPM_x  \
0                                     0.1754                      159.0
1                                        NaN                        NaN
2                                        NaN                        NaN
3                                        NaN                        NaN
4                                        NaN                        NaN
5                                        NaN                        NaN
6                                        NaN                        NaN
7                                        NaN                        NaN
8                                        NaN                        NaN
9                                        NaN                        NaN
10                                       NaN                        NaN
11                                       NaN                        NaN
12                                       NaN                        NaN
13                                       NaN                        NaN
14                                       NaN                        NaN
15                                       NaN                        NaN
16                                       NaN                        NaN
17                                       NaN                        NaN

    WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x  \
0                                              0.2072
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                NaN
16                                                NaN
17                                                NaN

    SUM_DISTANCE__CENTIMETER_x  WEIGHTED_MEAN_HEARTRATE__BPM_x  \
0                       1451.0                            76.0
1                          NaN                             NaN
2                          NaN                             NaN
3                          NaN                             NaN
4                          NaN                             NaN
5                          NaN                             NaN
6                          NaN                             NaN
7                          NaN                             NaN
8                          NaN                             NaN
9                          NaN                             NaN
10                         NaN                             NaN
11                         NaN                             NaN
12                         NaN                             NaN
13                         NaN                             NaN
14                         NaN                             NaN
15                         NaN                             NaN
16                         NaN                             NaN
17                         NaN                             NaN

    SUM_DURATION__MILLISECOND_x  WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x  \
0                        7002.0                            45.421875
1                           NaN                                  NaN
2                           NaN                                  NaN
3                           NaN                                  NaN
4                           NaN                                  NaN
5                           NaN                                  NaN
6                           NaN                                  NaN
7                           NaN                                  NaN
8                           NaN                                  NaN
9                           NaN                                  NaN
10                          NaN                                  NaN
11                          NaN                                  NaN
12                          NaN                                  NaN
13                          NaN                                  NaN
14                          NaN                                  NaN
15                          NaN                                  NaN
16                          NaN                                  NaN
17                          NaN                                  NaN

    SUM_BMR_ENERGY__KILOJOULE_x  LOSS_ELEVATION__CENTIMETER_x  \
0                           0.0                           0.0
1                           NaN                           NaN
2                           NaN                           NaN
3                           NaN                           NaN
4                           NaN                           NaN
5                           NaN                           NaN
6                           NaN                           NaN
7                           NaN                           NaN
8                           NaN                           NaN
9                           NaN                           NaN
10                          NaN                           NaN
11                          NaN                           NaN
12                          NaN                           NaN
13                          NaN                           NaN
14                          NaN                           NaN
15                          NaN                           NaN
16                          NaN                           NaN
17                          NaN                           NaN

    MAX_RUNCADENCE__BPM_x  \
0                    80.0
1                     NaN
2                     NaN
3                     NaN
4                     NaN
5                     NaN
6                     NaN
7                     NaN
8                     NaN
9                     NaN
10                    NaN
11                    NaN
12                    NaN
13                    NaN
14                    NaN
15                    NaN
16                    NaN
17                    NaN

    WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x  \
0                                                 0.0
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                NaN
16                                                NaN
17                                                NaN

    MAX_HEARTRATE__BPM_x  GAIN_ELEVATION__CENTIMETER_x  \
0                   76.0                           0.0
1                    NaN                           NaN
2                    NaN                           NaN
3                    NaN                           NaN
4                    NaN                           NaN
5                    NaN                           NaN
6                    NaN                           NaN
7                    NaN                           NaN
8                    NaN                           NaN
9                    NaN                           NaN
10                   NaN                           NaN
11                   NaN                           NaN
12                   NaN                           NaN
13                   NaN                           NaN
14                   NaN                           NaN
15                   NaN                           NaN
16                   NaN                           NaN
17                   NaN                           NaN

    WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x  \
0                                  273.735746
1                                         NaN
2                                         NaN
3                                         NaN
4                                         NaN
5                                         NaN
6                                         NaN
7                                         NaN
8                                         NaN
9                                         NaN
10                                        NaN
11                                        NaN
12                                        NaN
13                                        NaN
14                                        NaN
15                                        NaN
16                                        NaN
17                                        NaN

    WEIGHTED_MEAN_ELAPSED_DURATION_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x  \
0                                           -0.011207
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                NaN
16                                                NaN
17                                                NaN

    SUM_MOVINGDURATION__MILLISECOND_x  \
0                              3000.0
1                                 NaN
2                                 NaN
3                                 NaN
4                                 NaN
5                                 NaN
6                                 NaN
7                                 NaN
8                                 NaN
9                                 NaN
10                                NaN
11                                NaN
12                                NaN
13                                NaN
14                                NaN
15                                NaN
16                                NaN
17                                NaN

    WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x  \
0                                            0.483667
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                NaN
16                                                NaN
17                                                NaN

    SUM_ENERGY__KILOJOULE_y  WEIGHTED_MEAN_RUNCADENCE__BPM_y  \
0                       NaN                              NaN
1                  75.42036                             78.0
2                       NaN                              NaN
3                       NaN                              NaN
4                       NaN                              NaN
5                       NaN                              NaN
6                       NaN                              NaN
7                       NaN                              NaN

    startTimeSource  endTimeSource   startTimeGMT     endTimeGMT  \
0                 0              0  1681608345000  1681608351000
1                 0              0  1681608352000  1681608438000
2                 0              0  1681608456000  1681608462000
3                 0              0  1681608463000  1681608586000
4                 0              0  1681608671000  1681608677000
5                 0              0  1681608678000  1681609687000
6                 0              0  1681609776000  1681609783000
7                 0              0  1681609784000  1681610453000
8                 0              0  1681610533000  1681610538000
9                 0              0  1681610539000  1681612613000
10                0              0  1681612716000  1681612721000
11                0              0  1681612722000  1681612735000
12                0              0  1681612759000  1681612762000
13                0              0  1681612763000  1681614156000
14                0              0  1681608345000  1681608645000
15                0              0  1681608748000  1681613850955
16                0              0  1681613850000  1681614150000
17                0              0  1681614151000  1681614155314

    startLatitude  startLongitude  messageIndex  type  startIndex  endIndex  \
0       25.035357      121.530939             0    18           0         3
1       25.035470      121.531074             1    17           4        40
2       25.033453      121.532489             2    22          42        44
3       25.033465      121.532662             3    17          45        74
4       25.030877      121.534468             4    18          76        79
5       25.030747      121.534440             5    17          80       314
6       25.010954      121.528868             6    18         316       319
7       25.011150      121.528721             7    17         320       463
8       25.022796      121.514520             8    18         465       467
9       25.022802      121.514365             9    17         468       916
10      25.018229      121.503567            10    22         918       920
11      25.018286      121.503704            11    17         921       926
12      25.018549      121.504295            12    22         928       929
13      25.018650      121.504380            13    17         930      1237
14            NaN             NaN            14     5           1        97
15            NaN             NaN            15     3          98      1173
16            NaN             NaN            16     6        1174      1237
17            NaN             NaN            17     3        1238      1239

    totalExerciseReps                                       measurements  \
0                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
1                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
2                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
3                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
4                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
5                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
6                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
7                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
8                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
9                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
10                  0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
11                  0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
12                  0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
13                  0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
14                  0  [{'field': {'id': 121, 'key': 'endTimestamp', ...
15                  0  [{'field': {'id': 121, 'key': 'endTimestamp', ...
16                  0  [{'field': {'id': 121, 'key': 'endTimestamp', ...
17                  0  [{'field': {'id': 121, 'key': 'endTimestamp', ...

                                           lapIndexes  \
0                                                 NaN
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                [1]
15  [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 1...
16                                               [18]
17                                           [19, 20]

    SUM_ENERGY__KILOJOULE_x  WEIGHTED_MEAN_RUNCADENCE__BPM_x  \
0                       0.0                             23.0
1                       NaN                              NaN
2                       NaN                              NaN
3                       NaN                              NaN
4                       NaN                              NaN
5                       NaN                              NaN
6                       NaN                              NaN
7                       NaN                              NaN
8                       NaN                              NaN
9                       NaN                              NaN
10                      NaN                              NaN
11                      NaN                              NaN
12                      NaN                              NaN
13                      NaN                              NaN
14                      NaN                              NaN
15                      NaN                              NaN
16                      NaN                              NaN
17                      NaN                              NaN

    SUM_ELAPSEDDURATION__MILLISECOND_x  \
0                               7002.0
1                                  NaN
2                                  NaN
3                                  NaN
4                                  NaN
5                                  NaN
6                                  NaN
7                                  NaN
8                                  NaN
9                                  NaN
10                                 NaN
11                                 NaN
12                                 NaN
13                                 NaN
14                                 NaN
15                                 NaN
16                                 NaN
17                                 NaN

    MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x  MAX_DOUBLE_CADENCE__BPM_x  \
0                                     0.1754                      159.0
1                                        NaN                        NaN
2                                        NaN                        NaN
3                                        NaN                        NaN
4                                        NaN                        NaN
5                                        NaN                        NaN
6                                        NaN                        NaN
7                                        NaN                        NaN
8                                        NaN                        NaN
9                                        NaN                        NaN
10                                       NaN                        NaN
11                                       NaN                        NaN
12                                       NaN                        NaN
13                                       NaN                        NaN
14                                       NaN                        NaN
15                                       NaN                        NaN
16                                       NaN                        NaN
17                                       NaN                        NaN

    WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x  \
0                                              0.2072
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                NaN
16                                                NaN
17                                                NaN

    SUM_DISTANCE__CENTIMETER_x  WEIGHTED_MEAN_HEARTRATE__BPM_x  \
0                       1451.0                            76.0
1                          NaN                             NaN
2                          NaN                             NaN
3                          NaN                             NaN
4                          NaN                             NaN
5                          NaN                             NaN
6                          NaN                             NaN
7                          NaN                             NaN
8                          NaN                             NaN
9                          NaN                             NaN
10                         NaN                             NaN
11                         NaN                             NaN
12                         NaN                             NaN
13                         NaN                             NaN
14                         NaN                             NaN
15                         NaN                             NaN
16                         NaN                             NaN
17                         NaN                             NaN

    SUM_DURATION__MILLISECOND_x  WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x  \
0                        7002.0                            45.421875
1                           NaN                                  NaN
2                           NaN                                  NaN
3                           NaN                                  NaN
4                           NaN                                  NaN
5                           NaN                                  NaN
6                           NaN                                  NaN
7                           NaN                                  NaN
8                           NaN                                  NaN
9                           NaN                                  NaN
10                          NaN                                  NaN
11                          NaN                                  NaN
12                          NaN                                  NaN
13                          NaN                                  NaN
14                          NaN                                  NaN
15                          NaN                                  NaN
16                          NaN                                  NaN
17                          NaN                                  NaN

    SUM_BMR_ENERGY__KILOJOULE_x  LOSS_ELEVATION__CENTIMETER_x  \
0                           0.0                           0.0
1                           NaN                           NaN
2                           NaN                           NaN
3                           NaN                           NaN
4                           NaN                           NaN
5                           NaN                           NaN
6                           NaN                           NaN
7                           NaN                           NaN
8                           NaN                           NaN
9                           NaN                           NaN
10                          NaN                           NaN
11                          NaN                           NaN
12                          NaN                           NaN
13                          NaN                           NaN
14                          NaN                           NaN
15                          NaN                           NaN
16                          NaN                           NaN
17                          NaN                           NaN

    MAX_RUNCADENCE__BPM_x  \
0                    80.0
1                     NaN
2                     NaN
3                     NaN
4                     NaN
5                     NaN
6                     NaN
7                     NaN
8                     NaN
9                     NaN
10                    NaN
11                    NaN
12                    NaN
13                    NaN
14                    NaN
15                    NaN
16                    NaN
17                    NaN

    WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x  \
0                                                 0.0
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                NaN
16                                                NaN
17                                                NaN

    MAX_HEARTRATE__BPM_x  GAIN_ELEVATION__CENTIMETER_x  \
0                   76.0                           0.0
1                    NaN                           NaN
2                    NaN                           NaN
3                    NaN                           NaN
4                    NaN                           NaN
5                    NaN                           NaN
6                    NaN                           NaN
7                    NaN                           NaN
8                    NaN                           NaN
9                    NaN                           NaN
10                   NaN                           NaN
11                   NaN                           NaN
12                   NaN                           NaN
13                   NaN                           NaN
14                   NaN                           NaN
15                   NaN                           NaN
16                   NaN                           NaN
17                   NaN                           NaN

    WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x  \
0                                  273.735746
1                                         NaN
2                                         NaN
3                                         NaN
4                                         NaN
5                                         NaN
6                                         NaN
7                                         NaN
8                                         NaN
9                                         NaN
10                                        NaN
11                                        NaN
12                                        NaN
13                                        NaN
14                                        NaN
15                                        NaN
16                                        NaN
17                                        NaN

    WEIGHTED_MEAN_ELAPSED_DURATION_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x  \
0                                           -0.011207
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                NaN
16                                                NaN
17                                                NaN

    SUM_MOVINGDURATION__MILLISECOND_x  \
0                              3000.0
1                                 NaN
2                                 NaN
3                                 NaN
4                                 NaN
5                                 NaN
6                                 NaN
7                                 NaN
8                                 NaN
9                                 NaN
10                                NaN
11                                NaN
12                                NaN
13                                NaN
14                                NaN
15                                NaN
16                                NaN
17                                NaN

    WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x  \
0                                            0.483667
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                NaN
16                                                NaN
17                                                NaN

    SUM_ENERGY__KILOJOULE_y  WEIGHTED_MEAN_RUNCADENCE__BPM_y  \
0                       NaN                              NaN
1                  75.42036                             78.0
2                       NaN                              NaN
3                       NaN                              NaN
4                       NaN                              NaN
5                       NaN                              NaN
6                       NaN                              NaN
7                       NaN                              NaN

/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/145449955.py:12: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_ELAPSED_DURATION_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'SUM_MOVINGDURATION__MILLISECOND_x', 'SUM_BMR_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'SUM_ENERGY__KILOJOULE_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x', 'LOSS_ELEVATION__CENTIMETER_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\

    startTimeSource  endTimeSource   startTimeGMT     endTimeGMT  \
0                 0              0  1681608345000  1681608351000
1                 0              0  1681608352000  1681608438000
2                 0              0  1681608456000  1681608462000
3                 0              0  1681608463000  1681608586000
4                 0              0  1681608671000  1681608677000
5                 0              0  1681608678000  1681609687000
6                 0              0  1681609776000  1681609783000
7                 0              0  1681609784000  1681610453000
8                 0              0  1681610533000  1681610538000
9                 0              0  1681610539000  1681612613000
10                0              0  1681612716000  1681612721000
11                0              0  1681612722000  1681612735000
12                0              0  1681612759000  1681612762000
13                0              0  1681612763000  1681614156000
14                0              0  1681608345000  1681608645000
15                0              0  1681608748000  1681613850955
16                0              0  1681613850000  1681614150000
17                0              0  1681614151000  1681614155314

    startLatitude  startLongitude  messageIndex  type  startIndex  endIndex  \
0       25.035357      121.530939             0    18           0         3
1       25.035470      121.531074             1    17           4        40
2       25.033453      121.532489             2    22          42        44
3       25.033465      121.532662             3    17          45        74
4       25.030877      121.534468             4    18          76        79
5       25.030747      121.534440             5    17          80       314
6       25.010954      121.528868             6    18         316       319
7       25.011150      121.528721             7    17         320       463
8       25.022796      121.514520             8    18         465       467
9       25.022802      121.514365             9    17         468       916
10      25.018229      121.503567            10    22         918       920
11      25.018286      121.503704            11    17         921       926
12      25.018549      121.504295            12    22         928       929
13      25.018650      121.504380            13    17         930      1237
14            NaN             NaN            14     5           1        97
15            NaN             NaN            15     3          98      1173
16            NaN             NaN            16     6        1174      1237
17            NaN             NaN            17     3        1238      1239

    totalExerciseReps                                       measurements  \
0                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
1                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
2                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
3                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
4                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
5                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
6                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
7                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
8                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
9                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
10                  0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
11                  0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
12                  0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
13                  0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
14                  0  [{'field': {'id': 121, 'key': 'endTimestamp', ...
15                  0  [{'field': {'id': 121, 'key': 'endTimestamp', ...
16                  0  [{'field': {'id': 121, 'key': 'endTimestamp', ...
17                  0  [{'field': {'id': 121, 'key': 'endTimestamp', ...

                                           lapIndexes  \
0                                                 NaN
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                [1]
15  [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 1...
16                                               [18]
17                                           [19, 20]

    SUM_ENERGY__KILOJOULE_x  WEIGHTED_MEAN_RUNCADENCE__BPM_x  \
0                       0.0                             23.0
1                       NaN                              NaN
2                       NaN                              NaN
3                       NaN                              NaN
4                       NaN                              NaN
5                       NaN                              NaN
6                       NaN                              NaN
7                       NaN                              NaN
8                       NaN                              NaN
9                       NaN                              NaN
10                      NaN                              NaN
11                      NaN                              NaN
12                      NaN                              NaN
13                      NaN                              NaN
14                      NaN                              NaN
15                      NaN                              NaN
16                      NaN                              NaN
17                      NaN                              NaN

    SUM_ELAPSEDDURATION__MILLISECOND_x  \
0                               7002.0
1                                  NaN
2                                  NaN
3                                  NaN
4                                  NaN
5                                  NaN
6                                  NaN
7                                  NaN
8                                  NaN
9                                  NaN
10                                 NaN
11                                 NaN
12                                 NaN
13                                 NaN
14                                 NaN
15                                 NaN
16                                 NaN
17                                 NaN

    MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x  MAX_DOUBLE_CADENCE__BPM_x  \
0                                     0.1754                      159.0
1                                        NaN                        NaN
2                                        NaN                        NaN
3                                        NaN                        NaN
4                                        NaN                        NaN
5                                        NaN                        NaN
6                                        NaN                        NaN
7                                        NaN                        NaN
8                                        NaN                        NaN
9                                        NaN                        NaN
10                                       NaN                        NaN
11                                       NaN                        NaN
12                                       NaN                        NaN
13                                       NaN                        NaN
14                                       NaN                        NaN
15                                       NaN                        NaN
16                                       NaN                        NaN
17                                       NaN                        NaN

    WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x  \
0                                              0.2072
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                NaN
16                                                NaN
17                                                NaN

    SUM_DISTANCE__CENTIMETER_x  WEIGHTED_MEAN_HEARTRATE__BPM_x  \
0                       1451.0                            76.0
1                          NaN                             NaN
2                          NaN                             NaN
3                          NaN                             NaN
4                          NaN                             NaN
5                          NaN                             NaN
6                          NaN                             NaN
7                          NaN                             NaN
8                          NaN                             NaN
9                          NaN                             NaN
10                         NaN                             NaN
11                         NaN                             NaN
12                         NaN                             NaN
13                         NaN                             NaN
14                         NaN                             NaN
15                         NaN                             NaN
16                         NaN                             NaN
17                         NaN                             NaN

    SUM_DURATION__MILLISECOND_x  WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x  \
0                        7002.0                            45.421875
1                           NaN                                  NaN
2                           NaN                                  NaN
3                           NaN                                  NaN
4                           NaN                                  NaN
5                           NaN                                  NaN
6                           NaN                                  NaN
7                           NaN                                  NaN
8                           NaN                                  NaN
9                           NaN                                  NaN
10                          NaN                                  NaN
11                          NaN                                  NaN
12                          NaN                                  NaN
13                          NaN                                  NaN
14                          NaN                                  NaN
15                          NaN                                  NaN
16                          NaN                                  NaN
17                          NaN                                  NaN

    SUM_BMR_ENERGY__KILOJOULE_x  LOSS_ELEVATION__CENTIMETER_x  \
0                           0.0                           0.0
1                           NaN                           NaN
2                           NaN                           NaN
3                           NaN                           NaN
4                           NaN                           NaN
5                           NaN                           NaN
6                           NaN                           NaN
7                           NaN                           NaN
8                           NaN                           NaN
9                           NaN                           NaN
10                          NaN                           NaN
11                          NaN                           NaN
12                          NaN                           NaN
13                          NaN                           NaN
14                          NaN                           NaN
15                          NaN                           NaN
16                          NaN                           NaN
17                          NaN                           NaN

    MAX_RUNCADENCE__BPM_x  \
0                    80.0
1                     NaN
2                     NaN
3                     NaN
4                     NaN
5                     NaN
6                     NaN
7                     NaN
8                     NaN
9                     NaN
10                    NaN
11                    NaN
12                    NaN
13                    NaN
14                    NaN
15                    NaN
16                    NaN
17                    NaN

    WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x  \
0                                                 0.0
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                NaN
16                                                NaN
17                                                NaN

    MAX_HEARTRATE__BPM_x  GAIN_ELEVATION__CENTIMETER_x  \
0                   76.0                           0.0
1                    NaN                           NaN
2                    NaN                           NaN
3                    NaN                           NaN
4                    NaN                           NaN
5                    NaN                           NaN
6                    NaN                           NaN
7                    NaN                           NaN
8                    NaN                           NaN
9                    NaN                           NaN
10                   NaN                           NaN
11                   NaN                           NaN
12                   NaN                           NaN
13                   NaN                           NaN
14                   NaN                           NaN
15                   NaN                           NaN
16                   NaN                           NaN
17                   NaN                           NaN

    WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x  \
0                                  273.735746
1                                         NaN
2                                         NaN
3                                         NaN
4                                         NaN
5                                         NaN
6                                         NaN
7                                         NaN
8                                         NaN
9                                         NaN
10                                        NaN
11                                        NaN
12                                        NaN
13                                        NaN
14                                        NaN
15                                        NaN
16                                        NaN
17                                        NaN

    WEIGHTED_MEAN_ELAPSED_DURATION_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x  \
0                                           -0.011207
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                NaN
16                                                NaN
17                                                NaN

    SUM_MOVINGDURATION__MILLISECOND_x  \
0                              3000.0
1                                 NaN
2                                 NaN
3                                 NaN
4                                 NaN
5                                 NaN
6                                 NaN
7                                 NaN
8                                 NaN
9                                 NaN
10                                NaN
11                                NaN
12                                NaN
13                                NaN
14                                NaN
15                                NaN
16                                NaN
17                                NaN

    WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x  \
0                                            0.483667
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                NaN
16                                                NaN
17                                                NaN

    SUM_ENERGY__KILOJOULE_y  WEIGHTED_MEAN_RUNCADENCE__BPM_y  \
0                       NaN                              NaN
1                  75.42036                             78.0
2                       NaN                              NaN
3                       NaN                              NaN
4                       NaN                              NaN
5                       NaN                              NaN
6                       NaN                              NaN
7                       NaN                              NaN

    startTimeSource  endTimeSource   startTimeGMT     endTimeGMT  \
0                 0              0  1681608345000  1681608351000
1                 0              0  1681608352000  1681608438000
2                 0              0  1681608456000  1681608462000
3                 0              0  1681608463000  1681608586000
4                 0              0  1681608671000  1681608677000
5                 0              0  1681608678000  1681609687000
6                 0              0  1681609776000  1681609783000
7                 0              0  1681609784000  1681610453000
8                 0              0  1681610533000  1681610538000
9                 0              0  1681610539000  1681612613000
10                0              0  1681612716000  1681612721000
11                0              0  1681612722000  1681612735000
12                0              0  1681612759000  1681612762000
13                0              0  1681612763000  1681614156000
14                0              0  1681608345000  1681608645000
15                0              0  1681608748000  1681613850955
16                0              0  1681613850000  1681614150000
17                0              0  1681614151000  1681614155314

    startLatitude  startLongitude  messageIndex  type  startIndex  endIndex  \
0       25.035357      121.530939             0    18           0         3
1       25.035470      121.531074             1    17           4        40
2       25.033453      121.532489             2    22          42        44
3       25.033465      121.532662             3    17          45        74
4       25.030877      121.534468             4    18          76        79
5       25.030747      121.534440             5    17          80       314
6       25.010954      121.528868             6    18         316       319
7       25.011150      121.528721             7    17         320       463
8       25.022796      121.514520             8    18         465       467
9       25.022802      121.514365             9    17         468       916
10      25.018229      121.503567            10    22         918       920
11      25.018286      121.503704            11    17         921       926
12      25.018549      121.504295            12    22         928       929
13      25.018650      121.504380            13    17         930      1237
14            NaN             NaN            14     5           1        97
15            NaN             NaN            15     3          98      1173
16            NaN             NaN            16     6        1174      1237
17            NaN             NaN            17     3        1238      1239

    totalExerciseReps                                       measurements  \
0                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
1                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
2                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
3                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
4                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
5                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
6                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
7                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
8                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
9                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
10                  0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
11                  0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
12                  0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
13                  0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
14                  0  [{'field': {'id': 121, 'key': 'endTimestamp', ...
15                  0  [{'field': {'id': 121, 'key': 'endTimestamp', ...
16                  0  [{'field': {'id': 121, 'key': 'endTimestamp', ...
17                  0  [{'field': {'id': 121, 'key': 'endTimestamp', ...

                                           lapIndexes  \
0                                                 NaN
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                [1]
15  [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 1...
16                                               [18]
17                                           [19, 20]

    SUM_ENERGY__KILOJOULE_x  WEIGHTED_MEAN_RUNCADENCE__BPM_x  \
0                       0.0                             23.0
1                       NaN                              NaN
2                       NaN                              NaN
3                       NaN                              NaN
4                       NaN                              NaN
5                       NaN                              NaN
6                       NaN                              NaN
7                       NaN                              NaN
8                       NaN                              NaN
9                       NaN                              NaN
10                      NaN                              NaN
11                      NaN                              NaN
12                      NaN                              NaN
13                      NaN                              NaN
14                      NaN                              NaN
15                      NaN                              NaN
16                      NaN                              NaN
17                      NaN                              NaN

    SUM_ELAPSEDDURATION__MILLISECOND_x  \
0                               7002.0
1                                  NaN
2                                  NaN
3                                  NaN
4                                  NaN
5                                  NaN
6                                  NaN
7                                  NaN
8                                  NaN
9                                  NaN
10                                 NaN
11                                 NaN
12                                 NaN
13                                 NaN
14                                 NaN
15                                 NaN
16                                 NaN
17                                 NaN

    MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x  MAX_DOUBLE_CADENCE__BPM_x  \
0                                     0.1754                      159.0
1                                        NaN                        NaN
2                                        NaN                        NaN
3                                        NaN                        NaN
4                                        NaN                        NaN
5                                        NaN                        NaN
6                                        NaN                        NaN
7                                        NaN                        NaN
8                                        NaN                        NaN
9                                        NaN                        NaN
10                                       NaN                        NaN
11                                       NaN                        NaN
12                                       NaN                        NaN
13                                       NaN                        NaN
14                                       NaN                        NaN
15                                       NaN                        NaN
16                                       NaN                        NaN
17                                       NaN                        NaN

    WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x  \
0                                              0.2072
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                NaN
16                                                NaN
17                                                NaN

    SUM_DISTANCE__CENTIMETER_x  WEIGHTED_MEAN_HEARTRATE__BPM_x  \
0                       1451.0                            76.0
1                          NaN                             NaN
2                          NaN                             NaN
3                          NaN                             NaN
4                          NaN                             NaN
5                          NaN                             NaN
6                          NaN                             NaN
7                          NaN                             NaN
8                          NaN                             NaN
9                          NaN                             NaN
10                         NaN                             NaN
11                         NaN                             NaN
12                         NaN                             NaN
13                         NaN                             NaN
14                         NaN                             NaN
15                         NaN                             NaN
16                         NaN                             NaN
17                         NaN                             NaN

    SUM_DURATION__MILLISECOND_x  WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x  \
0                        7002.0                            45.421875
1                           NaN                                  NaN
2                           NaN                                  NaN
3                           NaN                                  NaN
4                           NaN                                  NaN
5                           NaN                                  NaN
6                           NaN                                  NaN
7                           NaN                                  NaN
8                           NaN                                  NaN
9                           NaN                                  NaN
10                          NaN                                  NaN
11                          NaN                                  NaN
12                          NaN                                  NaN
13                          NaN                                  NaN
14                          NaN                                  NaN
15                          NaN                                  NaN
16                          NaN                                  NaN
17                          NaN                                  NaN

    SUM_BMR_ENERGY__KILOJOULE_x  LOSS_ELEVATION__CENTIMETER_x  \
0                           0.0                           0.0
1                           NaN                           NaN
2                           NaN                           NaN
3                           NaN                           NaN
4                           NaN                           NaN
5                           NaN                           NaN
6                           NaN                           NaN
7                           NaN                           NaN
8                           NaN                           NaN
9                           NaN                           NaN
10                          NaN                           NaN
11                          NaN                           NaN
12                          NaN                           NaN
13                          NaN                           NaN
14                          NaN                           NaN
15                          NaN                           NaN
16                          NaN                           NaN
17                          NaN                           NaN

    MAX_RUNCADENCE__BPM_x  \
0                    80.0
1                     NaN
2                     NaN
3                     NaN
4                     NaN
5                     NaN
6                     NaN
7                     NaN
8                     NaN
9                     NaN
10                    NaN
11                    NaN
12                    NaN
13                    NaN
14                    NaN
15                    NaN
16                    NaN
17                    NaN

    WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x  \
0                                                 0.0
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                NaN
16                                                NaN
17                                                NaN

    MAX_HEARTRATE__BPM_x  GAIN_ELEVATION__CENTIMETER_x  \
0                   76.0                           0.0
1                    NaN                           NaN
2                    NaN                           NaN
3                    NaN                           NaN
4                    NaN                           NaN
5                    NaN                           NaN
6                    NaN                           NaN
7                    NaN                           NaN
8                    NaN                           NaN
9                    NaN                           NaN
10                   NaN                           NaN
11                   NaN                           NaN
12                   NaN                           NaN
13                   NaN                           NaN
14                   NaN                           NaN
15                   NaN                           NaN
16                   NaN                           NaN
17                   NaN                           NaN

    WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x  \
0                                  273.735746
1                                         NaN
2                                         NaN
3                                         NaN
4                                         NaN
5                                         NaN
6                                         NaN
7                                         NaN
8                                         NaN
9                                         NaN
10                                        NaN
11                                        NaN
12                                        NaN
13                                        NaN
14                                        NaN
15                                        NaN
16                                        NaN
17                                        NaN

    WEIGHTED_MEAN_ELAPSED_DURATION_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x  \
0                                           -0.011207
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                NaN
16                                                NaN
17                                                NaN

    SUM_MOVINGDURATION__MILLISECOND_x  \
0                              3000.0
1                                 NaN
2                                 NaN
3                                 NaN
4                                 NaN
5                                 NaN
6                                 NaN
7                                 NaN
8                                 NaN
9                                 NaN
10                                NaN
11                                NaN
12                                NaN
13                                NaN
14                                NaN
15                                NaN
16                                NaN
17                                NaN

    WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x  \
0                                            0.483667
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                NaN
16                                                NaN
17                                                NaN

    SUM_ENERGY__KILOJOULE_y  WEIGHTED_MEAN_RUNCADENCE__BPM_y  \
0                       NaN                              NaN
1                  75.42036                             78.0
2                       NaN                              NaN
3                       NaN                              NaN
4                       NaN                              NaN
5                       NaN                              NaN
6                       NaN                              NaN
7                       NaN                              NaN

/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/145449955.py:12: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_ELAPSED_DURATION_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'SUM_MOVINGDURATION__MILLISECOND_x', 'SUM_BMR_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'SUM_ENERGY__KILOJOULE_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x', 'LOSS_ELEVATION__CENTIMETER_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/145449955.py:12: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_ELAPSED_DURATION_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'SUM_MOVINGDURATION__MILLISECOND_x', 'SUM_BMR_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'SUM_ENERGY__KILOJOULE_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x', 'LOSS_ELEVATION__CENTIMETER_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\

    startTimeSource  endTimeSource   startTimeGMT     endTimeGMT  \
0                 0              0  1681608345000  1681608351000
1                 0              0  1681608352000  1681608438000
2                 0              0  1681608456000  1681608462000
3                 0              0  1681608463000  1681608586000
4                 0              0  1681608671000  1681608677000
5                 0              0  1681608678000  1681609687000
6                 0              0  1681609776000  1681609783000
7                 0              0  1681609784000  1681610453000
8                 0              0  1681610533000  1681610538000
9                 0              0  1681610539000  1681612613000
10                0              0  1681612716000  1681612721000
11                0              0  1681612722000  1681612735000
12                0              0  1681612759000  1681612762000
13                0              0  1681612763000  1681614156000
14                0              0  1681608345000  1681608645000
15                0              0  1681608748000  1681613850955
16                0              0  1681613850000  1681614150000
17                0              0  1681614151000  1681614155314

    startLatitude  startLongitude  messageIndex  type  startIndex  endIndex  \
0       25.035357      121.530939             0    18           0         3
1       25.035470      121.531074             1    17           4        40
2       25.033453      121.532489             2    22          42        44
3       25.033465      121.532662             3    17          45        74
4       25.030877      121.534468             4    18          76        79
5       25.030747      121.534440             5    17          80       314
6       25.010954      121.528868             6    18         316       319
7       25.011150      121.528721             7    17         320       463
8       25.022796      121.514520             8    18         465       467
9       25.022802      121.514365             9    17         468       916
10      25.018229      121.503567            10    22         918       920
11      25.018286      121.503704            11    17         921       926
12      25.018549      121.504295            12    22         928       929
13      25.018650      121.504380            13    17         930      1237
14            NaN             NaN            14     5           1        97
15            NaN             NaN            15     3          98      1173
16            NaN             NaN            16     6        1174      1237
17            NaN             NaN            17     3        1238      1239

    totalExerciseReps                                       measurements  \
0                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
1                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
2                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
3                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
4                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
5                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
6                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
7                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
8                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
9                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
10                  0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
11                  0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
12                  0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
13                  0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
14                  0  [{'field': {'id': 121, 'key': 'endTimestamp', ...
15                  0  [{'field': {'id': 121, 'key': 'endTimestamp', ...
16                  0  [{'field': {'id': 121, 'key': 'endTimestamp', ...
17                  0  [{'field': {'id': 121, 'key': 'endTimestamp', ...

                                           lapIndexes  \
0                                                 NaN
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                [1]
15  [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 1...
16                                               [18]
17                                           [19, 20]

    SUM_ENERGY__KILOJOULE_x  WEIGHTED_MEAN_RUNCADENCE__BPM_x  \
0                       0.0                             23.0
1                       NaN                              NaN
2                       NaN                              NaN
3                       NaN                              NaN
4                       NaN                              NaN
5                       NaN                              NaN
6                       NaN                              NaN
7                       NaN                              NaN
8                       NaN                              NaN
9                       NaN                              NaN
10                      NaN                              NaN
11                      NaN                              NaN
12                      NaN                              NaN
13                      NaN                              NaN
14                      NaN                              NaN
15                      NaN                              NaN
16                      NaN                              NaN
17                      NaN                              NaN

    SUM_ELAPSEDDURATION__MILLISECOND_x  \
0                               7002.0
1                                  NaN
2                                  NaN
3                                  NaN
4                                  NaN
5                                  NaN
6                                  NaN
7                                  NaN
8                                  NaN
9                                  NaN
10                                 NaN
11                                 NaN
12                                 NaN
13                                 NaN
14                                 NaN
15                                 NaN
16                                 NaN
17                                 NaN

    MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x  MAX_DOUBLE_CADENCE__BPM_x  \
0                                     0.1754                      159.0
1                                        NaN                        NaN
2                                        NaN                        NaN
3                                        NaN                        NaN
4                                        NaN                        NaN
5                                        NaN                        NaN
6                                        NaN                        NaN
7                                        NaN                        NaN
8                                        NaN                        NaN
9                                        NaN                        NaN
10                                       NaN                        NaN
11                                       NaN                        NaN
12                                       NaN                        NaN
13                                       NaN                        NaN
14                                       NaN                        NaN
15                                       NaN                        NaN
16                                       NaN                        NaN
17                                       NaN                        NaN

    WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x  \
0                                              0.2072
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                NaN
16                                                NaN
17                                                NaN

    SUM_DISTANCE__CENTIMETER_x  WEIGHTED_MEAN_HEARTRATE__BPM_x  \
0                       1451.0                            76.0
1                          NaN                             NaN
2                          NaN                             NaN
3                          NaN                             NaN
4                          NaN                             NaN
5                          NaN                             NaN
6                          NaN                             NaN
7                          NaN                             NaN
8                          NaN                             NaN
9                          NaN                             NaN
10                         NaN                             NaN
11                         NaN                             NaN
12                         NaN                             NaN
13                         NaN                             NaN
14                         NaN                             NaN
15                         NaN                             NaN
16                         NaN                             NaN
17                         NaN                             NaN

    SUM_DURATION__MILLISECOND_x  WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x  \
0                        7002.0                            45.421875
1                           NaN                                  NaN
2                           NaN                                  NaN
3                           NaN                                  NaN
4                           NaN                                  NaN
5                           NaN                                  NaN
6                           NaN                                  NaN
7                           NaN                                  NaN
8                           NaN                                  NaN
9                           NaN                                  NaN
10                          NaN                                  NaN
11                          NaN                                  NaN
12                          NaN                                  NaN
13                          NaN                                  NaN
14                          NaN                                  NaN
15                          NaN                                  NaN
16                          NaN                                  NaN
17                          NaN                                  NaN

    SUM_BMR_ENERGY__KILOJOULE_x  LOSS_ELEVATION__CENTIMETER_x  \
0                           0.0                           0.0
1                           NaN                           NaN
2                           NaN                           NaN
3                           NaN                           NaN
4                           NaN                           NaN
5                           NaN                           NaN
6                           NaN                           NaN
7                           NaN                           NaN
8                           NaN                           NaN
9                           NaN                           NaN
10                          NaN                           NaN
11                          NaN                           NaN
12                          NaN                           NaN
13                          NaN                           NaN
14                          NaN                           NaN
15                          NaN                           NaN
16                          NaN                           NaN
17                          NaN                           NaN

    MAX_RUNCADENCE__BPM_x  \
0                    80.0
1                     NaN
2                     NaN
3                     NaN
4                     NaN
5                     NaN
6                     NaN
7                     NaN
8                     NaN
9                     NaN
10                    NaN
11                    NaN
12                    NaN
13                    NaN
14                    NaN
15                    NaN
16                    NaN
17                    NaN

    WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x  \
0                                                 0.0
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                NaN
16                                                NaN
17                                                NaN

    MAX_HEARTRATE__BPM_x  GAIN_ELEVATION__CENTIMETER_x  \
0                   76.0                           0.0
1                    NaN                           NaN
2                    NaN                           NaN
3                    NaN                           NaN
4                    NaN                           NaN
5                    NaN                           NaN
6                    NaN                           NaN
7                    NaN                           NaN
8                    NaN                           NaN
9                    NaN                           NaN
10                   NaN                           NaN
11                   NaN                           NaN
12                   NaN                           NaN
13                   NaN                           NaN
14                   NaN                           NaN
15                   NaN                           NaN
16                   NaN                           NaN
17                   NaN                           NaN

    WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x  \
0                                  273.735746
1                                         NaN
2                                         NaN
3                                         NaN
4                                         NaN
5                                         NaN
6                                         NaN
7                                         NaN
8                                         NaN
9                                         NaN
10                                        NaN
11                                        NaN
12                                        NaN
13                                        NaN
14                                        NaN
15                                        NaN
16                                        NaN
17                                        NaN

    WEIGHTED_MEAN_ELAPSED_DURATION_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x  \
0                                           -0.011207
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                NaN
16                                                NaN
17                                                NaN

    SUM_MOVINGDURATION__MILLISECOND_x  \
0                              3000.0
1                                 NaN
2                                 NaN
3                                 NaN
4                                 NaN
5                                 NaN
6                                 NaN
7                                 NaN
8                                 NaN
9                                 NaN
10                                NaN
11                                NaN
12                                NaN
13                                NaN
14                                NaN
15                                NaN
16                                NaN
17                                NaN

    WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x  \
0                                            0.483667
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                NaN
16                                                NaN
17                                                NaN

    SUM_ENERGY__KILOJOULE_y  WEIGHTED_MEAN_RUNCADENCE__BPM_y  \
0                       NaN                              NaN
1                  75.42036                             78.0
2                       NaN                              NaN
3                       NaN                              NaN
4                       NaN                              NaN
5                       NaN                              NaN
6                       NaN                              NaN
7                       NaN                              NaN

/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/145449955.py:12: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_ELAPSED_DURATION_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'SUM_MOVINGDURATION__MILLISECOND_x', 'SUM_BMR_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'SUM_ENERGY__KILOJOULE_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x', 'LOSS_ELEVATION__CENTIMETER_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\

    startTimeSource  endTimeSource   startTimeGMT     endTimeGMT  \
0                 0              0  1681608345000  1681608351000
1                 0              0  1681608352000  1681608438000
2                 0              0  1681608456000  1681608462000
3                 0              0  1681608463000  1681608586000
4                 0              0  1681608671000  1681608677000
5                 0              0  1681608678000  1681609687000
6                 0              0  1681609776000  1681609783000
7                 0              0  1681609784000  1681610453000
8                 0              0  1681610533000  1681610538000
9                 0              0  1681610539000  1681612613000
10                0              0  1681612716000  1681612721000
11                0              0  1681612722000  1681612735000
12                0              0  1681612759000  1681612762000
13                0              0  1681612763000  1681614156000
14                0              0  1681608345000  1681608645000
15                0              0  1681608748000  1681613850955
16                0              0  1681613850000  1681614150000
17                0              0  1681614151000  1681614155314

    startLatitude  startLongitude  messageIndex  type  startIndex  endIndex  \
0       25.035357      121.530939             0    18           0         3
1       25.035470      121.531074             1    17           4        40
2       25.033453      121.532489             2    22          42        44
3       25.033465      121.532662             3    17          45        74
4       25.030877      121.534468             4    18          76        79
5       25.030747      121.534440             5    17          80       314
6       25.010954      121.528868             6    18         316       319
7       25.011150      121.528721             7    17         320       463
8       25.022796      121.514520             8    18         465       467
9       25.022802      121.514365             9    17         468       916
10      25.018229      121.503567            10    22         918       920
11      25.018286      121.503704            11    17         921       926
12      25.018549      121.504295            12    22         928       929
13      25.018650      121.504380            13    17         930      1237
14            NaN             NaN            14     5           1        97
15            NaN             NaN            15     3          98      1173
16            NaN             NaN            16     6        1174      1237
17            NaN             NaN            17     3        1238      1239

    totalExerciseReps                                       measurements  \
0                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
1                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
2                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
3                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
4                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
5                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
6                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
7                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
8                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
9                   0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
10                  0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
11                  0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
12                  0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
13                  0  [{'field': {'id': 113, 'key': 'sumEnergy', 'co...
14                  0  [{'field': {'id': 121, 'key': 'endTimestamp', ...
15                  0  [{'field': {'id': 121, 'key': 'endTimestamp', ...
16                  0  [{'field': {'id': 121, 'key': 'endTimestamp', ...
17                  0  [{'field': {'id': 121, 'key': 'endTimestamp', ...

                                           lapIndexes  \
0                                                 NaN
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                [1]
15  [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 1...
16                                               [18]
17                                           [19, 20]

    SUM_ENERGY__KILOJOULE_x  WEIGHTED_MEAN_RUNCADENCE__BPM_x  \
0                       0.0                             23.0
1                       NaN                              NaN
2                       NaN                              NaN
3                       NaN                              NaN
4                       NaN                              NaN
5                       NaN                              NaN
6                       NaN                              NaN
7                       NaN                              NaN
8                       NaN                              NaN
9                       NaN                              NaN
10                      NaN                              NaN
11                      NaN                              NaN
12                      NaN                              NaN
13                      NaN                              NaN
14                      NaN                              NaN
15                      NaN                              NaN
16                      NaN                              NaN
17                      NaN                              NaN

    SUM_ELAPSEDDURATION__MILLISECOND_x  \
0                               7002.0
1                                  NaN
2                                  NaN
3                                  NaN
4                                  NaN
5                                  NaN
6                                  NaN
7                                  NaN
8                                  NaN
9                                  NaN
10                                 NaN
11                                 NaN
12                                 NaN
13                                 NaN
14                                 NaN
15                                 NaN
16                                 NaN
17                                 NaN

    MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x  MAX_DOUBLE_CADENCE__BPM_x  \
0                                     0.1754                      159.0
1                                        NaN                        NaN
2                                        NaN                        NaN
3                                        NaN                        NaN
4                                        NaN                        NaN
5                                        NaN                        NaN
6                                        NaN                        NaN
7                                        NaN                        NaN
8                                        NaN                        NaN
9                                        NaN                        NaN
10                                       NaN                        NaN
11                                       NaN                        NaN
12                                       NaN                        NaN
13                                       NaN                        NaN
14                                       NaN                        NaN
15                                       NaN                        NaN
16                                       NaN                        NaN
17                                       NaN                        NaN

    WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x  \
0                                              0.2072
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                NaN
16                                                NaN
17                                                NaN

    SUM_DISTANCE__CENTIMETER_x  WEIGHTED_MEAN_HEARTRATE__BPM_x  \
0                       1451.0                            76.0
1                          NaN                             NaN
2                          NaN                             NaN
3                          NaN                             NaN
4                          NaN                             NaN
5                          NaN                             NaN
6                          NaN                             NaN
7                          NaN                             NaN
8                          NaN                             NaN
9                          NaN                             NaN
10                         NaN                             NaN
11                         NaN                             NaN
12                         NaN                             NaN
13                         NaN                             NaN
14                         NaN                             NaN
15                         NaN                             NaN
16                         NaN                             NaN
17                         NaN                             NaN

    SUM_DURATION__MILLISECOND_x  WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x  \
0                        7002.0                            45.421875
1                           NaN                                  NaN
2                           NaN                                  NaN
3                           NaN                                  NaN
4                           NaN                                  NaN
5                           NaN                                  NaN
6                           NaN                                  NaN
7                           NaN                                  NaN
8                           NaN                                  NaN
9                           NaN                                  NaN
10                          NaN                                  NaN
11                          NaN                                  NaN
12                          NaN                                  NaN
13                          NaN                                  NaN
14                          NaN                                  NaN
15                          NaN                                  NaN
16                          NaN                                  NaN
17                          NaN                                  NaN

    SUM_BMR_ENERGY__KILOJOULE_x  LOSS_ELEVATION__CENTIMETER_x  \
0                           0.0                           0.0
1                           NaN                           NaN
2                           NaN                           NaN
3                           NaN                           NaN
4                           NaN                           NaN
5                           NaN                           NaN
6                           NaN                           NaN
7                           NaN                           NaN
8                           NaN                           NaN
9                           NaN                           NaN
10                          NaN                           NaN
11                          NaN                           NaN
12                          NaN                           NaN
13                          NaN                           NaN
14                          NaN                           NaN
15                          NaN                           NaN
16                          NaN                           NaN
17                          NaN                           NaN

    MAX_RUNCADENCE__BPM_x  \
0                    80.0
1                     NaN
2                     NaN
3                     NaN
4                     NaN
5                     NaN
6                     NaN
7                     NaN
8                     NaN
9                     NaN
10                    NaN
11                    NaN
12                    NaN
13                    NaN
14                    NaN
15                    NaN
16                    NaN
17                    NaN

    WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x  \
0                                                 0.0
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                NaN
16                                                NaN
17                                                NaN

    MAX_HEARTRATE__BPM_x  GAIN_ELEVATION__CENTIMETER_x  \
0                   76.0                           0.0
1                    NaN                           NaN
2                    NaN                           NaN
3                    NaN                           NaN
4                    NaN                           NaN
5                    NaN                           NaN
6                    NaN                           NaN
7                    NaN                           NaN
8                    NaN                           NaN
9                    NaN                           NaN
10                   NaN                           NaN
11                   NaN                           NaN
12                   NaN                           NaN
13                   NaN                           NaN
14                   NaN                           NaN
15                   NaN                           NaN
16                   NaN                           NaN
17                   NaN                           NaN

    WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x  \
0                                  273.735746
1                                         NaN
2                                         NaN
3                                         NaN
4                                         NaN
5                                         NaN
6                                         NaN
7                                         NaN
8                                         NaN
9                                         NaN
10                                        NaN
11                                        NaN
12                                        NaN
13                                        NaN
14                                        NaN
15                                        NaN
16                                        NaN
17                                        NaN

    WEIGHTED_MEAN_ELAPSED_DURATION_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x  \
0                                           -0.011207
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                NaN
16                                                NaN
17                                                NaN

    SUM_MOVINGDURATION__MILLISECOND_x  \
0                              3000.0
1                                 NaN
2                                 NaN
3                                 NaN
4                                 NaN
5                                 NaN
6                                 NaN
7                                 NaN
8                                 NaN
9                                 NaN
10                                NaN
11                                NaN
12                                NaN
13                                NaN
14                                NaN
15                                NaN
16                                NaN
17                                NaN

    WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x  \
0                                            0.483667
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                NaN
16                                                NaN
17                                                NaN

    SUM_ENERGY__KILOJOULE_y  WEIGHTED_MEAN_RUNCADENCE__BPM_y  \
0                       NaN                              NaN
1                  75.42036                             78.0
2                       NaN                              NaN
3                       NaN                              NaN
4                       NaN                              NaN
5                       NaN                              NaN
6                       NaN                              NaN
7                       NaN                              NaN

/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/145449955.py:12: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_ELAPSED_DURATION_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'SUM_MOVINGDURATION__MILLISECOND_x', 'SUM_BMR_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'SUM_ENERGY__KILOJOULE_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x', 'LOSS_ELEVATION__CENTIMETER_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/145449955.py:12: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'MIN_ELEVATION__CENTIMETER_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'MAX_UNCORRECTED_ELEVATION__CENTIMETER_x', 'WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'MIN_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_ELAPSED_DURATION_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_CORRECTED_ELEVATION__CENTIMETER_x', 'END_TIMESTAMP__GMT_x', 'LOSS_UNCORRECTED_ELEVATION__CENTIMETER_x', 'GAIN_UNCORRECTED_ELEVATION__CENTIMETER_x', 'END_LONGITUDE__DECIMAL_DEGREE_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MIN_HEARTRATE__BPM_x', 'GAIN_CORRECTED_ELEVATION__CENTIMETER_x', 'MIN_RUNCADENCE__BPM_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'WEIGHTED_MEAN_FRACTIONAL_CADENCE__BPM_x', 'SUM_MOVINGDURATION__MILLISECOND_x', 'MAX_FRACTIONAL_CADENCE__BPM_x', 'MIN_CORRECTED_ELEVATION__CENTIMETER_x', 'SUM_STEP__STEP_x', 'SUM_BMR_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_ELEVATION__CENTIMETER_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'SUM_ENERGY__KILOJOULE_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'END_LATITUDE__DECIMAL_DEGREE_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x', 'LOSS_CORRECTED_ELEVATION__CENTIMETER_x', 'MIN_ACTIVITY_LAP_DURATION__MILLISECOND_x', 'LOSS_ELEVATION__CENTIMETER_x', 'MIN_UNCORRECTED_ELEVATION__CENTIMETER_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\

    startTimeSource  endTimeSource   startTimeGMT     endTimeGMT  \
0                 0              0  1681466498000  1681466503000
1                 0              0  1681466504000  1681466632000
2                 0              0  1681466665000  1681466670000
3                 0              0  1681466671000  1681468719000
4                 0              0  1681468846000  1681468848000
5                 0              0  1681468849000  1681468877000
6                 0              0  1681468936000  1681468939000
7                 0              0  1681468940000  1681469003000
8                 0              0  1681469097000  1681469098000
9                 0              0  1681469099000  1681469102000
10                0              0  1681469103000  1681469876000
11                0              0  1681466498000  1681467435850
12                0              0  1681467436000  1681468696000
13                0              0  1681468696000  1681469877182

    startLatitude  startLongitude  messageIndex  type  startIndex  endIndex  \
0       25.035366      121.531597             0    22           0         2
1       25.035256      121.531557             1    17           3        41
2       25.033510      121.533294             2    22          43        44
3       25.033513      121.533409             3    17          46       639
4       25.020614      121.535874             4    18         641       642
5       25.020679      121.535873             5    17         643       648
6       25.021243      121.535657             6    18         650       651
7       25.021253      121.535540             7    17         652       666
8       25.022141      121.534675             8    22         668       668
9       25.022142      121.534675             9    18           0         0
10      25.022234      121.534675            10    17         670       842
11            NaN             NaN            11     5           1       240
12            NaN             NaN            12     3         241       636
13            NaN             NaN            13     6         637       844

    totalExerciseReps                                       measurements  \
0                   0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
1                   0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
2                   0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
3                   0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
4                   0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
5                   0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
6                   0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
7                   0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
8                   0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
9                   0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
10                  0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
11                  0  [{'field': {'id': 121, 'key': 'endTimestamp', ...
12                  0  [{'field': {'id': 121, 'key': 'endTimestamp', ...
13                  0  [{'field': {'id': 121, 'key': 'endTimestamp', ...

                                           lapIndexes  MAX_HEARTRATE__BPM  \
0                                                 NaN                82.0
1                                                 NaN                 NaN
2                                                 NaN                 NaN
3                                                 NaN                 NaN
4                                                 NaN                 NaN
5                                                 NaN                 NaN
6                                                 NaN                 NaN
7                                                 NaN                 NaN
8                                                 NaN                 NaN
9                                                 NaN                 NaN
10                                                NaN                 NaN
11                                          [1, 2, 3]                 NaN
12  [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,...                 NaN
13                                       [28, 29, 30]                 NaN

    WEIGHTED_MEAN_HEARTRATE__BPM  SUM_BMR_ENERGY__KILOJOULE  \
0                           80.0                        0.0
1                            NaN                        NaN
2                            NaN                        NaN
3                            NaN                        NaN
4                            NaN                        NaN
5                            NaN                        NaN
6                            NaN                        NaN
7                            NaN                        NaN
8                            NaN                        NaN
9                            NaN                        NaN
10                           NaN                        NaN
11                           NaN                        NaN
12                           NaN                        NaN
13                           NaN                        NaN

    MAX_DOUBLE_CADENCE__BPM  \
0                       0.0
1                       NaN
2                       NaN
3                       NaN
4                       NaN
5                       NaN
6                       NaN
7                       NaN
8                       NaN
9                       NaN
10                      NaN
11                      NaN
12                      NaN
13                      NaN

    WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND  \
0                                                 0.0
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN

    SUM_DISTANCE__CENTIMETER  MAX_RUNCADENCE__BPM  \
0                     1153.0                  0.0
1                        NaN                  NaN
2                        NaN                  NaN
3                        NaN                  NaN
4                        NaN                  NaN
5                        NaN                  NaN
6                        NaN                  NaN
7                        NaN                  NaN
8                        NaN                  NaN
9                        NaN                  NaN
10                       NaN                  NaN
11                       NaN                  NaN
12                       NaN                  NaN
13                       NaN                  NaN

    MAX_SPEED__CENTIMETERS_PER_MILLISECOND  WEIGHTED_MEAN_RUNCADENCE__BPM  \
0                                   0.1493                            0.0
1                                      NaN                            NaN
2                                      NaN                            NaN
3                                      NaN                            NaN
4                                      NaN                            NaN
5                                      NaN                            NaN
6                                      NaN                            NaN
7                                      NaN                            NaN
8                                      NaN                            NaN
9                                      NaN                            NaN
10                                     NaN                            NaN
11                                     NaN                            NaN
12                                     NaN                            NaN
13                                     NaN                            NaN

    LOSS_ELEVATION__CENTIMETER  SUM_ENERGY__KILOJOULE  \
0                        237.0                    0.0
1                          NaN                    NaN
2                          NaN                    NaN
3                          NaN                    NaN
4                          NaN                    NaN
5                          NaN                    NaN
6                          NaN                    NaN
7                          NaN                    NaN
8                          NaN                    NaN
9                          NaN                    NaN
10                         NaN                    NaN
11                         NaN                    NaN
12                         NaN                    NaN
13                         NaN                    NaN

    WEIGHTED_MEAN_DOUBLE_CADENCE__BPM  \
0                                 0.0
1                                 NaN
2                                 NaN
3                                 NaN
4                                 NaN
5                                 NaN
6                                 NaN
7                                 NaN
8                                 NaN
9                                 NaN
10                                NaN
11                                NaN
12                                NaN
13                                NaN

    WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND  \
0                                             0.1647
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN
5                                                NaN
6                                                NaN
7                                                NaN
8                                                NaN
9                                                NaN
10                                               NaN
11                                               NaN
12                                               NaN
13                                               NaN

    GAIN_ELEVATION__CENTIMETER  SUM_ELAPSEDDURATION__MILLISECOND  \
0                          0.0                            7001.0
1                          NaN                               NaN
2                          NaN                               NaN
3                          NaN                               NaN
4                          NaN                               NaN
5                          NaN                               NaN
6                          NaN                               NaN
7                          NaN                               NaN
8                          NaN                               NaN
9                          NaN                               NaN
10                         NaN                               NaN
11                         NaN                               NaN
12                         NaN                               NaN
13                         NaN                               NaN

    SUM_DURATION__MILLISECOND  \
0                      7001.0
1                         NaN
2                         NaN
3                         NaN
4                         NaN
5                         NaN
6                         NaN
7                         NaN
8                         NaN
9                         NaN
10                        NaN
11                        NaN
12                        NaN
13                        NaN

    WEIGHTED_MEAN_ELAPSED_DURATION_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND  \
0                                            0.001569
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN

    SUM_MOVINGDURATION__MILLISECOND  \
0                            1000.0
1                               NaN
2                               NaN
3                               NaN
4                               NaN
5                               NaN
6                               NaN
7                               NaN
8                               NaN
9                               NaN
10                              NaN
11                              NaN
12                              NaN
13                              NaN

    WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND
0                                               1.153
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
    startTimeSource  endTimeSource   startTimeGMT     endTimeGMT  \
0                 0              0  1681466498000  1681466503000
1                 0              0  1681466504000  1681466632000
2                 0              0  1681466665000  1681466670000
3                 0              0  1681466671000  1681468719000
4                 0              0  1681468846000  1681468848000
5                 0              0  1681468849000  1681468877000
6                 0              0  1681468936000  1681468939000
7                 0              0  1681468940000  1681469003000
8                 0              0  1681469097000  1681469098000
9                 0              0  1681469099000  1681469102000
10                0              0  1681469103000  1681469876000
11                0              0  1681466498000  1681467435850
12                0              0  1681467436000  1681468696000
13                0              0  1681468696000  1681469877182

    startLatitude  startLongitude  messageIndex  type  startIndex  endIndex  \
0       25.035366      121.531597             0    22           0         2
1       25.035256      121.531557             1    17           3        41
2       25.033510      121.533294             2    22          43        44
3       25.033513      121.533409             3    17          46       639
4       25.020614      121.535874             4    18         641       642
5       25.020679      121.535873             5    17         643       648
6       25.021243      121.535657             6    18         650       651
7       25.021253      121.535540             7    17         652       666
8       25.022141      121.534675             8    22         668       668
9       25.022142      121.534675             9    18           0         0
10      25.022234      121.534675            10    17         670       842
11            NaN             NaN            11     5           1       240
12            NaN             NaN            12     3         241       636
13            NaN             NaN            13     6         637       844

    totalExerciseReps                                       measurements  \
0                   0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
1                   0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
2                   0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
3                   0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
4                   0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
5                   0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
6                   0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
7                   0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
8                   0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
9                   0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
10                  0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
11                  0  [{'field': {'id': 121, 'key': 'endTimestamp', ...
12                  0  [{'field': {'id': 121, 'key': 'endTimestamp', ...
13                  0  [{'field': {'id': 121, 'key': 'endTimestamp', ...

                                           lapIndexes  MAX_HEARTRATE__BPM_x  \
0                                                 NaN                  82.0
1                                                 NaN                   NaN
2                                                 NaN                   NaN
3                                                 NaN                   NaN
4                                                 NaN                   NaN
5                                                 NaN                   NaN
6                                                 NaN                   NaN
7                                                 NaN                   NaN
8                                                 NaN                   NaN
9                                                 NaN                   NaN
10                                                NaN                   NaN
11                                          [1, 2, 3]                   NaN
12  [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,...                   NaN
13                                       [28, 29, 30]                   NaN

    WEIGHTED_MEAN_HEARTRATE__BPM_x  SUM_BMR_ENERGY__KILOJOULE_x  \
0                             80.0                          0.0
1                              NaN                          NaN
2                              NaN                          NaN
3                              NaN                          NaN
4                              NaN                          NaN
5                              NaN                          NaN
6                              NaN                          NaN
7                              NaN                          NaN
8                              NaN                          NaN
9                              NaN                          NaN
10                             NaN                          NaN
11                             NaN                          NaN
12                             NaN                          NaN
13                             NaN                          NaN

    MAX_DOUBLE_CADENCE__BPM_x  \
0                         0.0
1                         NaN
2                         NaN
3                         NaN
4                         NaN
5                         NaN
6                         NaN
7                         NaN
8                         NaN
9                         NaN
10                        NaN
11                        NaN
12                        NaN
13                        NaN


/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/145449955.py:12: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_ELAPSED_DURATION_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'SUM_MOVINGDURATION__MILLISECOND_x', 'SUM_BMR_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'SUM_ENERGY__KILOJOULE_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/145449955.py:12: FutureWarning: Passing 'suffixes' which cause duplicate columns {'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/145449955.py:12: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_ELAPSED_DURATION_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'SUM_MOVINGDURATION__MILLISECOND_x', 'SUM_BMR_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'SUM_ENERGY__KILOJOULE_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\

    startTimeSource  endTimeSource   startTimeGMT     endTimeGMT  \
0                 0              0  1681466498000  1681466503000
1                 0              0  1681466504000  1681466632000
2                 0              0  1681466665000  1681466670000
3                 0              0  1681466671000  1681468719000
4                 0              0  1681468846000  1681468848000
5                 0              0  1681468849000  1681468877000
6                 0              0  1681468936000  1681468939000
7                 0              0  1681468940000  1681469003000
8                 0              0  1681469097000  1681469098000
9                 0              0  1681469099000  1681469102000
10                0              0  1681469103000  1681469876000
11                0              0  1681466498000  1681467435850
12                0              0  1681467436000  1681468696000
13                0              0  1681468696000  1681469877182

    startLatitude  startLongitude  messageIndex  type  startIndex  endIndex  \
0       25.035366      121.531597             0    22           0         2
1       25.035256      121.531557             1    17           3        41
2       25.033510      121.533294             2    22          43        44
3       25.033513      121.533409             3    17          46       639
4       25.020614      121.535874             4    18         641       642
5       25.020679      121.535873             5    17         643       648
6       25.021243      121.535657             6    18         650       651
7       25.021253      121.535540             7    17         652       666
8       25.022141      121.534675             8    22         668       668
9       25.022142      121.534675             9    18           0         0
10      25.022234      121.534675            10    17         670       842
11            NaN             NaN            11     5           1       240
12            NaN             NaN            12     3         241       636
13            NaN             NaN            13     6         637       844

    totalExerciseReps                                       measurements  \
0                   0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
1                   0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
2                   0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
3                   0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
4                   0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
5                   0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
6                   0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
7                   0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
8                   0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
9                   0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
10                  0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
11                  0  [{'field': {'id': 121, 'key': 'endTimestamp', ...
12                  0  [{'field': {'id': 121, 'key': 'endTimestamp', ...
13                  0  [{'field': {'id': 121, 'key': 'endTimestamp', ...

                                           lapIndexes  MAX_HEARTRATE__BPM_x  \
0                                                 NaN                  82.0
1                                                 NaN                   NaN
2                                                 NaN                   NaN
3                                                 NaN                   NaN
4                                                 NaN                   NaN
5                                                 NaN                   NaN
6                                                 NaN                   NaN
7                                                 NaN                   NaN
8                                                 NaN                   NaN
9                                                 NaN                   NaN
10                                                NaN                   NaN
11                                          [1, 2, 3]                   NaN
12  [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,...                   NaN
13                                       [28, 29, 30]                   NaN

    WEIGHTED_MEAN_HEARTRATE__BPM_x  SUM_BMR_ENERGY__KILOJOULE_x  \
0                             80.0                          0.0
1                              NaN                          NaN
2                              NaN                          NaN
3                              NaN                          NaN
4                              NaN                          NaN
5                              NaN                          NaN
6                              NaN                          NaN
7                              NaN                          NaN
8                              NaN                          NaN
9                              NaN                          NaN
10                             NaN                          NaN
11                             NaN                          NaN
12                             NaN                          NaN
13                             NaN                          NaN

    MAX_DOUBLE_CADENCE__BPM_x  \
0                         0.0
1                         NaN
2                         NaN
3                         NaN
4                         NaN
5                         NaN
6                         NaN
7                         NaN
8                         NaN
9                         NaN
10                        NaN
11                        NaN
12                        NaN
13                        NaN

    WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x  \
0                                                 0.0
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN

    SUM_DISTANCE__CENTIMETER_x  MAX_RUNCADENCE__BPM_x  \
0                       1153.0                    0.0
1                          NaN                    NaN
2                          NaN                    NaN
3                          NaN                    NaN
4                          NaN                    NaN
5                          NaN                    NaN
6                          NaN                    NaN
7                          NaN                    NaN
8                          NaN                    NaN
9                          NaN                    NaN
10                         NaN                    NaN
11                         NaN                    NaN
12                         NaN                    NaN
13                         NaN                    NaN

    MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x  WEIGHTED_MEAN_RUNCADENCE__BPM_x  \
0                                     0.1493                              0.0
1                                        NaN                              NaN
2                                        NaN                              NaN
3                                        NaN                              NaN
4                                        NaN                              NaN
5                                        NaN                              NaN
6                                        NaN                              NaN
7                                        NaN                              NaN
8                                        NaN                              NaN
9                                        NaN                              NaN
10                                       NaN                              NaN
11                                       NaN                              NaN
12                                       NaN                              NaN
13                                       NaN                              NaN

    LOSS_ELEVATION__CENTIMETER_x  SUM_ENERGY__KILOJOULE_x  \
0                          237.0                      0.0
1                            NaN                      NaN
2                            NaN                      NaN
3                            NaN                      NaN
4                            NaN                      NaN
5                            NaN                      NaN
6                            NaN                      NaN
7                            NaN                      NaN
8                            NaN                      NaN
9                            NaN                      NaN
10                           NaN                      NaN
11                           NaN                      NaN
12                           NaN                      NaN
13                           NaN                      NaN

    WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x  \
0                                   0.0
1                                   NaN
2                                   NaN
3                                   NaN
4                                   NaN
5                                   NaN
6                                   NaN
7                                   NaN
8                                   NaN
9                                   NaN
10                                  NaN
11                                  NaN
12                                  NaN
13                                  NaN

    WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x  \
0                                              0.1647
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN

    GAIN_ELEVATION__CENTIMETER_x  SUM_ELAPSEDDURATION__MILLISECOND_x  \
0                            0.0                              7001.0
1                            NaN                                 NaN
2                            NaN                                 NaN
3                            NaN                                 NaN
4                            NaN                                 NaN
5                            NaN                                 NaN
6                            NaN                                 NaN
7                            NaN                                 NaN
8                            NaN                                 NaN
9                            NaN                                 NaN
10                           NaN                                 NaN
11                           NaN                                 NaN
12                           NaN                                 NaN
13                           NaN                                 NaN

    SUM_DURATION__MILLISECOND_x  \
0                        7001.0
1                           NaN
2                           NaN
3                           NaN
4                           NaN
5                           NaN
6                           NaN
7                           NaN
8                           NaN
9                           NaN
10                          NaN
11                          NaN
12                          NaN
13                          NaN

    WEIGHTED_MEAN_ELAPSED_DURATION_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x  \
0                                            0.001569
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN

    SUM_MOVINGDURATION__MILLISECOND_x  \
0                              1000.0
1                                 NaN
2                                 NaN
3                                 NaN
4                                 NaN
5                                 NaN
6                                 NaN
7                                 NaN
8                                 NaN
9                                 NaN
10                                NaN
11                                NaN
12                                NaN
13                                NaN

    WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x  \
0                                               1.153
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN

    MAX_HEARTRATE__BPM_y  WEIGHTED_MEAN_HEARTRATE__BPM_y  \
0                    NaN                             NaN
1                  144.0                           125.0
2                    NaN                             NaN
3                    NaN                             NaN
4                    NaN                             NaN
5                    NaN                             NaN
6                    NaN                             NaN
7                    NaN                             NaN
8                    NaN                             NaN
9                    NaN                             NaN
10                   NaN                             NaN
11                   NaN                             NaN
12                   NaN                             NaN
13                   NaN                             NaN

    SUM_BMR_ENERGY__KILOJOULE_y  MAX_DOUBLE_CADENCE__BPM_y  \
0                           NaN                        NaN
1                      12.57006                      165.0
2                           NaN                        NaN
3                           NaN                        NaN
4                           NaN                        NaN
5                           NaN                        NaN
6                           NaN                        NaN
7                           NaN                        NaN
8                           NaN                        NaN
9                           NaN                        NaN
10                          NaN                        NaN
11                          NaN                        NaN
12                          NaN                        NaN
13                          NaN                        NaN

    WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_y  \
0                                                 NaN
1                                              0.0032
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN

    SUM_DISTANCE__CENTIMETER_y  MAX_RUNCADENCE__BPM_y  \
0                          NaN                    NaN
1                      36644.0                   83.0
2                          NaN                    NaN
3                          NaN                    NaN
4                          NaN                    NaN
5                          NaN                    NaN
6                          NaN                    NaN
7                          NaN                    NaN
8                          NaN                    NaN
9                          NaN                    NaN
10                         NaN                    NaN
11                         NaN                    NaN
12                         NaN                    NaN
13                         NaN                    NaN

    MAX_SPEED__CENTIMETERS_PER_MILLISECOND_y  WEIGHTED_MEAN_RUNCADENCE__BPM_y  \
0                                        NaN                              NaN
1                                     0.3816                             75.0
2                                        NaN                              NaN
3                                        NaN                              NaN
4                                        NaN                              NaN
5                                        NaN                              NaN
6                                        NaN                              NaN
7                                        NaN                              NaN
8                                        NaN                              NaN
9                                        NaN                              NaN
10                                       NaN                              NaN
11                                       NaN                              NaN
12                                       NaN                              NaN
13                                       NaN                              NaN

    LOSS_ELEVATION__CENTIMETER_y  SUM_ENERGY__KILOJOULE_y  \
0                            NaN                      NaN
1                         1415.0                113.13054
2                            NaN                      NaN
3                            NaN                      NaN
4                            NaN                      NaN
5                            NaN                      NaN
6                            NaN                      NaN
7                            NaN                      NaN
8                            NaN                      NaN
9                            NaN                      NaN
10                           NaN                      NaN
11                           NaN                      NaN

/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/145449955.py:12: FutureWarning: Passing 'suffixes' which cause duplicate columns {'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/145449955.py:12: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_ELAPSED_DURATION_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'SUM_MOVINGDURATION__MILLISECOND_x', 'SUM_BMR_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'SUM_ENERGY__KILOJOULE_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/145449955.py:12: FutureWarning: Passing 'suffixes' which cause duplicate columns {'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\

    startTimeSource  endTimeSource   startTimeGMT     endTimeGMT  \
0                 0              0  1681466498000  1681466503000
1                 0              0  1681466504000  1681466632000
2                 0              0  1681466665000  1681466670000
3                 0              0  1681466671000  1681468719000
4                 0              0  1681468846000  1681468848000
5                 0              0  1681468849000  1681468877000
6                 0              0  1681468936000  1681468939000
7                 0              0  1681468940000  1681469003000
8                 0              0  1681469097000  1681469098000
9                 0              0  1681469099000  1681469102000
10                0              0  1681469103000  1681469876000
11                0              0  1681466498000  1681467435850
12                0              0  1681467436000  1681468696000
13                0              0  1681468696000  1681469877182

    startLatitude  startLongitude  messageIndex  type  startIndex  endIndex  \
0       25.035366      121.531597             0    22           0         2
1       25.035256      121.531557             1    17           3        41
2       25.033510      121.533294             2    22          43        44
3       25.033513      121.533409             3    17          46       639
4       25.020614      121.535874             4    18         641       642
5       25.020679      121.535873             5    17         643       648
6       25.021243      121.535657             6    18         650       651
7       25.021253      121.535540             7    17         652       666
8       25.022141      121.534675             8    22         668       668
9       25.022142      121.534675             9    18           0         0
10      25.022234      121.534675            10    17         670       842
11            NaN             NaN            11     5           1       240
12            NaN             NaN            12     3         241       636
13            NaN             NaN            13     6         637       844

    totalExerciseReps                                       measurements  \
0                   0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
1                   0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
2                   0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
3                   0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
4                   0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
5                   0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
6                   0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
7                   0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
8                   0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
9                   0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
10                  0  [{'field': {'id': 108, 'key': 'maxHeartRate', ...
11                  0  [{'field': {'id': 121, 'key': 'endTimestamp', ...
12                  0  [{'field': {'id': 121, 'key': 'endTimestamp', ...
13                  0  [{'field': {'id': 121, 'key': 'endTimestamp', ...

                                           lapIndexes  MAX_HEARTRATE__BPM_x  \
0                                                 NaN                  82.0
1                                                 NaN                   NaN
2                                                 NaN                   NaN
3                                                 NaN                   NaN
4                                                 NaN                   NaN
5                                                 NaN                   NaN
6                                                 NaN                   NaN
7                                                 NaN                   NaN
8                                                 NaN                   NaN
9                                                 NaN                   NaN
10                                                NaN                   NaN
11                                          [1, 2, 3]                   NaN
12  [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,...                   NaN
13                                       [28, 29, 30]                   NaN

    WEIGHTED_MEAN_HEARTRATE__BPM_x  SUM_BMR_ENERGY__KILOJOULE_x  \
0                             80.0                          0.0
1                              NaN                          NaN
2                              NaN                          NaN
3                              NaN                          NaN
4                              NaN                          NaN
5                              NaN                          NaN
6                              NaN                          NaN
7                              NaN                          NaN
8                              NaN                          NaN
9                              NaN                          NaN
10                             NaN                          NaN
11                             NaN                          NaN
12                             NaN                          NaN
13                             NaN                          NaN

    MAX_DOUBLE_CADENCE__BPM_x  \
0                         0.0
1                         NaN
2                         NaN
3                         NaN
4                         NaN
5                         NaN
6                         NaN
7                         NaN
8                         NaN
9                         NaN
10                        NaN
11                        NaN
12                        NaN
13                        NaN

    WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x  \
0                                                 0.0
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN

    SUM_DISTANCE__CENTIMETER_x  MAX_RUNCADENCE__BPM_x  \
0                       1153.0                    0.0
1                          NaN                    NaN
2                          NaN                    NaN
3                          NaN                    NaN
4                          NaN                    NaN
5                          NaN                    NaN
6                          NaN                    NaN
7                          NaN                    NaN
8                          NaN                    NaN
9                          NaN                    NaN
10                         NaN                    NaN
11                         NaN                    NaN
12                         NaN                    NaN
13                         NaN                    NaN

    MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x  WEIGHTED_MEAN_RUNCADENCE__BPM_x  \
0                                     0.1493                              0.0
1                                        NaN                              NaN
2                                        NaN                              NaN
3                                        NaN                              NaN
4                                        NaN                              NaN
5                                        NaN                              NaN
6                                        NaN                              NaN
7                                        NaN                              NaN
8                                        NaN                              NaN
9                                        NaN                              NaN
10                                       NaN                              NaN
11                                       NaN                              NaN
12                                       NaN                              NaN
13                                       NaN                              NaN

    LOSS_ELEVATION__CENTIMETER_x  SUM_ENERGY__KILOJOULE_x  \
0                          237.0                      0.0
1                            NaN                      NaN
2                            NaN                      NaN
3                            NaN                      NaN
4                            NaN                      NaN
5                            NaN                      NaN
6                            NaN                      NaN
7                            NaN                      NaN
8                            NaN                      NaN
9                            NaN                      NaN
10                           NaN                      NaN
11                           NaN                      NaN
12                           NaN                      NaN
13                           NaN                      NaN

    WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x  \
0                                   0.0
1                                   NaN
2                                   NaN
3                                   NaN
4                                   NaN
5                                   NaN
6                                   NaN
7                                   NaN
8                                   NaN
9                                   NaN
10                                  NaN
11                                  NaN
12                                  NaN
13                                  NaN

    WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x  \
0                                              0.1647
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN

    GAIN_ELEVATION__CENTIMETER_x  SUM_ELAPSEDDURATION__MILLISECOND_x  \
0                            0.0                              7001.0
1                            NaN                                 NaN
2                            NaN                                 NaN
3                            NaN                                 NaN
4                            NaN                                 NaN
5                            NaN                                 NaN
6                            NaN                                 NaN
7                            NaN                                 NaN
8                            NaN                                 NaN
9                            NaN                                 NaN
10                           NaN                                 NaN
11                           NaN                                 NaN
12                           NaN                                 NaN
13                           NaN                                 NaN

    SUM_DURATION__MILLISECOND_x  \
0                        7001.0
1                           NaN
2                           NaN
3                           NaN
4                           NaN
5                           NaN
6                           NaN
7                           NaN
8                           NaN
9                           NaN
10                          NaN
11                          NaN
12                          NaN
13                          NaN

    WEIGHTED_MEAN_ELAPSED_DURATION_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x  \
0                                            0.001569
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN

    SUM_MOVINGDURATION__MILLISECOND_x  \
0                              1000.0
1                                 NaN
2                                 NaN
3                                 NaN
4                                 NaN
5                                 NaN
6                                 NaN
7                                 NaN
8                                 NaN
9                                 NaN
10                                NaN
11                                NaN
12                                NaN
13                                NaN

    WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x  \
0                                               1.153
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN

    MAX_HEARTRATE__BPM_y  WEIGHTED_MEAN_HEARTRATE__BPM_y  \
0                    NaN                             NaN
1                  144.0                           125.0
2                    NaN                             NaN
3                    NaN                             NaN
4                    NaN                             NaN
5                    NaN                             NaN
6                    NaN                             NaN
7                    NaN                             NaN
8                    NaN                             NaN
9                    NaN                             NaN
10                   NaN                             NaN
11                   NaN                             NaN
12                   NaN                             NaN
13                   NaN                             NaN

    SUM_BMR_ENERGY__KILOJOULE_y  MAX_DOUBLE_CADENCE__BPM_y  \
0                           NaN                        NaN
1                      12.57006                      165.0
2                           NaN                        NaN
3                           NaN                        NaN
4                           NaN                        NaN
5                           NaN                        NaN
6                           NaN                        NaN
7                           NaN                        NaN
8                           NaN                        NaN
9                           NaN                        NaN
10                          NaN                        NaN
11                          NaN                        NaN
12                          NaN                        NaN
13                          NaN                        NaN

    WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_y  \
0                                                 NaN
1                                              0.0032
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN

    SUM_DISTANCE__CENTIMETER_y  MAX_RUNCADENCE__BPM_y  \
0                          NaN                    NaN
1                      36644.0                   83.0
2                          NaN                    NaN
3                          NaN                    NaN
4                          NaN                    NaN
5                          NaN                    NaN
6                          NaN                    NaN
7                          NaN                    NaN
8                          NaN                    NaN
9                          NaN                    NaN
10                         NaN                    NaN
11                         NaN                    NaN
12                         NaN                    NaN
13                         NaN                    NaN

    MAX_SPEED__CENTIMETERS_PER_MILLISECOND_y  WEIGHTED_MEAN_RUNCADENCE__BPM_y  \
0                                        NaN                              NaN
1                                     0.3816                             75.0
2                                        NaN                              NaN
3                                        NaN                              NaN
4                                        NaN                              NaN
5                                        NaN                              NaN
6                                        NaN                              NaN
7                                        NaN                              NaN
8                                        NaN                              NaN
9                                        NaN                              NaN
10                                       NaN                              NaN
11                                       NaN                              NaN
12                                       NaN                              NaN
13                                       NaN                              NaN

    LOSS_ELEVATION__CENTIMETER_y  SUM_ENERGY__KILOJOULE_y  \
0                            NaN                      NaN
1                         1415.0                113.13054
2                            NaN                      NaN
3                            NaN                      NaN
4                            NaN                      NaN
5                            NaN                      NaN
6                            NaN                      NaN
7                            NaN                      NaN
8                            NaN                      NaN
9                            NaN                      NaN
10                           NaN                      NaN
11                           NaN                      NaN

/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/145449955.py:12: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_ELAPSED_DURATION_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'SUM_MOVINGDURATION__MILLISECOND_x', 'SUM_BMR_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'SUM_ENERGY__KILOJOULE_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/145449955.py:12: FutureWarning: Passing 'suffixes' which cause duplicate columns {'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/145449955.py:12: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_ELAPSED_DURATION_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'SUM_MOVINGDURATION__MILLISECOND_x', 'SUM_BMR_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'SUM_ENERGY__KILOJOULE_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [ ]:
activity_splits_full = pd.DataFrame(overall_df.loc[0].splits)
for index, row in overall_df.iterrows():
    if row['activityType'] != 'running':
        continue
    activity_splits = pd.DataFrame(row['splits'])
    print(activity_splits.shape)
    for index2, row in activity_splits.iterrows():
        #print(index)
        #print(row['startTimeGMT'])
        #print(pd.json_normalize(activity_splits.measurements[index]))
        #print(20*"\n")
        dict_measurements = {}
        split_measurements = pd.json_normalize(activity_splits.measurements[index2])
        for _, row in split_measurements.iterrows():
            dict_measurements[f"{row['fieldEnum']}__{row['unitEnum']}"] = row['value']
        #print(dict_measurements)
        split_measurements_df = pd.DataFrame(dict_measurements, index = [index2])
        activity_splits = pd.merge(activity_splits, split_measurements_df,\
                                   left_index = True, right_index = True, how = "outer")
activity_splits

(18, 13)
(14, 13)
(6, 13)
(16, 13)
(22, 13)
(7, 13)

/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_ELAPSED_DURATION_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'SUM_MOVINGDURATION__MILLISECOND_x', 'SUM_BMR_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'SUM_ENERGY__KILOJOULE_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x', 'LOSS_ELEVATION__CENTIMETER_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_ELAPSED_DURATION_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'SUM_MOVINGDURATION__MILLISECOND_x', 'SUM_BMR_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'SUM_ENERGY__KILOJOULE_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x', 'LOSS_ELEVATION__CENTIMETER_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'SUM_ENERGY__KILOJOULE_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_DISTANCE__CENTIMETER_x', 'SUM_DURATION__MILLISECOND_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'MAX_RUNCADENCE__BPM_x', 'WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x', 'SUM_MOVINGDURATION__MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x', 'SUM_BMR_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'SUM_ENERGY__KILOJOULE_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'MAX_RUNCADENCE__BPM_x', 'SUM_DISTANCE__CENTIMETER_x', 'SUM_DURATION__MILLISECOND_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x', 'SUM_MOVINGDURATION__MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'MIN_ELEVATION__CENTIMETER_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'MAX_UNCORRECTED_ELEVATION__CENTIMETER_x', 'MAX_HEARTRATE__BPM_x', 'MIN_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_CORRECTED_ELEVATION__CENTIMETER_x', 'END_TIMESTAMP__GMT_x', 'LOSS_UNCORRECTED_ELEVATION__CENTIMETER_x', 'GAIN_UNCORRECTED_ELEVATION__CENTIMETER_x', 'END_LONGITUDE__DECIMAL_DEGREE_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'MAX_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MIN_HEARTRATE__BPM_x', 'MIN_RUNCADENCE__BPM_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'WEIGHTED_MEAN_FRACTIONAL_CADENCE__BPM_x', 'SUM_MOVINGDURATION__MILLISECOND_x', 'MAX_FRACTIONAL_CADENCE__BPM_x', 'MIN_CORRECTED_ELEVATION__CENTIMETER_x', 'SUM_STEP__STEP_x', 'MAX_ELEVATION__CENTIMETER_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'SUM_ENERGY__KILOJOULE_x', 'END_LATITUDE__DECIMAL_DEGREE_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x', 'MIN_ACTIVITY_LAP_DURATION__MILLISECOND_x', 'MIN_UNCORRECTED_ELEVATION__CENTIMETER_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'SUM_ENERGY__KILOJOULE_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'SUM_MOVINGDURATION__MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x', 'SUM_BMR_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'SUM_ENERGY__KILOJOULE_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x', 'SUM_MOVINGDURATION__MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x', 'SUM_BMR_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'SUM_ENERGY__KILOJOULE_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x', 'SUM_BMR_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x', 'WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_ELAPSED_DURATION_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'SUM_ENERGY__KILOJOULE_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'SUM_MOVINGDURATION__MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x', 'WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'SUM_ENERGY__KILOJOULE_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'MAX_RUNCADENCE__BPM_x', 'SUM_DISTANCE__CENTIMETER_x', 'SUM_DURATION__MILLISECOND_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'SUM_MOVINGDURATION__MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'SUM_ENERGY__KILOJOULE_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_RUNCADENCE__BPM_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'SUM_DISTANCE__CENTIMETER_x', 'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x', 'SUM_MOVINGDURATION__MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'SUM_ENERGY__KILOJOULE_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x', 'SUM_BMR_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'SUM_ENERGY__KILOJOULE_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'SUM_MOVINGDURATION__MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x', 'SUM_BMR_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_ELAPSED_DURATION_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'SUM_MOVINGDURATION__MILLISECOND_x', 'SUM_BMR_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'SUM_ENERGY__KILOJOULE_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'SUM_ENERGY__KILOJOULE_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x', 'WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'MAX_HEARTRATE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x', 'SUM_BMR_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_ELAPSED_DURATION_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_MOVINGDURATION__MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'SUM_ENERGY__KILOJOULE_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x', 'MAX_HEARTRATE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_MOVINGDURATION__MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'SUM_ENERGY__KILOJOULE_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'MAX_RUNCADENCE__BPM_x', 'SUM_DISTANCE__CENTIMETER_x', 'SUM_DURATION__MILLISECOND_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x', 'MAX_HEARTRATE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_ENERGY__KILOJOULE_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'MAX_RUNCADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'SUM_DISTANCE__CENTIMETER_x', 'WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x', 'SUM_BMR_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\

(7, 13)
(24, 13)
(9, 13)
(8, 13)
(18, 13)
(10, 13)
(12, 13)

/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'SUM_ENERGY__KILOJOULE_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'MAX_RUNCADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x', 'WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_MOVINGDURATION__MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'MIN_ELEVATION__CENTIMETER_x', 'MAX_UNCORRECTED_ELEVATION__CENTIMETER_x', 'MIN_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_CORRECTED_ELEVATION__CENTIMETER_x', 'END_TIMESTAMP__GMT_x', 'LOSS_UNCORRECTED_ELEVATION__CENTIMETER_x', 'GAIN_UNCORRECTED_ELEVATION__CENTIMETER_x', 'END_LONGITUDE__DECIMAL_DEGREE_x', 'MAX_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MIN_HEARTRATE__BPM_x', 'MIN_RUNCADENCE__BPM_x', 'WEIGHTED_MEAN_FRACTIONAL_CADENCE__BPM_x', 'MAX_FRACTIONAL_CADENCE__BPM_x', 'MIN_CORRECTED_ELEVATION__CENTIMETER_x', 'SUM_STEP__STEP_x', 'MAX_ELEVATION__CENTIMETER_x', 'END_LATITUDE__DECIMAL_DEGREE_x', 'MIN_ACTIVITY_LAP_DURATION__MILLISECOND_x', 'MIN_UNCORRECTED_ELEVATION__CENTIMETER_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'MIN_ELEVATION__CENTIMETER_x', 'MAX_UNCORRECTED_ELEVATION__CENTIMETER_x', 'MIN_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_CORRECTED_ELEVATION__CENTIMETER_x', 'END_TIMESTAMP__GMT_x', 'LOSS_UNCORRECTED_ELEVATION__CENTIMETER_x', 'GAIN_UNCORRECTED_ELEVATION__CENTIMETER_x', 'END_LONGITUDE__DECIMAL_DEGREE_x', 'MAX_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MIN_HEARTRATE__BPM_x', 'MIN_RUNCADENCE__BPM_x', 'WEIGHTED_MEAN_FRACTIONAL_CADENCE__BPM_x', 'MAX_FRACTIONAL_CADENCE__BPM_x', 'MIN_CORRECTED_ELEVATION__CENTIMETER_x', 'SUM_STEP__STEP_x', 'MAX_ELEVATION__CENTIMETER_x', 'END_LATITUDE__DECIMAL_DEGREE_x', 'LOSS_CORRECTED_ELEVATION__CENTIMETER_x', 'MIN_ACTIVITY_LAP_DURATION__MILLISECOND_x', 'MIN_UNCORRECTED_ELEVATION__CENTIMETER_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'SUM_ENERGY__KILOJOULE_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'MAX_RUNCADENCE__BPM_x', 'SUM_DISTANCE__CENTIMETER_x', 'SUM_DURATION__MILLISECOND_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x', 'WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_MOVINGDURATION__MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'GAIN_CORRECTED_ELEVATION__CENTIMETER_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'MIN_ELEVATION__CENTIMETER_x', 'MAX_UNCORRECTED_ELEVATION__CENTIMETER_x', 'MIN_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_CORRECTED_ELEVATION__CENTIMETER_x', 'END_TIMESTAMP__GMT_x', 'LOSS_UNCORRECTED_ELEVATION__CENTIMETER_x', 'GAIN_UNCORRECTED_ELEVATION__CENTIMETER_x', 'END_LONGITUDE__DECIMAL_DEGREE_x', 'MAX_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MIN_HEARTRATE__BPM_x', 'MIN_RUNCADENCE__BPM_x', 'WEIGHTED_MEAN_FRACTIONAL_CADENCE__BPM_x', 'MAX_FRACTIONAL_CADENCE__BPM_x', 'MIN_CORRECTED_ELEVATION__CENTIMETER_x', 'SUM_STEP__STEP_x', 'MAX_ELEVATION__CENTIMETER_x', 'END_LATITUDE__DECIMAL_DEGREE_x', 'MIN_ACTIVITY_LAP_DURATION__MILLISECOND_x', 'MIN_UNCORRECTED_ELEVATION__CENTIMETER_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'SUM_ENERGY__KILOJOULE_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'MAX_RUNCADENCE__BPM_x', 'SUM_DISTANCE__CENTIMETER_x', 'SUM_DURATION__MILLISECOND_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'LOSS_CORRECTED_ELEVATION__CENTIMETER_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x', 'WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_MOVINGDURATION__MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'MIN_ELEVATION__CENTIMETER_x', 'MAX_UNCORRECTED_ELEVATION__CENTIMETER_x', 'MIN_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_CORRECTED_ELEVATION__CENTIMETER_x', 'END_TIMESTAMP__GMT_x', 'LOSS_UNCORRECTED_ELEVATION__CENTIMETER_x', 'GAIN_UNCORRECTED_ELEVATION__CENTIMETER_x', 'END_LONGITUDE__DECIMAL_DEGREE_x', 'MAX_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MIN_HEARTRATE__BPM_x', 'GAIN_CORRECTED_ELEVATION__CENTIMETER_x', 'MIN_RUNCADENCE__BPM_x', 'WEIGHTED_MEAN_FRACTIONAL_CADENCE__BPM_x', 'MAX_FRACTIONAL_CADENCE__BPM_x', 'MIN_CORRECTED_ELEVATION__CENTIMETER_x', 'SUM_STEP__STEP_x', 'MAX_ELEVATION__CENTIMETER_x', 'END_LATITUDE__DECIMAL_DEGREE_x', 'MIN_ACTIVITY_LAP_DURATION__MILLISECOND_x', 'MIN_UNCORRECTED_ELEVATION__CENTIMETER_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'MIN_ELEVATION__CENTIMETER_x', 'MAX_UNCORRECTED_ELEVATION__CENTIMETER_x', 'MIN_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_CORRECTED_ELEVATION__CENTIMETER_x', 'END_TIMESTAMP__GMT_x', 'LOSS_UNCORRECTED_ELEVATION__CENTIMETER_x', 'GAIN_UNCORRECTED_ELEVATION__CENTIMETER_x', 'END_LONGITUDE__DECIMAL_DEGREE_x', 'MAX_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MIN_HEARTRATE__BPM_x', 'MIN_RUNCADENCE__BPM_x', 'WEIGHTED_MEAN_FRACTIONAL_CADENCE__BPM_x', 'MAX_FRACTIONAL_CADENCE__BPM_x', 'MIN_CORRECTED_ELEVATION__CENTIMETER_x', 'SUM_STEP__STEP_x', 'MAX_ELEVATION__CENTIMETER_x', 'END_LATITUDE__DECIMAL_DEGREE_x', 'LOSS_CORRECTED_ELEVATION__CENTIMETER_x', 'MIN_ACTIVITY_LAP_DURATION__MILLISECOND_x', 'LOSS_ELEVATION__CENTIMETER_x', 'MIN_UNCORRECTED_ELEVATION__CENTIMETER_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_ENERGY__KILOJOULE_x', 'SUM_DISTANCE__CENTIMETER_x', 'SUM_DURATION__MILLISECOND_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'MAX_RUNCADENCE__BPM_x', 'WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x', 'SUM_BMR_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_ELAPSED_DURATION_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'SUM_MOVINGDURATION__MILLISECOND_x', 'SUM_BMR_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'SUM_ENERGY__KILOJOULE_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'SUM_ENERGY__KILOJOULE_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_DURATION__MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x', 'SUM_BMR_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'SUM_ENERGY__KILOJOULE_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x', 'WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_MOVINGDURATION__MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'SUM_ENERGY__KILOJOULE_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'MAX_RUNCADENCE__BPM_x', 'SUM_DISTANCE__CENTIMETER_x', 'SUM_DURATION__MILLISECOND_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x', 'WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_MOVINGDURATION__MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_ENERGY__KILOJOULE_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'MAX_HEARTRATE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x', 'SUM_BMR_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_ENERGY__KILOJOULE_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'SUM_MOVINGDURATION__MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x', 'SUM_BMR_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_ELAPSED_DURATION_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'WEIGHTED_MEAN_ELAPSED_DURATION_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x', 'WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_MOVINGDURATION__MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_ENERGY__KILOJOULE_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'MAX_HEARTRATE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'SUM_ENERGY__KILOJOULE_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'MAX_RUNCADENCE__BPM_x', 'SUM_DISTANCE__CENTIMETER_x', 'SUM_DURATION__MILLISECOND_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'MAX_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'MAX_RUNCADENCE__BPM_x', 'SUM_DISTANCE__CENTIMETER_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_ENERGY__KILOJOULE_x', 'MAX_HEARTRATE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x', 'SUM_BMR_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x', 'WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_ELAPSED_DURATION_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_MOVINGDURATION__MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'MAX_RUNCADENCE__BPM_x', 'SUM_DISTANCE__CENTIMETER_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'SUM_ENERGY__KILOJOULE_x', 'MAX_HEARTRATE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x', 'WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_MOVINGDURATION__MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\

(7, 13)
(20, 13)
(20, 13)
(7, 13)
(21, 12)
(2, 12)
(5, 12)
(7, 12)

/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'WEIGHTED_MEAN_ELAPSED_DURATION_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_MOVINGDURATION__MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'SUM_ENERGY__KILOJOULE_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x', 'MAX_HEARTRATE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x', 'SUM_BMR_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'SUM_MOVINGDURATION__MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_ELAPSED_DURATION_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'SUM_BMR_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'SUM_ENERGY__KILOJOULE_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'SUM_ENERGY__KILOJOULE_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'SUM_MOVINGDURATION__MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x', 'SUM_BMR_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'SUM_ENERGY__KILOJOULE_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x', 'WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_MOVINGDURATION__MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'MIN_ELEVATION__CENTIMETER_x', 'MAX_UNCORRECTED_ELEVATION__CENTIMETER_x', 'MIN_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_CORRECTED_ELEVATION__CENTIMETER_x', 'END_TIMESTAMP__GMT_x', 'LOSS_UNCORRECTED_ELEVATION__CENTIMETER_x', 'GAIN_UNCORRECTED_ELEVATION__CENTIMETER_x', 'END_LONGITUDE__DECIMAL_DEGREE_x', 'MAX_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MIN_HEARTRATE__BPM_x', 'MIN_RUNCADENCE__BPM_x', 'WEIGHTED_MEAN_FRACTIONAL_CADENCE__BPM_x', 'MAX_FRACTIONAL_CADENCE__BPM_x', 'MIN_CORRECTED_ELEVATION__CENTIMETER_x', 'SUM_STEP__STEP_x', 'MAX_ELEVATION__CENTIMETER_x', 'END_LATITUDE__DECIMAL_DEGREE_x', 'MIN_ACTIVITY_LAP_DURATION__MILLISECOND_x', 'LOSS_ELEVATION__CENTIMETER_x', 'MIN_UNCORRECTED_ELEVATION__CENTIMETER_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'SUM_ENERGY__KILOJOULE_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'MAX_RUNCADENCE__BPM_x', 'SUM_DISTANCE__CENTIMETER_x', 'SUM_DURATION__MILLISECOND_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x', 'WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_MOVINGDURATION__MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'MIN_ELEVATION__CENTIMETER_x', 'MAX_UNCORRECTED_ELEVATION__CENTIMETER_x', 'MIN_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_CORRECTED_ELEVATION__CENTIMETER_x', 'END_TIMESTAMP__GMT_x', 'LOSS_UNCORRECTED_ELEVATION__CENTIMETER_x', 'GAIN_UNCORRECTED_ELEVATION__CENTIMETER_x', 'END_LONGITUDE__DECIMAL_DEGREE_x', 'MAX_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MIN_HEARTRATE__BPM_x', 'MIN_RUNCADENCE__BPM_x', 'WEIGHTED_MEAN_FRACTIONAL_CADENCE__BPM_x', 'MAX_FRACTIONAL_CADENCE__BPM_x', 'MIN_CORRECTED_ELEVATION__CENTIMETER_x', 'SUM_STEP__STEP_x', 'MAX_ELEVATION__CENTIMETER_x', 'END_LATITUDE__DECIMAL_DEGREE_x', 'MIN_ACTIVITY_LAP_DURATION__MILLISECOND_x', 'LOSS_ELEVATION__CENTIMETER_x', 'MIN_UNCORRECTED_ELEVATION__CENTIMETER_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'SUM_ENERGY__KILOJOULE_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'SUM_ENERGY__KILOJOULE_x', 'MAX_HEARTRATE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x', 'SUM_BMR_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'SUM_ENERGY__KILOJOULE_x', 'SUM_MOVINGDURATION__MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x', 'SUM_BMR_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'SUM_ELAPSEDDURATION__MILLISECOND_x', 'SUM_DURATION__MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'SUM_ENERGY__KILOJOULE_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'SUM_MOVINGDURATION__MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_ELAPSED_DURATION_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'LOSS_ELEVATION__CENTIMETER_x', 'SUM_BMR_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'SUM_DURATION__MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'SUM_ENERGY__KILOJOULE_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'MAX_HEARTRATE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x', 'SUM_BMR_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_ENERGY__KILOJOULE_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x', 'MAX_HEARTRATE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x', 'SUM_BMR_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'SUM_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'SUM_MOVINGDURATION__MILLISECOND_x', 'MAX_HEARTRATE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x', 'SUM_BMR_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x', 'WEIGHTED_MEAN_ELAPSED_DURATION_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'SUM_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'MAX_HEARTRATE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x', 'SUM_BMR_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_87419/4115229818.py:18: FutureWarning: Passing 'suffixes' which cause duplicate columns {'GAIN_ELEVATION__CENTIMETER_x', 'WEIGHTED_MEAN_RUNCADENCE__BPM_x', 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'SUM_ELAPSEDDURATION__MILLISECOND_x', 'SUM_DISTANCE__CENTIMETER_x', 'MAX_RUNCADENCE__BPM_x', 'SUM_DURATION__MILLISECOND_x', 'SUM_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_HEARTRATE__BPM_x', 'WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x', 'MAX_DOUBLE_CADENCE__BPM_x', 'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x', 'MAX_HEARTRATE__BPM_x', 'LOSS_ELEVATION__CENTIMETER_x', 'SUM_BMR_ENERGY__KILOJOULE_x', 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x'} in the result is deprecated and will raise a MergeError in a future version.
  activity_splits = pd.merge(activity_splits, split_measurements_df,\

(2, 12)
(2, 12)
(2, 12)
(4, 12)
(5, 12)
(5, 12)

,startTimeSource,endTimeSource,startTimeGMT,endTimeGMT,startLatitude,startLongitude,messageIndex,type,startIndex,endIndex,totalExerciseReps,measurements,WEIGHTED_MEAN_RUNCADENCE__BPM_x,MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x,SUM_BMR_ENERGY__KILOJOULE_x,WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x,MAX_RUNCADENCE__BPM_x,SUM_DISTANCE__CENTIMETER_x,SUM_DURATION__MILLISECOND_x,WEIGHTED_MEAN_HEARTRATE__BPM_x,LOSS_ELEVATION__CENTIMETER_x,MAX_HEARTRATE__BPM_x,SUM_ELAPSEDDURATION__MILLISECOND_x,GAIN_ELEVATION__CENTIMETER_x,WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x,SUM_ENERGY__KILOJOULE_x,MAX_DOUBLE_CADENCE__BPM_x,WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x,WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x,WEIGHTED_MEAN_RUNCADENCE__BPM_y,MAX_SPEED__CENTIMETERS_PER_MILLISECOND_y,SUM_BMR_ENERGY__KILOJOULE_y,WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_y,MAX_RUNCADENCE__BPM_y,SUM_DISTANCE__CENTIMETER_y,SUM_DURATION__MILLISECOND_y,WEIGHTED_MEAN_HEARTRATE__BPM_y,LOSS_ELEVATION__CENTIMETER_y,MAX_HEARTRATE__BPM_y,SUM_ELAPSEDDURATION__MILLISECOND_y,GAIN_ELEVATION__CENTIMETER_y,WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_y,SUM_ENERGY__KILOJOULE_y,MAX_DOUBLE_CADENCE__BPM_y,WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_y,WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_y,WEIGHTED_MEAN_ELAPSED_DURATION_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x,SUM_MOVINGDURATION__MILLISECOND_x,WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_x,WEIGHTED_MEAN_RUNCADENCE__BPM_x,MAX_SPEED__CENTIMETERS_PER_MILLISECOND_x,SUM_BMR_ENERGY__KILOJOULE_x,WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_x,MAX_RUNCADENCE__BPM_x,SUM_DISTANCE__CENTIMETER_x,SUM_DURATION__MILLISECOND_x,WEIGHTED_MEAN_HEARTRATE__BPM_x,LOSS_ELEVATION__CENTIMETER_x,MAX_HEARTRATE__BPM_x,SUM_ELAPSEDDURATION__MILLISECOND_x,GAIN_ELEVATION__CENTIMETER_x,WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_x,SUM_ENERGY__KILOJOULE_x,MAX_DOUBLE_CADENCE__BPM_x,WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_x,WEIGHTED_MEAN_RUNCADENCE__BPM_y,MAX_SPEED__CENTIMETERS_PER_MILLISECOND_y,SUM_BMR_ENERGY__KILOJOULE_y,WEIGHTED_MEAN_DOUBLE_CADENCE__BPM_y,MAX_RUNCADENCE__BPM_y,SUM_DISTANCE__CENTIMETER_y,SUM_DURATION__MILLISECOND_y,WEIGHTED_MEAN_HEARTRATE__BPM_y,LOSS_ELEVATION__CENTIMETER_y,MAX_HEARTRATE__BPM_y,SUM_ELAPSEDDURATION__MILLISECOND_y,GAIN_ELEVATION__CENTIMETER_y,WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_y,SUM_ENERGY__KILOJOULE_y,MAX_DOUBLE_CADENCE__BPM_y,WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND_y,WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_x,WEIGHTED_MEAN_RUNCADENCE__BPM,MAX_SPEED__CENTIMETERS_PER_MILLISECOND,SUM_BMR_ENERGY__KILOJOULE,WEIGHTED_MEAN_DOUBLE_CADENCE__BPM,MAX_RUNCADENCE__BPM,SUM_DISTANCE__CENTIMETER,SUM_DURATION__MILLISECOND,WEIGHTED_MEAN_HEARTRATE__BPM,LOSS_ELEVATION__CENTIMETER,MAX_HEARTRATE__BPM,SUM_ELAPSEDDURATION__MILLISECOND,GAIN_ELEVATION__CENTIMETER,WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND,SUM_ENERGY__KILOJOULE,MAX_DOUBLE_CADENCE__BPM,WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND,WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER_y,WEIGHTED_MEAN_ELAPSED_DURATION_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND_y,SUM_MOVINGDURATION__MILLISECOND_y,WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND_y
0,0,0,1676389151000,1676389151000,50.660711,4.459391,0,22,0,0,0,"[{'field': {'id': 111, 'key': 'weightedMeanRun...",88.0,0.0,0.0,175.0,88.0,289.0,5000.0,59.0,0.0,59.0,5000.0,0.0,0.0,0.0,175.0,0.0578,19.817144,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,0,1676389152000,1676391525000,50.660734,4.459357,1,17,2,590,0,"[{'field': {'id': 111, 'key': 'weightedMeanRun...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78.0,0.4124,255.59122,156.0625,88.0,836069.0,2373000.0,151.0,14906.0,174.0,2373000.0,19412.0,0.0019,2497.25192,175.0,0.3523,135.455641,-0.000268,2367000.0,0.353219,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,0,1676391526000,1676391527000,50.661035,4.458446,2,22,591,591,0,"[{'field': {'id': 111, 'key': 'weightedMeanRun...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0317,0.0,0.0,0.0,918.0,2001.0,170.0,0.0,170.0,2001.0,0.0,0.0,4.19002,0.0,0.4588,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,0,1676391528000,1676391528000,50.661017,4.458580,3,18,0,0,0,"[{'field': {'id': 111, 'key': 'weightedMeanRun...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94.0,0.3872,0.0,188.0,94.0,540.0,1000.0,170.0,0.0,170.0,1000.0,0.0,0.0,0.0,188.0,0.54,172.340429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,0,1676391529000,1676391555000,50.661020,4.458640,4,17,592,601,0,"[{'field': {'id': 111, 'key': 'weightedMeanRun...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83.0,0.4199,4.19002,166.109375,94.0,7902.0,26301.0,175.0,0.0,179.0,34999.0,430.0,0.0185,29.33014,188.0,0.3004,108.523013,0.02633,26301.0,0.300445

In [ ]:
dict_measurements

{'WEIGHTED_MEAN_RUNCADENCE__BPM': 83.0,
 'MAX_SPEED__CENTIMETERS_PER_MILLISECOND': 0.4198999881744385,
 'SUM_BMR_ENERGY__KILOJOULE': 4.19002,
 'WEIGHTED_MEAN_DOUBLE_CADENCE__BPM': 166.109375,
 'MAX_RUNCADENCE__BPM': 94.0,
 'SUM_DISTANCE__CENTIMETER': 7902.0,
 'SUM_DURATION__MILLISECOND': 26301.0,
 'WEIGHTED_MEAN_HEARTRATE__BPM': 175.0,
 'LOSS_ELEVATION__CENTIMETER': 0.0,
 'MAX_HEARTRATE__BPM': 179.0,
 'SUM_ELAPSEDDURATION__MILLISECOND': 34999.0,
 'GAIN_ELEVATION__CENTIMETER': 430.0,
 'WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND': 0.01850000023841858,
 'SUM_ENERGY__KILOJOULE': 29.330139999999997,
 'MAX_DOUBLE_CADENCE__BPM': 188.0,
 'WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND': 0.3003999948501587,
 'WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER': 108.52301278392451,
 'WEIGHTED_MEAN_ELAPSED_DURATION_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND': 0.02633039686414931,
 'SUM_MOVINGDURATION__MILLISECOND': 26301.0,
 'WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND': 0.30044483044424525}

In [ ]:
  print(split_measurements)
        dict_measurements = {}
        print(index)
        for _, row in split_measurements.iterrows():
            dict_measurements[f"{row['fieldEnum']}__{row['unitEnum']}"] = row['value']
            #print(dict_measurements)
        split_measurements_df = pd.DataFrame(dict_measurements, index = [index])
        activity_splits = pd.merge(activity_splits, split_measurements_df,\
                                   left_index = True, right_index = True)
activity_splits
    #activity_splits_full = pd.concat([activity_splits_full, activity_splits], ignore_index = True)
#activity_splits_full.drop_duplicates()

In [ ]:
measurements_df

,SUM_ENERGY__KILOJOULE,WEIGHTED_MEAN_RUNCADENCE__BPM,SUM_ELAPSEDDURATION__MILLISECOND,MAX_SPEED__CENTIMETERS_PER_MILLISECOND,MAX_DOUBLE_CADENCE__BPM,WEIGHTED_MEAN_SPEED__CENTIMETERS_PER_MILLISECOND,SUM_DISTANCE__CENTIMETER,WEIGHTED_MEAN_HEARTRATE__BPM,SUM_DURATION__MILLISECOND,WEIGHTED_MEAN_DOUBLE_CADENCE__BPM,SUM_BMR_ENERGY__KILOJOULE,LOSS_ELEVATION__CENTIMETER,MAX_RUNCADENCE__BPM,WEIGHTED_MEAN_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND,MAX_HEARTRATE__BPM,GAIN_ELEVATION__CENTIMETER,WEIGHTED_MEAN_STRIDE_LENGTH__CENTIMETER,WEIGHTED_MEAN_ELAPSED_DURATION_VERTICAL_SPEED__CENTIMETERS_PER_MILLISECOND,SUM_MOVINGDURATION__MILLISECOND,WEIGHTED_MEAN_MOVINGSPEED__CENTIMETERS_PER_MILLISECOND
1,0.0,23.0,7002.0,0.1754,159.0,0.2072,1451.0,76.0,7002.0,45.421875,0.0,0.0,80.0,0.0,76.0,0.0,273.735746,-0.011207,3000.0,0.483667

In [ ]:
pd.DataFrame(overall_df.loc[0].splits[0]).measurements

0     {'field': {'id': 113, 'key': 'sumEnergy', 'con...
1     {'field': {'id': 111, 'key': 'weightedMeanRunC...
2     {'field': {'id': 2651, 'key': 'sumElapsedDurat...
3     {'field': {'id': 106, 'key': 'maxSpeed', 'cont...
4     {'field': {'id': 3132, 'key': 'maxDoubleCadenc...
5     {'field': {'id': 105, 'key': 'weightedMeanSpee...
6     {'field': {'id': 103, 'key': 'sumDistance', 'c...
7     {'field': {'id': 107, 'key': 'weightedMeanHear...
8     {'field': {'id': 104, 'key': 'sumDuration', 'c...
9     {'field': {'id': 3131, 'key': 'weightedMeanDou...
10    {'field': {'id': 4000, 'key': 'sumBmrEnergy', ...
11    {'field': {'id': 118, 'key': 'lossElevation', ...
12    {'field': {'id': 112, 'key': 'maxRunCadence', ...
13    {'field': {'id': 3811, 'key': 'weightedMeanVer...
14    {'field': {'id': 108, 'key': 'maxHeartRate', '...
15    {'field': {'id': 117, 'key': 'gainElevation', ...
16    {'field': {'id': 3169, 'key': 'weightedMeanStr...
17    {'field': {'id': 4007, 'key': 'weightedMeanEla...
18    {'field': {'id': 2647, 'key': 'sumMovingDurati...
19    {'field': {'id': 2658, 'key': 'weightedMeanMov...
Name: measurements, dtype: object

In [ ]:
splits_df = pd.DataFrame(overall_df.loc[].splits[0])
splits_df

In [ ]:
for index in range(overall_df.shape[0]):
    if row['activityType'] != 'Running':
        continue
    print(overall_df.splits[index][0][0])
    split_df = pd.DataFrame(overall_df.splits[index])
    splits_df = pd.concat([splits_df, split_df], ignore_index=True)

# Garmin

In [ ]:
from garminconnect import Garmin
import datetime
from datetime import date
import json

In [ ]:
import fitparse

fitfile = fitparse.FitFile('/Users/valen/code/VaHerinckx/LifeLog_Project/Garmin/174959604532_WELLNESS.fit')
fitfile.parse()

In [ ]:
import pandas as pd

data = []
for message in fitfile.messages:
    if message.name == 'stress_level':
        record_data = {}
        for field in message.fields:
            record_data[field.name] = field.value
        data.append(record_data)
        
df = pd.DataFrame(data)
df

In [ ]:
message.name

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_json('exports/garmin_exports/DI_CONNECT/DI-Connect-User/UDSFile_2022-12-16_2023-03-26.json')

In [ ]:
df

In [ ]:
import requests
from bs4 import BeautifulSoup

url = 'https://connect.garmin.com/modern/daily-summary/2023-04-03'
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')
walking_data = soup.find('span', {'class': 'IconTooltip_titleText__1uGJY'})
soup

In [ ]:
import time

from selenium import webdriver


driver = webdriver.Chrome('chromedriver_mac64(1)/LICENSE.chromedriver')  # Optional argument, if not specified will search path.

driver.get('http://www.google.com/');

time.sleep(5) # Let the user actually see something!

search_box = driver.find_element_by_name('q')

search_box.send_keys('ChromeDriver')

search_box.submit()

time.sleep(5) # Let the user actually see something!

driver.quit()

In [ ]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By

# Instantiate a new Chrome browser
driver = webdriver.Chrome(executable_path= 'chromedriver_mac64(2)/chromedriver')

# Load the login page
driver.get('https://connect.garmin.com/signin/')

driver.implicitly_wait(10)
# Find the username and password input fields and submit button
#username_field = driver.find_element_by_id('username')
password_field = driver.find_element(By.NAME, 'password')
submit_button = driver.find_element(By.NAME, 'submit')

# Fill in the form and submit it
username_field.send_keys('valentin.herinckx@gmail.com')
password_field.send_keys('Placebo1')
submit_button.click()

# Wait for the page to load after login
driver.implicitly_wait(10)

# Check if we have been redirected to the authenticated page
if driver.current_url == 'https://connect.garmin.com/modern/':
    print('Login successful')
else:
    print('Login failed')
    
# Close the browser
driver.quit()

In [ ]:
import requests
from bs4 import BeautifulSoup
login_url = 'https://connect.garmin.com/signin'
login_data = {
    'username': 'valentin.herinckx@gmail.com',
    'password': 'Placebo1'
}

session = requests.Session()
# Send a POST request with the login credentials to authenticate
response = session.post(login_url, data=login_data)
print(response.url)

In [ ]:


# Prepare the login credentials and CSRF token for submission
login_data = {
    '_csrf': '19C11F4E952BB38025978A1D6F146222EAA0DD5A9F9B8DE1686CD2003BEA5A3ECC615CA2A5D9078139BC9A04EF6685E0D14C',
    'username': 'valentin.herinckx@gmail.com',
    'password': 'Placebo1'
}

# Send a POST request with the login credentials to authenticate
response = session.post(login_url, data=login_data)

# Check the status code of the response to ensure successful login
if response.status_code == 200:
    print("login successful")
    # Send a GET request to the protected page and scrape the necessary data
    response = session.get(target_url)
    print(response.url)
    soup = BeautifulSoup(response.text, 'html.parser')
    print(soup)
    walking_data = soup.find('span', {'class': 'IconTooltip_titleText__1uGJY'})
    
    if walking_data:
        activity_type = walking_data.text.strip()
        print("Activity type:", activity_type)
    else:
        print("No activity type found.")
else:
    print("Login failed with status code", response.status_code)

In [ ]:
!pip3 install selenium# Import the libraries.
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By# Create variables for login credentials.
username = "valentin.herinckx@gmail.com"
password = "Placebo1"# Install the chrome web driver from selenium. 
!apt-get update 
!apt install chromium-chromedriver

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
driver = webdriver.Chrome('chromedriver_mac64(2)/chromedriver',chrome_options=chrome_options)


# Launch the browser and open the github URL in your web driver.
driver.get("https://connect.garmin.com/signin/")
WebDriverWait(driver=driver, timeout=10)

# Find the username/email field and send the username to the input field.
uname = driver.find_element("id", "username") 
uname.send_keys(username)

# Find the password input field and send the password to the input field.
pword = driver.find_element("id", "password") 
pword.send_keys(password)

# Click sign in button to login the website.
driver.find_element("type", "submit").click()# Wait for login process to complete. 
WebDriverWait(driver=driver, timeout=10).until(
    lambda x: x.execute_script("return document.readyState === 'complete'")
)# Verify that the login was successful.
error_message = "Incorrect username or password."
# Retrieve any errors found. 
errors = driver.find_elements(By.CLASS_NAME, "flash-error")

# When errors are found, the login will fail. 
if any(error_message in e.text for e in errors): 
    print("[!] Login failed")
else:
    print("[+] Login successful")# Close the driver
driver.close()

# Scraping Garmin

In [ ]:
import requests
url = 'https://connect.garmin.com/signin/'
username = 'valentin.herinckx@gmail.com'
password = 'Placebo1'
embed = False
_csrf = 'AEEB156F81510ECF63A16D0DE716B40756F71BEA07D9EFCBE13839CBC4B5AE669EFB60694643C2C7C75576B773C1CAF0662C'

In [ ]:
payload = {
    "username" : username,
    "password" : password,
    "embed" : embed,
    "_csrf" : _csrf
}

In [ ]:
s = requests.Session()

In [ ]:
p = s.post(url, data = payload)
p.status_code
print(p.url)

## Test scraping other website

In [ ]:
url = "http://quotes.toscrape.com/login"
username = 'valentin.herinckx@gmail.com'
password = 'Placebo1'
payload = {
    "username" : username,
    "password" : password,
    #"embed" : embed,
    #"_csrf" : _csrf
}
s = requests.Session()
p = s.post(url, data = payload)
p.status_code
print(p.url)

## Chat GPT instructions

In [ ]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
username = "valentin.herinckx@gmail.com"
password = "Placebo1"# Install the chrome web driver from selenium. 

driver = webdriver.Chrome('chromedriver_mac64(2)/chromedriver')

# Launch the browser and open the github URL in your web driver.
driver.get("https://connect.garmin.com/signin/")

# Wait for the page to load and the login form to become visible
wait = WebDriverWait(driver, 10)
username_field = driver.find_elements(By.TAG_NAME, "label")
#password_field = driver.find_element_by_id('password')
#submit_button = driver.find_element_by_id('login-btn-signin')

soup = BeautifulSoup(driver.page_source, 'html.parser')
soup

In [ ]:
# Find the username/email field and send the username to the input field.
uname = driver.find_element("id", "username") 
uname.send_keys(username)

# Find the password input field and send the password to the input field.
pword = driver.find_element("id", "password") 
pword.send_keys(password)

# Click sign in button to login the website.
driver.find_element("type", "submit").click()# Wait for login process to complete. 
WebDriverWait(driver=driver, timeout=10).until(
    lambda x: x.execute_script("return document.readyState === 'complete'")
)# Verify that the login was successful.
error_message = "Incorrect username or password."
# Retrieve any errors found. 
errors = driver.find_elements(By.CLASS_NAME, "flash-error")

# When errors are found, the login will fail. 
if any(error_message in e.text for e in errors): 
    print("[!] Login failed")
else:
    print("[+] Login successful")# Close the driver
driver.close()

 # Pocket casts

In [ ]:
import pandas as pd

with open('exports/pocket_casts_exports/data 2.txt', 'r') as file:
    data = file.read()
tables = data.split('\n--------')
tables = [table.strip() for table in tables]

def parse_table_episodes(table_str):
    # Split the string into lines
    lines = table_str.strip().split('\n')
    # The first line contains the column names
    columns = lines[0].split(',')
    # The remaining lines contain the data
    data = [line.split(',') for line in lines[1:]]
    return pd.DataFrame(data, columns=columns)

def parse_table_history(table_str):
    # Split the string into lines
    lines = table_str.strip().split('\n')
    # The first line contains the column names
    columns = lines[0].split(',')
    # The remaining lines contain the data
    data = []
    for line in lines[1:]:
        data_line = []
        original_split = line.split(',')
        if len(original_split) > 6:
            data_line = original_split[:4]
            data_line.append(",".join(original_split[4:-1]))
            data_line.append(original_split[-1])
        else:
            data_line = line.split(',')
        data.append(data_line)
    return pd.DataFrame(data, columns=columns)

table_episodes = tables[3]
df_episodes = parse_table_episodes(table_episodes).drop(parse_table_episodes(table_episodes).index[-2:])

table_history = tables[5].split('\n-------')[2]
df_history = parse_table_history(table_history).drop(parse_table_history(table_history).index[-2:])

In [ ]:
df_history['modified at'] = pd.to_datetime(df_history['modified at'], unit = 'ms')
df_history['modified at'] = df_history['modified at'].dt.floor('S').apply(lambda x: time_difference_correction(x)).sort_values()
df_history['published at'] = pd.to_datetime(df_history['published at'], unit = 's').apply(lambda x: time_difference_correction(x)).sort_values()

In [ ]:
df_episodes.query('uuid == "51cbb550-e68a-0134-ec2c-4114446340cb"')

# DON'T TOUCH

In [ ]:
i = 0
list_podcast_id = list(df_history.groupby('podcast').count().sort_values('uuid', ascending = False).reset_index().podcast.unique())
total = len(list_podcast_id)
dict_podcast = {}

# DON'T TOUCH

In [ ]:
df = pd.read_csv('work_files/podcast_mapping.csv', sep = '|')
dict_podcast = df.set_index('podcast_id')['podcast_name'].to_dict()
dict_podcast

In [ ]:
input_name = "The goop Podcast"

In [ ]:
df = pd.read_csv('work_files/podcast_mapping.csv', sep = '|')
dict_podcast = df.set_index('podcast_id')['podcast_name'].to_dict()
if (list_podcast_id[i] in list(dict_podcast.keys())) | (input_name in list(dict_podcast.values())):
    print("Already added")
else:
    dict_podcast[list_podcast_id[i]] = input_name
df = pd.DataFrame(list(dict_podcast.items()), columns=['podcast_id', 'podcast_name'])
df.to_csv('work_files/podcast_mapping.csv', sep = '|')

In [ ]:
i+=1

In [ ]:
print(f"{i} podcast out of {total} done")
print(list_podcast_id[i])
df_history[df_history["podcast"] == list_podcast_id[i]]

In [ ]:
df_episodes.query("uuid == '1bc28152-508b-4bf7-830d-efc67db4fead'")
list(df_episodes['uuid'].unique())

# Podcast genre

In [ ]:
import requests

# Set up API endpoint and parameters
url = "https://listen-api.listennotes.com/api/v2/search"
headers = {'X-ListenAPI-Key': 'YOUR_API_KEY_HERE'}
params = {'q': 'PODCAST_NAME_HERE', 'type': 'podcast'}

# Make API request and get response
response = requests.get(url, headers=headers, params=params).json()

# Check if there are any results and get the genre
if response['count'] > 0:
    genre = response['results'][0]['genre_ids'][0]
    print(f"The genre of the podcast is {genre}")
else:
    print("No results found for the given podcast name.")

# Letterboxd

In [ ]:
import os
import shutil

# Define the parent directory containing all the folders
parent_dir = 'exports/letterboxd_exports/'

# Get a list of all the subdirectories in the parent directory
subdirs = [os.path.join(parent_dir, d) for d in os.listdir(parent_dir) if os.path.isdir(os.path.join(parent_dir, d))]

# Sort the subdirectories by name (which includes the date in YYYY-MM-DD format)
sorted_subdirs = sorted(subdirs, key=lambda x: os.path.basename(x))

# Select the most recent subdirectory (i.e., the last one in the sorted list)
most_recent_subdir = sorted_subdirs[-1]

# Remove all the other subdirectories
for subdir in sorted_subdirs[:-1]:
    shutil.rmtree(subdir)
    
# Use the most recent subdirectory for further processing
print(f"Using most recent subdirectory: {most_recent_subdir}")
sorted_subdirs

# Weather API

In [ ]:
df = pd.read_excel('work_files/weather_work_files/weather_work_file.xlsx')
df

In [ ]:
import requests
import json
from geopy.geocoders import Nominatim
from geopy import distance
from dotenv import load_dotenv
import os
import pandas as pd

# Set the name of the location you want to retrieve weather data for
location_name = 'Hualien, Taiwan'

# Define the start and end dates for the historical data in YYYY-MM-DD format
start_date = '2023-04-06'
end_date = '2023-04-17'

# Set your Meteostat API key
api_key = "9a3c791d64msh70c5eee6bf72a6fp1407a6jsnd7dd35285345"
api_host = "meteostat.p.rapidapi.com"

# Use the Geocoding API to find the latitude and longitude of the location
geolocator = Nominatim(user_agent='my_application')
location = geolocator.geocode(location_name)
latitude = location.latitude
longitude = location.longitude

# Retrieve a list of weather stations from the Meteostat API
url = "https://meteostat.p.rapidapi.com/stations/nearby"

querystring = {"lat":latitude,"lon":longitude, 'radius':1000000}

headers = {
	"X-RapidAPI-Key": api_key,
	"X-RapidAPI-Host": api_host
}

response = requests.request("GET", url, headers=headers, params=querystring)

stations = json.loads(response.text)['data']

# Extract the station ID for the nearest weather station
station_id = stations[2]['id']
station_name = stations[1]['name']['en']

# Use the Meteostat API to retrieve hourly historical weather data for the nearest weather station
url = "https://meteostat.p.rapidapi.com/stations/hourly"

querystring = {"station":'46770',"start":start_date,"end":end_date}

headers = {
	"X-RapidAPI-Key": api_key,
	"X-RapidAPI-Host": api_host
}

response = requests.request("GET", url, headers=headers, params=querystring)

weather_data = json.loads(response.text)['data']

In [ ]:
json.loads(response.text)

In [ ]:
stations_dict = {}
for station in stations:
    stations_dict[station['id']] = station['name']['en']
stations_dict

In [ ]:
for data_point in weather_data:
    hourly_location.append(location_name)
    hourly_station_id.append(station_id)
    hourly_station_name.append(station_name)
    hourly_time.append(data_point['time'])
    hourly_temp.append(data_point['temp'])
    hourly_dwpt.append(data_point['dwpt'])
    hourly_rhum.append(data_point['rhum'])
    hourly_prcp.append(data_point['prcp'])
    hourly_snow.append(data_point['snow'])
    hourly_wdir.append(data_point['wdir'])
    hourly_wspd.append(data_point['wspd'])
    hourly_wpgt.append(data_point['wpgt'])
    hourly_pres.append(data_point['pres'])
    hourly_tsun.append(data_point['tsun'])
    hourly_coco.append(data_point['coco'])

data = [hourly_location, hourly_station_id, hourly_station_name, hourly_time, hourly_temp,\
        hourly_dwpt, hourly_rhum,hourly_prcp, hourly_snow, hourly_wdir, hourly_wspd,\
        hourly_wpgt, hourly_pres,hourly_tsun, hourly_coco]
col_names = ['location', 'closest_station_id', 'closest_station_name', 'timestamp',\
             'temperature', 'dew_point', 'relative_humidity_%', 'precipitation', 'snow_depth',\
             'wind_direction', 'wind_speed', 'peak_wind_gust', 'sea_level_air_pressure',\
             'sunshine_total_time','weather_condition_code']

dict_weather_code = {1: 'Clear',
                     2: 'Fair',
                     3: 'Cloudy',
                     4: 'Overcast',
                     5: 'Fog',
                     6: 'Freezing Fog',
                     7: 'Light Rain',
                     8: 'Rain',
                     9: 'Heavy Rain',
                     10: 'Freezing Rain',
                     11: 'Heavy Freezing Rain',
                     12: 'Sleet',
                     13: 'Heavy Sleet',
                     14: 'Light Snowfall',
                     15: 'Snowfall',
                     16: 'Heavy Snowfall',
                     17: 'Rain Shower',
                     18: 'Heavy Rain Shower',
                     19: 'Sleet Shower',
                     20: 'Heavy Sleet Shower',
                     21: 'Snow Shower',
                     22: 'Heavy Snow Shower',
                     23: 'Lightning',
                     24: 'Hail',
                     25: 'Thunderstorm',
                     26: 'Heavy Thunderstorm',
                     27: 'Storm'}

df = pd.DataFrame(data).transpose()
df.columns = col_names
df['weather_assessment'] = df['weather_condition_code'].map(dict_weather_code)
df

# Kindle

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('exports/kindle_exports/Kindle.Devices.ReadingSession/Kindle.Devices.ReadingSession.csv')

In [ ]:
df_cleaned = df[df['total_reading_millis'].notna()]

In [ ]:
df_cleaned['start_timestamp'] = pd.to_datetime(df_cleaned['start_timestamp'])
df_cleaned['end_timestamp'] = pd.to_datetime(df_cleaned['end_timestamp'])

In [ ]:
df_cleaned['end_date'] = df_cleaned.end_timestamp.dt.date
df_cleaned['start_date'] = df_cleaned.start_timestamp.dt.date
df_cleaned[['ASIN', 'start_date', 'end_date']].groupby("ASIN")\
          .agg({'start_date': 'min', 'end_date': 'max'}).sort_values('start_date')

In [ ]:
df_gr = pd.read_csv('processed_files/gr_processed.csv', sep = ',')

In [ ]:
df_gr[df_gr['Date ended'].notna()][['Title','Date started','Date ended']].sort_values('Date ended', ascending = False)

# Apple Health

In [ ]:
import pandas as pd
import xmltodict
import datetime
import time

In [ ]:
path = 'exports/apple_exports/apple_export_180423.xml'
with open(path, 'r') as xml_file:
        input_data = xmltodict.parse(xml_file.read())
print('Apple health import succesful')
records_list = input_data['HealthData']['Record']
df = pd.DataFrame(records_list)

Apple health import succesful

In [ ]:
df["@type"].unique()

array(['HKQuantityTypeIdentifierDietaryWater',
       'HKQuantityTypeIdentifierHeight',
       'HKQuantityTypeIdentifierBodyMass',
       'HKQuantityTypeIdentifierHeartRate',
       'HKQuantityTypeIdentifierStepCount',
       'HKQuantityTypeIdentifierDistanceWalkingRunning',
       'HKQuantityTypeIdentifierBasalEnergyBurned',
       'HKQuantityTypeIdentifierActiveEnergyBurned',
       'HKQuantityTypeIdentifierFlightsClimbed',
       'HKQuantityTypeIdentifierDistanceCycling',
       'HKQuantityTypeIdentifierRestingHeartRate',
       'HKQuantityTypeIdentifierHeadphoneAudioExposure',
       'HKQuantityTypeIdentifierWalkingDoubleSupportPercentage',
       'HKQuantityTypeIdentifierWalkingSpeed',
       'HKQuantityTypeIdentifierWalkingStepLength',
       'HKQuantityTypeIdentifierWalkingAsymmetryPercentage',
       'HKDataTypeSleepDurationGoal',
       'HKQuantityTypeIdentifierAppleWalkingSteadiness',
       'HKCategoryTypeIdentifierSleepAnalysis',
       'HKCategoryTypeIdentifierHeadphoneAudioExposureEvent'],
      dtype=object)

In [ ]:
df['@startDate'] = pd.to_datetime(df['@startDate']).dt.floor("T")
df['@endDate'] = pd.to_datetime(df['@endDate']).dt.floor("T")

In [ ]:
df[df["@type"]=='HKQuantityTypeIdentifierActiveEnergyBurned'].sort_values('@startDate')

,@type,@sourceName,@sourceVersion,@unit,@creationDate,@startDate,@endDate,@value,@device,MetadataEntry
688654,HKQuantityTypeIdentifierActiveEnergyBurned,Polar Flow,373,kcal,2018-10-26 01:19:13 +0800,2018-10-26 01:19:12 +0800,2018-10-26 01:19:12 +0800,7,NaN,NaN
688655,HKQuantityTypeIdentifierActiveEnergyBurned,Polar Flow,373,kcal,2018-10-26 01:27:26 +0800,2018-10-26 01:27:25 +0800,2018-10-26 01:27:25 +0800,5,NaN,NaN
688656,HKQuantityTypeIdentifierActiveEnergyBurned,Polar Flow,373,kcal,2018-10-26 04:43:51 +0800,2018-10-26 04:43:50 +0800,2018-10-26 04:43:50 +0800,460,NaN,NaN
688657,HKQuantityTypeIdentifierActiveEnergyBurned,Polar Flow,373,kcal,2018-10-26 14:56:56 +0800,2018-10-26 05:59:59 +0800,2018-10-26 05:59:59 +0800,13,NaN,NaN
688658,HKQuantityTypeIdentifierActiveEnergyBurned,Polar Flow,373,kcal,2018-10-26 14:56:57 +0800,2018-10-26 14:56:55 +0800,2018-10-26 14:56:55 +0800,288,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
700335,HKQuantityTypeIdentifierActiveEnergyBurned,Connect,36,kcal,2023-04-18 09:01:12 +0800,2023-04-18 00:00:00 +0800,2023-04-18 09:01:12 +0800,13,NaN,NaN
700321,HKQuantityTypeIdentifierActiveEnergyBurned,Julien's iphone,16.1.1,kcal,2023-04-18 07:54:24 +0800,2023-04-18 07:42:20 +0800,2023-04-18 07:42:30 +0800,0.039,"<<HKDevice: 0x28330d400>, name:iPhone, manufac...",NaN
700322,HKQuantityTypeIdentifierActiveEnergyBurned,Julien's iphone,16.1.1,kcal,2023-04-18 08:07:24 +0800,2023-04-18 07:54:09 +0800,2023-04-18 08:04:05 +0800,13.701,"<<HKDevice: 0x28330d400>, name:iPhone, manufac...",NaN
700323,HKQuantityTypeIdentifierActiveEnergyBurned,Julien's iphone,16.1.1,kcal,2023-04-18 08:21:03 +0800,2023-04-18 08:04:05 +0800,2023-04-18 08:05:38 +0800,1.695,"<<HKDevice: 0x28330d400>, name:iPhone, manufac...",NaN
700324,HKQuantityTypeIdentifierActiveEnergyBurned,Julien's iphone,16.1.1,kcal,2023-04-18 08:32:28 +0800,2023-04-18 08:20:45 +0800,2023-04-18 08:30:34 +0800,33.071,"<<HKDevice: 0x28330d400>, name:iPhone, manufac...",NaN

In [ ]:
g_df = df.groupby('@startDate').count()
g_df[g_df["@type"] > 1]

,@type,@sourceName,@sourceVersion,@unit,@creationDate,@endDate,@value,@device,MetadataEntry
@startDate,,,,,,,,,
2022-04-07 21:51:00+08:00,21,21,21,21,21,21,21,0,0
2022-04-07 21:52:00+08:00,60,60,60,60,60,60,60,0,0
2022-04-07 21:53:00+08:00,60,60,60,60,60,60,60,0,0
2022-04-07 21:54:00+08:00,60,60,60,60,60,60,60,0,0
2022-04-07 21:55:00+08:00,60,60,60,60,60,60,60,0,0
...,...,...,...,...,...,...,...,...,...
2023-02-12 19:47:00+08:00,60,60,60,60,60,60,60,0,0
2023-02-12 19:48:00+08:00,60,60,60,60,60,60,60,0,0
2023-02-12 19:49:00+08:00,60,60,60,60,60,60,60,0,0
2023-02-12 19:50:00+08:00,60,60,60,60,60,60,60,0,0
2023-02-12 19:51:00+08:00,52,52,52,52,52,52,52,0,0

In [ ]:
df[df['@startDate'] >= '2022-04-07 21:52:00+08:00'].sort_values('@startDate')

,@type,@sourceName,@sourceVersion,@unit,@creationDate,@startDate,@endDate,@value,@device,MetadataEntry
36229,HKQuantityTypeIdentifierHeartRate,Polar Flow,749,count/min,2022-04-08 22:58:29 +0800,2022-04-07 21:52:01 +0800,2022-04-07 21:52:01 +0800,98,NaN,NaN
36230,HKQuantityTypeIdentifierHeartRate,Polar Flow,749,count/min,2022-04-08 22:58:29 +0800,2022-04-07 21:52:02 +0800,2022-04-07 21:52:02 +0800,98,NaN,NaN
36231,HKQuantityTypeIdentifierHeartRate,Polar Flow,749,count/min,2022-04-08 22:58:29 +0800,2022-04-07 21:52:03 +0800,2022-04-07 21:52:03 +0800,99,NaN,NaN
36232,HKQuantityTypeIdentifierHeartRate,Polar Flow,749,count/min,2022-04-08 22:58:29 +0800,2022-04-07 21:52:04 +0800,2022-04-07 21:52:04 +0800,100,NaN,NaN
36233,HKQuantityTypeIdentifierHeartRate,Polar Flow,749,count/min,2022-04-08 22:58:29 +0800,2022-04-07 21:52:05 +0800,2022-04-07 21:52:05 +0800,103,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
388019,HKQuantityTypeIdentifierHeartRate,Connect,36,count/min,2023-04-18 09:01:18 +0800,2023-04-18 08:50:00 +0800,2023-04-18 08:50:00 +0800,62,NaN,NaN
388020,HKQuantityTypeIdentifierHeartRate,Connect,36,count/min,2023-04-18 09:01:18 +0800,2023-04-18 08:52:00 +0800,2023-04-18 08:52:00 +0800,49,NaN,NaN
388021,HKQuantityTypeIdentifierHeartRate,Connect,36,count/min,2023-04-18 09:01:18 +0800,2023-04-18 08:54:00 +0800,2023-04-18 08:54:00 +0800,49,NaN,NaN
388022,HKQuantityTypeIdentifierHeartRate,Connect,36,count/min,2023-04-18 09:01:18 +0800,2023-04-18 08:56:00 +0800,2023-04-18 08:56:00 +0800,50,NaN,NaN
388023,HKQuantityTypeIdentifierHeartRate,Connect,36,count/min,2023-04-18 09:01:18 +0800,2023-04-18 08:58:00 +0800,2023-04-18 08:58:00 +0800,58,NaN,NaN

In [ ]:
df['@startDate']

152      2018-10-26 14:28:00+08:00
153      2018-10-26 14:29:00+08:00
154      2018-10-26 14:30:00+08:00
155      2018-10-26 14:31:00+08:00
156      2018-10-26 14:32:00+08:00
                    ...
388019   2023-04-18 08:50:00+08:00
388020   2023-04-18 08:52:00+08:00
388021   2023-04-18 08:54:00+08:00
388022   2023-04-18 08:56:00+08:00
388023   2023-04-18 08:58:00+08:00
Name: @startDate, Length: 387872, dtype: datetime64[ns, pytz.FixedOffset(480)]

In [ ]:
heart_rate_df['@startDate'] = pd.to_datetime(heart_rate_df['@startDate'])
heart_rate_df['@endDate'] = pd.to_datetime(heart_rate_df['@endDate'])
heart_rate_df["end_start_diff"] = heart_rate_df["@endDate"] - heart_rate_df["@startDate"]

/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_1612/2644188187.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  heart_rate_df['@startDate'] = pd.to_datetime(heart_rate_df['@startDate'])
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_1612/2644188187.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  heart_rate_df['@endDate'] = pd.to_datetime(heart_rate_df['@endDate'])
/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_1612/2644188187.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  heart_rate_df["end_start_diff"] = heart_rate_df["@endDate"] - heart_rate_df["@startDate"]

1

In [ ]:
df = df[df['@type'] == 'HKQuantityTypeIdentifierStepCount']

In [ ]:
df["@sourceName"].unique()

array(["Julien's iphone", 'Polar Flow', 'Connect'], dtype=object)

In [ ]:
df['@startDate'] = pd.to_datetime(df['@startDate'])
df['@endDate'] = pd.to_datetime(df['@endDate'])
df["@value"] = df["@value"].astype(float)
df["@endDate"] = df["@endDate"].dt.floor("T")
df["@startDate"] = df["@startDate"].dt.floor("T")

In [ ]:
df.shape

(169557, 11)

In [ ]:
df.shape[0]/new_df.shape[0]

19.75267940354147

In [ ]:
new_df = df[df['Date'] >= datetime.date(2023, 1, 1)]

In [ ]:
def row_expander_sum(row):
    minute_diff = (row['@endDate'] - row['@startDate']).total_seconds()/60
    if minute_diff <=1:
        date_df = pd.DataFrame(columns=['date', 'val', 'source'])
        new_row = {'date': row['@startDate'], 'val' : row["@value"], 'source' : row['@sourceName']}
        date_df = date_df.append(new_row, ignore_index=True)
        return date_df
    dates = pd.date_range(row['@startDate'], row['@endDate']- pd.Timedelta(minutes=1), freq='T')
    date_df = pd.DataFrame({'date': dates})
    date_df['val'] = row["@value"]/minute_diff
    date_df['source'] = row['@sourceName']
    return date_df

In [ ]:
date_df = pd.DataFrame(columns=['date', 'val'])
df['@startDate'] = pd.to_datetime(df['@startDate']).dt.floor("T")
df['@endDate'] = pd.to_datetime(df['@endDate']).dt.floor("T")
df["@value"] = df["@value"].astype(float)
start_time = time.time()
for index, row in new_df.iterrows():
    date_df = pd.concat([date_df, row_expander_sum(row)], ignore_index=True)
time_spent = time.time() - start_time
print(f"Time spent in function: {time_spent} seconds")
date_df

Time spent in function: 7.745074987411499 seconds

                           date    val           source
0     2023-01-01 00:00:00+08:00  10.00  Julien's iphone
1     2023-01-01 00:08:00+08:00  13.75  Julien's iphone
2     2023-01-01 00:09:00+08:00  13.75  Julien's iphone
3     2023-01-01 00:10:00+08:00  13.75  Julien's iphone
4     2023-01-01 00:11:00+08:00  13.75  Julien's iphone
...                         ...    ...              ...
65521 2023-04-18 08:54:00+08:00   4.00          Connect
65522 2023-04-18 08:55:00+08:00   4.00          Connect
65523 2023-04-18 08:56:00+08:00   4.00          Connect
65524 2023-04-18 08:57:00+08:00   4.00          Connect
65525 2023-04-18 08:58:00+08:00   4.00          Connect

[65526 rows x 3 columns]

In [ ]:
date_df.val.sum()

2451761.0

In [ ]:
new_df['@value'].sum()

2451761.0

In [ ]:
df["minutes_diff"] = df.apply(lambda row: (row["@endDate"] - row["@startDate"]).total_seconds()/60, axis=1)
same_hour_df = df[df["@startDate"].dt.hour == df["@endDate"].dt.hour].copy()
diff_hour_df = df[df["@startDate"].dt.hour != df["@endDate"].dt.hour].copy()
same_hour_df["@hour"] = same_hour_df["@startDate"].dt.floor("H")
result_df = same_hour_df.groupby(["@hour"], as_index=False).agg({"@value": "sum"})
result_df = result_df.rename(columns={"@hour": "date"})
diff_hour_df = diff_hour_df.set_index("@startDate").resample("T").asfreq()
diff_hour_df = diff_hour_df.fillna(value=0)
diff_hour_df["@hour"] = diff_hour_df.index.floor("H")
result_df2 = diff_hour_df.groupby(["@hour"], as_index=False).agg({"@value": "sum"})
result_df2 = result_df2.rename(columns={"@hour": "date"})
result_df = pd.concat([result_df, result_df2])

In [ ]:
result_df['@value'].sum()

33856103.0

# Scraping Garmin

In [ ]:
import requests
import json
import bs4
import pandas as pd
import os
import csv
import time
import sys
import urllib.request
from datetime import date
from dotenv import load_dotenv
from selenium import webdriver
#from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import StaleElementReferenceException
from json import JSONDecoder
from fake_useragent import UserAgent
#from user_agent import random_header

In [ ]:
# set url
url = 'https://connect.garmin.com/signin/'
username = "valentin.herinckx@gmail.com"
password = "Placebo1"

# call open browser function
chrome_options = Options()
chrome_options.add_argument("--window-size=1920,1080")
chrome_options.headless = True
chrome_options.add_argument("--disable-dev-shm-usage")
chrome_options.add_argument("--no-sandbox")
prefs = {"profile.managed_default_content_settings.images": 2}
chrome_options.add_experimental_option("prefs", prefs)
ua = UserAgent()
userAgent = ua.random
chrome_options.add_argument(f'user-agent={userAgent}')
driver = webdriver.Chrome('chromedriver_mac64(2)/chromedriver')
driver.get(url)

username = WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.CLASS_NAME, 'username')))
password = WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.CLASS_NAME, 'password')))
username.send_keys(username)
password.send_keys(password)

driver.find_element_by_xpath("//*[@type='submit']").click()
time.sleep(2)

error_message = "Incorrect username or password."
# When errors are found, the login will fail. 
if any(error_message in e.text for e in errors): 
    print("[!] Login failed")
else:
    print("[+] Login successful")# Close the driver
driver.close()

/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_56237/2364861136.py:17: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome('chromedriver_mac64(2)/chromedriver')

TimeoutException: Message:
Stacktrace:
0   chromedriver                        0x00000001030e76f8 chromedriver + 4982520
1   chromedriver                        0x00000001030dedf3 chromedriver + 4947443
2   chromedriver                        0x0000000102c9b1b6 chromedriver + 475574
3   chromedriver                        0x0000000102cde9f0 chromedriver + 752112
4   chromedriver                        0x0000000102cdec51 chromedriver + 752721
5   chromedriver                        0x0000000102d22f34 chromedriver + 1031988
6   chromedriver                        0x0000000102d04c0d chromedriver + 908301
7   chromedriver                        0x0000000102d2022b chromedriver + 1020459
8   chromedriver                        0x0000000102d049b3 chromedriver + 907699
9   chromedriver                        0x0000000102cceacf chromedriver + 686799
10  chromedriver                        0x0000000102ccffee chromedriver + 692206
11  chromedriver                        0x00000001030a311d chromedriver + 4702493
12  chromedriver                        0x00000001030a8382 chromedriver + 4723586
13  chromedriver                        0x00000001030aeebf chromedriver + 4751039
14  chromedriver                        0x00000001030a92fa chromedriver + 4727546
15  chromedriver                        0x000000010307baa2 chromedriver + 4541090
16  chromedriver                        0x00000001030c8ff8 chromedriver + 4857848
17  chromedriver                        0x00000001030c9177 chromedriver + 4858231
18  chromedriver                        0x00000001030d871f chromedriver + 4921119
19  libsystem_pthread.dylib             0x00007ff811ded259 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff811de8c7b thread_start + 15

In [ ]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC


# specify the path to chromedriver.exe
driver_path = 'chromedriver_mac64(2)/chromedriver'

from selenium.webdriver.chrome.options import Options

options = Options()
options.add_argument("--disable-javascript")

driver = webdriver.Chrome(driver_path, options=options)

# create a new Chrome browser instance
#driver = webdriver.Chrome(driver_path)

# navigate to the login page
driver.get("https://connect.garmin.com/signin/")
html = driver.page_source

# print the HTML code to the console
print(html)


# find the login and password input fields and enter your credentials
login_field = WebDriverWait(driver, 120).until(EC.presence_of_element_located((By.ID, "username")))
login_field.send_keys("valentin.herinckx@gmail.com")

password_field = driver.find_element_by_id("password")
password_field.send_keys("Placebo1")

# submit the login form
password_field.send_keys(Keys.RETURN)

# you can now access your data on the website

/var/folders/8c/h641pyy52rg83z8vpp_7hb6c0000gn/T/ipykernel_56237/884546048.py:16: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(driver_path, options=options)

<html><head><style type="text/css">.truste_cursor_pointer {cursor: pointer;}.truste_border_none {border: none;}</style><meta charset="utf-8"><meta http-equiv="x-ua-compatible" content="ie=edge"><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"><style data-href="/styles.a8465107f99a824f09fa.css" id="gatsby-global-css">body,html{height:auto;font:400 14px/22px Open Sans,Helvetica Neue,Helvetica,Arial,sans-serif;color:#222;background-color:#efefef;margin:0}a,a:active,a:hover,a:visited{text-decoration:none;color:inherit}#truste-consent-track{display:block}#truste-consent-content{display:flex;align-items:center;justify-content:center;flex-wrap:wrap;width:100%;box-sizing:border-box}#truste-consent-text{margin:0 1rem 0 0;color:#fff;font-size:16px;font-weight:700;font-family:arial}#truste-consent-buttons>a{color:#fff;font-size:14px;margin:12px 10px 10px;text-align:center;text-decoration:underline}#truste-consent-buttons{display:flex;flex-direction:row;margin-top:1px!important;margin-left:10px!important}#truste-consent-buttons #truste-consent-button,#truste-consent-buttons #truste-consent-required,#truste-consent-buttons #truste-show-consent{font-family:Open Sans,HelveticaNeue,HelveticaNeueu,Arial,sans-serif;font-size:14px;color:#fff;background-color:#4a4a4a;cursor:pointer;padding:5px 20px;margin:12px 0;border-radius:4px;border:none}#truste-consent-buttons #truste-consent-required{margin-left:.5rem}#truste-consent-buttons #truste-show-consent{margin-left:1rem}#truste-consent-buttons #truste-consent-button:hover,#truste-consent-buttons #truste-consent-required:hover,#truste-consent-buttons #truste-show-consent:hover{background-color:#242424;border:none}#truste-cookie-button{color:#fff;margin:1rem;line-height:2}@media (max-width:1024px){#truste-consent-content{flex-direction:column;flex-wrap:nowrap}#truste-consent-text{margin:20px 20px 10px;text-align:center;width:unset!important}#truste-consent-buttons{display:block;text-align:center}#truste-consent-buttons #truste-consent-button,#truste-consent-buttons #truste-consent-required,#truste-consent-buttons #truste-show-consent{padding-top:10px;padding-bottom:10px;width:100%;margin:5px 0}#truste-cookie-button{display:inline-block;margin:auto;padding:15px}#truste-consent-buttons #truste-show-consent{margin-left:0}}.truste_overlay{background:#fff!important;opacity:.8!important}.truste_box_overlay{background:none!important}.truste_box_overlay_inner{border:3px solid #e8e8e8}</style><meta name="generator" content="Gatsby 2.32.13"><title data-react-helmet="true">Garmin Connect | </title><link data-react-helmet="true" rel="shortcut icon" href="https://static.garmincdn.com/favicon.ico"><meta data-react-helmet="true" name="robots" content="index,follow"><meta data-react-helmet="true" name="revisit-after" content="15 days"><meta data-react-helmet="true" name="author" content="Garmin International"><meta data-react-helmet="true" property="fb:app_id" content="169380733077633"><meta data-react-helmet="true" property="og:type" content="website"><meta data-react-helmet="true" property="og:site_name" content="Garmin Connect"><meta data-react-helmet="true" name="twitter:card" content="summary"><meta data-react-helmet="true" name="twitter:site" content="@GarminFitness"><meta data-react-helmet="true" name="description" content="Sign in to Garmin Connect to track, analyze and share the activities from your Garmin device."><meta data-react-helmet="true" property="og:title" content="Garmin Connect | Sign In"><meta data-react-helmet="true" property="og:url" content="https://connect.garmin.com/signin"><meta data-react-helmet="true" property="og:description" content="Sign in to Garmin Connect to track, analyze and share the activities from your Garmin device."><meta data-react-helmet="true" property="og:image" content="http://static.garmincdn.com/com.garmin.connect/content/images/garmin-connect-fb3.gif"><meta data-react-helmet="true" name="twitter:title" content="Garmin Connect | Sign In"><link as="script" rel="preload" href="/webpack-runtime-e5c95a7b88b68ee1a85c.js"><link as="script" rel="preload" href="/framework-e5864046d5e4814d37bb.js"><link as="script" rel="preload" href="/styles-ce7d8ff3eef002cc2f8a.js"><link as="script" rel="preload" href="/app-2a28dedf5bdf9902f4b1.js"><link as="script" rel="preload" href="/d7d9b804431110c1d15e411419869addd5f0115c-3c2082de5db94818410e.js"><link as="script" rel="preload" href="/278158f65b23e4213095c56b5a3ba41b0cf2c281-bb097181bf4bf18affee.js"><link as="script" rel="preload" href="/component---src-pages-signin-js-40881412a0113baf63b6.js"><link as="fetch" rel="preload" href="/page-data/signin/page-data.json" crossorigin="anonymous"><link as="fetch" rel="preload" href="/page-data/app-data.json" crossorigin="anonymous"><style data-jss="" data-meta="t, Unthemed, Static">
.c0138 {
  cursor: pointer;
  padding: 5px 5px 2px 15px;
}
.c0138:hover {
  background: #eeeeee;
}
.c0139 {
  margin: 10px 0 0 0;
  padding: 0;
  z-index: 1;
  position: absolute;
  overflow: scroll;
  background: #fff;
  max-height: 50vh;
  white-space: nowrap;
  list-style-type: none;
}
.c0140 {
  display: none;
}
@media only screen and (max-width: 767px) {
  .c0139 {
    margin: 0;
    position: relative;
  }
}
</style><style data-jss="" data-meta="t, Unthemed, Static">
.c0141 {
  margin: 0;
  cursor: pointer;
  border: none;
  background: none;
  transition: background-color 200ms;
  border-radius: 4px;
}
.c0141:focus {
  outline: none;
  box-shadow: 0 0 0 2px #fff, 0 0 0 4px #1976d2;
}
.c0141[disabled] {
  cursor: not-allowed;
  opacity: 0.5;
  box-shadow: none;
  pointer-events: none;
}
</style><style data-jss="" data-meta="t, Unthemed, Dynamic">
.c0142 {
  background-color: #1976d2;
  color: #fff;
  font-size: 14px;
  height: 33px;
  padding: 0 20px;
}
.c0142:focus {
  background-color: #1976d2;
}
.c0142:hover {
  background-color: #1265c2;
}
.c0142:active {
  background-color: #0a59b2;
}
.c0142[disabled] {
  background-color: #1976d2;
}
</style><style data-jss="" data-meta="t, Unthemed, Static">
.c017 {
  height: 60px;
  display: flex;
  padding: 0 15% 0 15%;
  background: #1a1a1a;
  justify-content: space-between;
}
.c018 {
  top: 3px;
  width: 150px;
  height: 28px;
  display: block;
  position: relative;
  background: transparent url(/static/logo-sprite-@2x-87aa58de41a3347bb5fc1e8ad25c31b6.png) no-repeat 0 -23.47619px;
  background-size: 236px 271px;
}
.c019 {
  float: right;
  margin: 0;
  list-style: none;
}
.c0110 {
  display: inline-block;
  margin-right: 25px;
}
.c0110 a {
  color: #fff;
  font-size: 1em;
  font-weight: 300;
}
.c0112 {
  width: 0;
  height: 0;
  display: inline-block;
  border-top: 4px solid #fff;
  border-left: 4px solid transparent;
  margin-left: 5px;
  border-right: 4px solid transparent;
}
.c0113 {
  width: 0;
  height: 0;
  display: inline-block;
  border-left: 4px solid transparent;
  margin-left: 5px;
  border-right: 4px solid transparent;
  border-bottom: 4px solid #fff;
}
.c0114 {
  display: none;
}
.c0115 {
  margin: 0;
  padding: 0;
}
.c0116 {
  font-size: inherit;
  font-weight: inherit;
  margin-block-end: 0em;
  margin-block-start: 0em;
}
.c0117 {
  margin-top: 12px;
}
.c0118 {
  margin-top: 12px;
}
@media only screen and (max-width: 767px) {
  .c018 {
    top: -3px;
  }
  .c0120 {
    height: 100%;
  }
  .c0121 {
    height: 100vh;
  }
  .c017 {
    margin: 0;
    display: flex;
    padding: 0;
    flex-flow: wrap;
    justify-content: space-between;
  }
  .c0117 {
    display: none;
  }
  .c0114 {
    width: 20px;
    margin: 23px 25px;
    height: 14px;
    display: inline-flex;
    background: transparent url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB3aWR0aD0iMjBweCIgaGVpZ2h0PSIxNHB4IiB2aWV3Qm94PSIwIDAgMjAgMTQiIHZlcnNpb249IjEuMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayI+CiAgICA8IS0tIEdlbmVyYXRvcjogU2tldGNoIDUzLjIgKDcyNjQzKSAtIGh0dHBzOi8vc2tldGNoYXBwLmNvbSAtLT4KICAgIDx0aXRsZT5pY29uLW1lbnU8L3RpdGxlPgogICAgPGRlc2M+Q3JlYXRlZCB3aXRoIFNrZXRjaC48L2Rlc2M+CiAgICA8ZyBpZD0iaWNvbi1tZW51IiBzdHJva2U9Im5vbmUiIHN0cm9rZS13aWR0aD0iMSIgZmlsbD0ibm9uZSIgZmlsbC1ydWxlPSJldmVub2RkIj4KICAgICAgICA8cGF0aCBkPSJNMCwwIEwyMCwwIEwyMCwyIEwwLDIgTDAsMCBaIE0wLDYgTDIwLDYgTDIwLDggTDAsOCBMMCw2IFogTTAsMTIgTDIwLDEyIEwyMCwxNCBMMCwxNCBMMCwxMiBaIiBpZD0iQ29tYmluZWQtU2hhcGUiIGZpbGw9IiNGRkZGRkYiPjwvcGF0aD4KICAgIDwvZz4KPC9zdmc+) no-repeat;
  }
  .c0122 {
    margin: 0;
    display: block;
    padding: 0;
    flex-flow: wrap;
    background: #121212;
    justify-content: space-between;
  }
  .c0122 .c018 {
    background: transparent url(/static/logo-sprite-@2x-87aa58de41a3347bb5fc1e8ad25c31b6.png) no-repeat 0 -23.47619px;
    background-size: 236px 271px;
  }
  .c0122 .c0117 {
    margin: 5px 0 10px 0;
    display: flex;
    flex-basis: 100%;
  }
  .c0122 .c0115 {
    width: 100%;
    margin: 0;
    padding: 0;
    display: grid;
  }
  .c0122 .c0110 {
    color: #fff;
    margin: 0;
    padding: 10px 25px;
    border-top: 1px solid #4d4d4d;
  }
  .c0122 .c0112 {
    float: right;
    margin-top: 10px;
    border-top: 4px solid #fff;
  }
  .c0122 .c0113 {
    float: right;
    margin-top: 10px;
    border-bottom: 4px solid #fff;
  }
  .c0122 .c0119 {
    width: 80%;
    margin-top: 20px;
    border-top: 0px;
    text-align: center;
    justify-self: center;
    margin-right: 0;
  }
  .c0122 .c0114 {
    width: 20px;
    right: 0;
    height: 18px;
    display: inline-block;
    position: absolute;
    background: transparent url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB3aWR0aD0iMTZweCIgaGVpZ2h0PSIxNnB4IiB2aWV3Qm94PSIwIDAgMTYgMTYiIHZlcnNpb249IjEuMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayI+CiAgICA8IS0tIEdlbmVyYXRvcjogU2tldGNoIDUzLjIgKDcyNjQzKSAtIGh0dHBzOi8vc2tldGNoYXBwLmNvbSAtLT4KICAgIDx0aXRsZT5pY29uLWNsb3NlPC90aXRsZT4KICAgIDxkZXNjPkNyZWF0ZWQgd2l0aCBTa2V0Y2guPC9kZXNjPgogICAgPGcgaWQ9Imljb24tY2xvc2UiIHN0cm9rZT0ibm9uZSIgc3Ryb2tlLXdpZHRoPSIxIiBmaWxsPSJub25lIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiPgogICAgICAgIDxwYXRoIGQ9Ik02LjU0NTQ1NDU1LDggTC0xLjU5NzM4ODg5ZS0xMiwxLjQ1NDU0NTQ1IEwxLjQ1NDU0NTQ1LC0xLjY0NDI0MDNlLTEyIEw4LDYuNTQ1NDU0NTUgTDE0LjU0NTQ1NDUsMS42NTIwMTE4NmUtMTIgTDE2LDEuNDU0NTQ1NDUgTDkuNDU0NTQ1NDUsOCBMMTYsMTQuNTQ1NDU0NSBMMTQuNTQ1NDU0NSwxNiBMOCw5LjQ1NDU0NTQ1IEwxLjQ1NDU0NTQ1LDE2IEwtMS42MDI0OTU5MWUtMTIsMTQuNTQ1NDU0NSBMNi41NDU0NTQ1NSw4IFoiIGlkPSJDb21iaW5lZC1TaGFwZSIgZmlsbD0iI0ZGRkZGRiI+PC9wYXRoPgogICAgPC9nPgo8L3N2Zz4=) no-repeat ;
  }
  .c0122 .c0111 {
    margin: 0;
    padding: 0;
  }
  .c0122 .c0111 div {
    padding: 10px 25px;
  }
  .c0122 .c0111 ul {
    max-height: initial;
  }
  .c0122 .c0111 li {
    color: #000;
    padding: 10px 25px;
  }
  .c0122 .c0110:nth-last-child(2) {
    border-bottom: 1px solid #4d4d4d;
  }
  .c0122 .c0110 a {
    color: #fff;
  }
  .c0118 {
    display: inline-flex;
    padding: 10px 25px;
    flex-basis: 50%;
  }
}
</style><style data-jss="" data-meta="t, Unthemed, Static">
.c0136 {
  display: inline;
}
.c0136 a {
  white-space: nowrap;
}
.c0137 {
  left: 0;
  width: 100%;
  color: #fff;
  bottom: 0;
  margin: 0 auto;
  z-index: 110;
  position: fixed;
  font-size: 14px;
  font-family: 'Open Sans','HelveticaNeue','HelveticaNeueu',Arial,sans-serif;
  background-color: #333;
}
</style><style data-jss="" data-meta="t, Unthemed, Static">
.c0123 {
  left: 0;
  width: 100%;
  bottom: 0;
  display: flex;
  padding: 60px 0;
  text-align: center;
  flex-direction: column;
  justify-content: center;
  background-color: #EFEFEF;
}
.c0124 {
  font-size: 1.3rem;
  font-weight: 200;
  padding-bottom: 30px;
}
.c0124 a {
  padding: 10px;
  border-color: #555555;
  border-style: solid;
  border-width: 1px;
  border-radius: 3px;
}
.c0124 a:visited, .c0124 a:hover, .c0124 a:active {
  color: #555555;
}
.c0125 {
  flex: 1;
  color: #6c6c6c;
  box-sizing: border-box;
  text-align: left;
  font-weight: 300;
  padding-left: 20px;
}
.c0126 {
  flex: 1;
  padding: 0;
  box-sizing: border-box;
  text-align: right;
}
.c0127 {
  color: #6c6c6c;
  display: inline-block;
  font-weight: 400;
}
.c0127 a:visited, .c0127 a:hover, .c0127 a:active {
  color: #6c6c6c;
  text-decoration: none;
}
.c0127:not(:first-of-type):before {
  width: 5px;
  height: 5px;
  margin: 0 10px 3px 10px;
  content: "";
  display: inline-block;
  border-radius: 50%;
  background-color: #6c6c6c;
}
.c0128 {
  display: flex;
  align-items: center;
  justify-content: center;
}
.c0129 {
  width: 24px;
  height: 24px;
  margin: 15px;
  display: inline-block;
}
.c0130 {
  width: 24px;
  height: 24px;
  margin: 15px;
  display: inline-block;
}
.c0131 {
  width: 24px;
  height: 24px;
  margin: 15px;
  display: inline-block;
}
.c0132 a {
  width: 24px;
  height: 24px;
  display: inline-block;
}
@media screen and (max-width:767px) {
  .c0128 {
    padding: 0 5px 0 5px;
    flex-wrap: wrap;
  }
  .c0126 {
    flex-basis: 100%;
    text-align: center;
  }
  .c0125 {
    text-align: center;
    padding-left: 0;
  }
}
</style><style data-jss="" data-meta="t, Unthemed, Dynamic">
.c0133 {

TimeoutException: Message:
Stacktrace:
0   chromedriver                        0x0000000104e4c6f8 chromedriver + 4982520
1   chromedriver                        0x0000000104e43df3 chromedriver + 4947443
2   chromedriver                        0x0000000104a001b6 chromedriver + 475574
3   chromedriver                        0x0000000104a439f0 chromedriver + 752112
4   chromedriver                        0x0000000104a43c51 chromedriver + 752721
5   chromedriver                        0x0000000104a87f34 chromedriver + 1031988
6   chromedriver                        0x0000000104a69c0d chromedriver + 908301
7   chromedriver                        0x0000000104a8522b chromedriver + 1020459
8   chromedriver                        0x0000000104a699b3 chromedriver + 907699
9   chromedriver                        0x0000000104a33acf chromedriver + 686799
10  chromedriver                        0x0000000104a34fee chromedriver + 692206
11  chromedriver                        0x0000000104e0811d chromedriver + 4702493
12  chromedriver                        0x0000000104e0d382 chromedriver + 4723586
13  chromedriver                        0x0000000104e13ebf chromedriver + 4751039
14  chromedriver                        0x0000000104e0e2fa chromedriver + 4727546
15  chromedriver                        0x0000000104de0aa2 chromedriver + 4541090
16  chromedriver                        0x0000000104e2dff8 chromedriver + 4857848
17  chromedriver                        0x0000000104e2e177 chromedriver + 4858231
18  chromedriver                        0x0000000104e3d71f chromedriver + 4921119
19  libsystem_pthread.dylib             0x00007ff811ded259 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff811de8c7b thread_start + 15

# Kindle

In [ ]:
import pandas as pd
from utils import time_difference_correction


df = pd.read_csv("exports/kindle_exports/Kindle_export_020523/Kindle.Devices.ReadingSession/Kindle.Devices.ReadingSession.csv")
df = df[df['start_timestamp']!="Not Available"]

In [ ]:
gr_df = df.groupby("ASIN").\
          aggregate({'start_timestamp' : 'min', 'end_timestamp' : 'max',\
                     'number_of_page_flips' : 'sum'}).reset_index()

In [ ]:
gr_df['Title'] = gr_df.ASIN.map(dict_ASIN)

NameError: name 'dict_ASIN' is not defined

In [ ]:
pd.set_option('display.max_columns', None)

,Book Id,Title,Author,Author l-f,Additional Authors,ISBN,ISBN13,My Rating,Average Rating,Publisher,Binding,Number of Pages,Year Published,Original Publication Year,Date Read,Date Added,Bookshelves,Bookshelves with positions,Exclusive Shelf,My Review,Spoiler,Private Notes,Read Count,Owned Copies,Date started,Date ended,reading_duration
5,4406,East of Eden,John Steinbeck,"Steinbeck, John",NaN,"=""0142000655""","=""9780142000656""",4,4.4,Penguin Books,Paperback,601.0,2002.0,1952.0,2023/03/22,2023/02/16,NaN,NaN,read,NaN,NaN,NaN,1,0,2023-03-07,2023-03-22,15.0

In [ ]:
def row_expander_minutes(row):
    minute_diff = (row['end_timestamp'] - row['start_timestamp']).total_seconds()/60
    if minute_diff <=1:
        date_df = pd.DataFrame(columns=['Title', 'Timestamp', 'Seconds', 'Pages'])
        new_row = {'Title' : row['Title'], 'Timestamp': row['start_timestamp'].floor('T'),\
                   'Seconds' : row["total_reading_millis"]/1000,\
                   'Pages' : row['actual_page_flip']}
        date_df = date_df.append(new_row, ignore_index=True)
        return date_df
    dates = pd.date_range(row['start_timestamp'], row['end_timestamp']- pd.Timedelta(minutes=1), freq='T')
    date_df = pd.DataFrame({'Timestamp': dates.floor('T')})
    date_df['Title'] = row['Title']
    date_df['Pages'] = row['actual_page_flip']/minute_diff
    for index, _ in date_df.iterrows():
        start_diff = (row['start_timestamp'] - row['start_timestamp'].floor('T'))\
                      .total_seconds()
        end_diff = (row['end_timestamp'] - row['end_timestamp'].floor('T'))\
                    .total_seconds()
        if index == 0:
            date_df.loc[index,'Seconds'] = 60- start_diff
        elif index == date_df.shape[0]-1:
            date_df.loc[index,'Seconds'] = end_diff
        else:
            date_df.loc[index,'Seconds'] = 60
    return date_df

In [ ]:
df = pd.read_csv('processed_files/kindle_processed.csv', sep = '|')
df = df[df['kindle_page_ratio'].notna()]
df['actual_page_flip'] = df['number_of_page_flips']/df['kindle_page_ratio']
new_df = pd.DataFrame(columns=['Title', 'Timestamp', 'Seconds', 'Pages'])
df['start_timestamp'] = pd.to_datetime(df['start_timestamp'])
df['end_timestamp'] = pd.to_datetime(df['end_timestamp'])
for _, row in df.iterrows():
    new_df = pd.concat([new_df, row_expander_minutes(row)], ignore_index=True)
new_df

,Title,Timestamp,Seconds,Pages
0,Le mage du Kremlin,2023-02-07 21:13:00,6.6,6.545455
1,Le mage du Kremlin,2023-02-07 21:13:00,2.5,1.636364
2,The Grapes of Wrath,2023-02-09 21:38:00,20.0,0.651445
3,The Grapes of Wrath,2023-02-09 21:39:00,60.0,0.651445
4,The Grapes of Wrath,2023-02-09 21:40:00,60.0,0.651445
...,...,...,...,...
3721,"King Leopold's Ghost: A Story of Greed, Terror...",2023-04-23 09:52:00,60.0,1.026784
3722,"King Leopold's Ghost: A Story of Greed, Terror...",2023-04-23 09:53:00,60.0,1.026784
3723,"King Leopold's Ghost: A Story of Greed, Terror...",2023-04-23 09:54:00,60.0,1.026784
3724,"King Leopold's Ghost: A Story of Greed, Terror...",2023-04-23 09:55:00,60.0,1.026784
3725,"King Leopold's Ghost: A Story of Greed, Terror...",2023-04-23 09:56:00,42.0,1.026784

In [ ]:
def kindle_ratio(kindle_pages, total_pages):
    return None if kindle_pages < 100 else kindle_pages/total_pages
merged.loc[merged['Title'] == 'Come as You Are', 'Number of Pages'] = 400
merged['kindle_page_ratio'] = merged.apply(lambda x: \
                                           kindle_ratio(x.number_of_page_flips, x['Number of Pages']), axis = 1)

In [ ]:
merged

,ASIN,start_timestamp,end_timestamp,number_of_page_flips,Title,uncapitalized_title,Number of Pages,kindle_page_ratio
0,B0048EK3VK,2022-12-26T18:41:58Z,2022-12-29T16:08:30Z,26.0,The Magus,the magus,656.0,NaN
1,B0048EK42S,2023-03-23T01:59:41Z,2023-03-27T05:03:52Z,445.0,The Collector,the collector,283.0,1.572438
2,B004KZOWEG,2023-04-12T10:12:25Z,2023-04-23T01:57:42Z,776.0,"King Leopold's Ghost: A Story of Greed, Terror...","king leopold's ghost: a story of greed, terror...",442.0,1.755656
3,B005ODY2YI,2022-12-26T18:23:35Z,2022-12-26T18:41:27Z,4.0,Wild Swans: Three Daughters of China,wild swans: three daughters of china,562.0,NaN
4,B08R2L2YM2,2023-02-19T21:03:34Z,2023-03-07T09:50:15Z,986.0,Wildland: The Making of America's Fury,wildland: the making of america's fury,465.0,2.120430
5,B09G6WDZ9J,2023-02-09T20:38:40Z,2023-02-16T11:31:00Z,752.0,The Grapes of Wrath,the grapes of wrath,479.0,1.569937
6,B09W2TF86M,2023-03-07T09:50:34Z,2023-03-23T00:02:24Z,1342.0,East Of Eden,east of eden,601.0,2.232945
7,B09WDY29NM,2023-02-07T20:13:29Z,2023-02-25T18:56:37Z,352.0,Le mage du Kremlin,le mage du kremlin,288.0,1.222222
8,B0C2K71L2W,2023-04-23T13:53:14Z,2023-04-23T15:30:15Z,24.0,The Fisherman,the fisherman,313.0,NaN
9,FXENY64FAQ3IBOXHJUGOA6XJNVDLJMCD,2023-03-27T09:05:23Z,2023-04-12T10:12:07Z,744.0,Come as You Are,come as you are,400.0,1.860000

In [ ]:
dict_ASIN = {}

In [ ]:
import json

# Assume 'my_dict' is the dictionary you want to save to a file
filename = 'ASIN_dictionnary.json'  # Specify the name of the output file
with open(filename, 'w') as f:
    json.dump(dict_ASIN, f)  # Write the dictionary to the output file
# Assume 'filename' is the name of the file containing the dictionary
with open(filename, 'r') as f:
    my_dict = json.load(f)  # Load the dictionary from the input file
my_dict

{'B0048EK3VK': 'The Magus',
 'B0048EK42S': 'The Collector',
 'B004KZOWEG': "King Leopold's Ghost: A Story of Greed, Terror, and Heroism in Colonial Africa",
 'B005ODY2YI': 'Wild Swans: Three Daughters of China',
 'B08R2L2YM2': "Wildland: The Making of America's Fury",
 'B09G6WDZ9J': 'Grapes of wrath',
 'B09W2TF86M': 'East Of Eden',
 'B09WDY29NM': 'Le mage du Kremlin',
 'B0C2K71L2W': 'The Fisherman',
 'FXENY64FAQ3IBOXHJUGOA6XJNVDLJMCD': 'Come as You Are'}

In [ ]:
gr_df[gr_df['ASIN']==ASIN].start_timestamp.unique())

[numpy.datetime64('2023-03-23T00:00:00.000000000')]

In [ ]:
import requests
import time
from bs4 import BeautifulSoup
for ASIN in list(gr_df.ASIN.unique()):
    if ASIN in dict_ASIN.keys():
        continue
    url = f"https://www.amazon.fr/s?k={ASIN}&__mk_fr_FR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=MCGNNB0G7BY7&sprefix=b09g6wdz9j%2Caps%2C663&ref=nb_sb_noss"
    html = requests.get(url)
    soup = BeautifulSoup(html.text)
    title = soup.find('span', class_='a-size-base-plus a-color-base a-text-normal').text.strip()
    print(f"Started reading on {gr_df[gr_df['ASIN']==ASIN].start_timestamp.dt.date} \n")
    print(f"Amazon scraped is {title.split('(')[0].strip()}\n")
    confirmation = input('Is this the correct title? OK if yes, else NOK: ')
    print('\n')
    if confirmation == 'OK': 
        dict_ASIN[ASIN] = title.split('(')[0].strip()
    else:
        print('\n')
        new_title = input('Input the actual title: ')
        dict_ASIN[ASIN] = new_title   
    time.sleep(2)

Started reading on 8    2023-04-23
Name: start_timestamp, dtype: object

Amazon scraped is EZVALO LED Lampe de Placard 40cm à Détecteur de Mouvement Intérieur, Réglette LED Cuisine sans Fil, Lumière D'armoire 3500K avec 3 Modes d’Éclairage, Rechargeable par USB, LED Veilleuse - 1 Pack

Is this the correct title? OK if yes, else NOK: NOK




Input the actual title: The Fisherman
Started reading on 9    2023-03-27
Name: start_timestamp, dtype: object

Amazon scraped is TNGXXWL Sweat-shirt à capuche surdimensionné pour femme Y2k avec fermeture éclair pour pull esthétique avec portrait vintage 90S

Is this the correct title? OK if yes, else NOK: NOK




Input the actual title: Come as You Are

In [ ]:
import json

# Assume 'my_dict' is the dictionary you want to save to a file
filename = 'work_files/kindle_ASIN_dictionnary.json'  # Specify the name of the output file
with open(filename, 'w') as f:
    json.dump(dict_ASIN, f)  # Write the dictionary to the output file
# Assume 'filename' is the name of the file containing the dictionary
with open(filename, 'r') as f:
    my_dict = json.load(f)  # Load the dictionary from the input file
my_dict

{'B0048EK3VK': 'The Magus',
 'B0048EK42S': 'The Collector',
 'B004KZOWEG': "King Leopold's Ghost: A Story of Greed, Terror, and Heroism in Colonial Africa",
 'B005ODY2YI': 'Wild Swans: Three Daughters of China',
 'B08R2L2YM2': "Wildland: The Making of America's Fury",
 'B09G6WDZ9J': 'The Grapes of Wrath',
 'B09W2TF86M': 'East Of Eden',
 'B09WDY29NM': 'Le mage du Kremlin',
 'B0C2K71L2W': 'The Fisherman',
 'FXENY64FAQ3IBOXHJUGOA6XJNVDLJMCD': 'Come as You Are'}

In [ ]:
df_gr = pd.read_excel("exports/goodreads_exports/gr_dates_input.xlsx")
df_gr['start_timestamp'] = pd.to_datetime(df_gr['Date started'])
gr_df['start_timestamp'] = pd.to_datetime(gr_df['start_timestamp'])

In [ ]:
df_gr

,Book Id,Title,Date started,Date ended,start_timestamp
0,767171.0,The Rise and Fall of the Third Reich: A Histor...,2021-12-10,2022-01-09,2021-12-10
1,58300343.0,Le monde en 2040 vu par la CIA: Un monde plus ...,2022-01-10,2022-01-19,2022-01-10
2,59662073.0,Une journée particulière,2022-01-20,2022-01-28,2022-01-20
3,49481192.0,Si la Chine était un village,2022-01-30,2022-02-01,2022-01-30
4,54869368.0,Yoga,2022-02-10,2022-02-14,2022-02-10
5,40718726.0,Genghis Khan and the Making of the Modern World,2022-02-15,2022-02-23,2022-02-15
6,58966904.0,Les Grands jours qui ont changé l'Amérique,2022-02-24,2022-03-02,2022-02-24
7,36205412.0,"Angela Merkel, l'ovni politique",2022-03-03,2022-02-09,2022-03-03
8,318431.0,Long Walk to Freedom,2022-03-03,2022-03-11,2022-03-03
9,12283366.0,Les services secrets chinois : De Mao à nos jours,2022-03-13,2022-03-21,2022-03-13
10,43890142.0,Un printemps à Téhéran (French Edition),2022-03-22,2022-03-24,2022-03-22
11,48589917.0,La Republique de Chine: Histoire Generale de l...,2022-03-28,2022-05-05,2022-03-28
12,76401.0,Bury My Heart at Wounded Knee: An Indian Histo...,2022-04-05,2022-04-10,2022-04-05
13,2212686.0,"Young Stalin (Joseph Stalin, #1)",2022-04-13,2022-04-29,2022-04-13
14,19183700.0,La Fin de l'homme rouge,2022-05-02,2022-05-17,2022-05-02
15,56750097.0,The Burgundians: A Vanished Empire,2022-05-18,2022-06-16,2022-05-18
16,57833635.0,Somnolences,2022-06-17,2022-06-17,2022-06-17
17,58561459.0,"À la table des tyrans: Mao, Hitler, Bokassa, S...",2022-06-26,2022-06-28,2022-06-26
18,282108.0,Stalin: The Court of the Red Tsar,2022-07-04,2022-07-18,2022-07-04
19,60898797.0,Taïwan face à la Chine,2022-07-19,2022-07-27,2022-07-19
20,33877608.0,Eat the Buddha: Life and Death in a Tibetan Town,2022-07-30,2022-08-06,2022-07-30
21,53349836.0,Mémoires de guerre Tome 1: 1919 - 1941 (Texto),2022-08-06,2022-08-19,2022-08-06
22,30983387.0,"The Girl with the Dragon Tattoo (Millennium, #1)",2022-08-20,2022-08-23,2022-08-20
23,40106669.0,"The Girl Who Played with Fire (Millennium, #2)",2022-08-24,2022-08-30,2022-08-24
24,33288926.0,The Girl Who Kicked the Hornet's Nest,2022-09-02,2022-09-10,2022-09-02
25,60638014.0,Mobutu,2022-09-13,2022-09-18,2022-09-13
26,26535513.0,Storytelling with Data: A Data Visualization G...,2022-09-18,2022-09-24,2022-09-18
27,58625120.0,"Mémoires de guerre : Tome 2, Février 1941-1945...",2022-09-25,2022-10-08,2022-09-25
28,60731116.0,L'Art de la guerre,2022-10-09,2022-10-13,2022-10-09
29,52709651.0,Une vie comme les autres,2022-10-17,2022-10-26,2022-10-17
30,49151008.0,"Made in China: A Prisoner, an SOS Letter, and ...",2022-10-29,2022-10-31,2022-10-29
31,61330158.0,Disparaître,2022-11-01,2022-11-03,2022-11-01
32,57330020.0,MBS: The Rise to Power of Mohammad Bin Salman,2022-11-05,2022-11-13,2022-11-05
33,43868109.0,Empire of Pain: The Secret History of the Sack...,2022-11-16,2022-11-28,2022-11-16
34,61217741.0,On était des loups,2022-12-01,2022-12-03,2022-12-01
35,62995876.0,Rupert Murdoch. L'empereur des médias qui mani...,2022-12-05,2022-12-09,2022-12-05
36,53176763.0,"Three Tigers, One Mountain: A Journey through ...",2022-12-11,2022-12-24,2022-12-11
37,1848.0,Wild Swans: Three Daughters of China,2022-12-26,2022-01-15,2022-12-26
38,816085.0,Harvest Home,2022-12-30,2022-01-01,2022-12-30
39,58938609.0,Hidden Pictures,2023-01-22,2023-01-23,2023-01-22
40,51285366.0,The House of Kennedy,2023-01-24,2023-01-31,2023-01-24
41,16286.0,The Magus,2023-01-31,2023-02-06,2023-01-31
42,18114322.0,The Grapes of Wrath,2023-02-07,2023-02-16,2023-02-07
43,122716306.0,Poutine ou l'obsession de la puissance,2023-02-18,2023-02-19,2023-02-18
44,56269283.0,Wildland: The Making of America's Fury,2023-02-19,2023-03-07,2023-02-19
45,60882951.0,Le Mage du Kremlin,2023-02-24,2023-02-24,2023-02-24
46,4406.0,East of Eden,2023-03-07,2023-03-22,2023-03-07
47,243705.0,The Collector,2023-03-22,2023-03-26,2023-03-22
48,NaN,Come as You Are,2023-03-27,2023-04-12,2023-03-27
49,40961621.0,"King Leopold's Ghost: A Story of Greed, Terro...",2023-04-12,2023-04-22,2023-04-12
50,131942420.0,The Fisherman,2023-04-23,2023-04-27,2023-04-23

In [ ]:
gr_df

,ASIN,start_timestamp,end_timestamp,number_of_page_flips
0,B0048EK3VK,2022-12-26,2022-12-29,26.0
1,B0048EK42S,2023-03-23,2023-03-27,445.0
2,B004KZOWEG,2023-04-12,2023-04-23,776.0
3,B005ODY2YI,2022-12-26,2022-12-26,4.0
4,B08R2L2YM2,2023-02-19,2023-03-07,986.0
5,B09G6WDZ9J,2023-02-09,2023-02-16,752.0
6,B09W2TF86M,2023-03-07,2023-03-23,1342.0
7,B09WDY29NM,2023-02-07,2023-02-25,352.0
8,B0C2K71L2W,2023-04-23,2023-04-23,24.0
9,FXENY64FAQ3IBOXHJUGOA6XJNVDLJMCD,2023-03-27,2023-04-12,744.0

In [ ]:
pd.merge(gr_df[['ASIN', 'start_timestamp']], df_gr[['start_timestamp', 'Title']],\
         on = 'start_timestamp', how = 'left')

,ASIN,start_timestamp,Title
0,B0048EK3VK,2022-12-26,Wild Swans: Three Daughters of China
1,B0048EK42S,2023-03-23,NaN
2,B004KZOWEG,2023-04-12,"King Leopold's Ghost: A Story of Greed, Terro..."
3,B005ODY2YI,2022-12-26,Wild Swans: Three Daughters of China
4,B08R2L2YM2,2023-02-19,Wildland: The Making of America's Fury
5,B09G6WDZ9J,2023-02-09,NaN
6,B09W2TF86M,2023-03-07,East of Eden
7,B09WDY29NM,2023-02-07,The Grapes of Wrath
8,B0C2K71L2W,2023-04-23,The Fisherman
9,FXENY64FAQ3IBOXHJUGOA6XJNVDLJMCD,2023-03-27,Come as You Are

In [ ]:
gr_df.sort_values('start_timestamp')

,start_timestamp,end_timestamp,number_of_page_flips,Date started
ASIN,,,,
B005ODY2YI,2022-12-26 19:23:35,2022-12-26T18:41:27Z,4.0,2022-12-26 19:23:35
B0048EK3VK,2022-12-26 19:41:58,2022-12-29T16:08:30Z,26.0,2022-12-26 19:41:58
B09WDY29NM,2023-02-07 21:13:29,2023-02-25T18:56:37Z,352.0,2023-02-07 21:13:29
B09G6WDZ9J,2023-02-09 21:38:40,2023-02-16T11:31:00Z,752.0,2023-02-09 21:38:40
B08R2L2YM2,2023-02-19 22:03:34,2023-03-07T09:50:15Z,986.0,2023-02-19 22:03:34
B09W2TF86M,2023-03-07 17:50:34,2023-03-23T00:02:24Z,1342.0,2023-03-07 17:50:34
B0048EK42S,2023-03-23 09:59:41,2023-03-27T05:03:52Z,445.0,2023-03-23 09:59:41
FXENY64FAQ3IBOXHJUGOA6XJNVDLJMCD,2023-03-27 17:05:23,2023-04-12T10:12:07Z,744.0,2023-03-27 17:05:23
B004KZOWEG,2023-04-12 18:12:25,2023-04-23T01:57:42Z,776.0,2023-04-12 18:12:25
B0C2K71L2W,2023-04-23 21:53:14,2023-04-23T15:30:15Z,24.0,2023-04-23 21:53:14

In [ ]:
df = df[df['Date started'].notna()]

In [ ]:
df.sort_values('Date started')

,Book Id,Title,Date started,Date ended
0,767171.0,The Rise and Fall of the Third Reich: A Histor...,2021-12-10,2022-01-09
1,58300343.0,Le monde en 2040 vu par la CIA: Un monde plus ...,2022-01-10,2022-01-19
2,59662073.0,Une journée particulière,2022-01-20,2022-01-28
3,49481192.0,Si la Chine était un village,2022-01-30,2022-02-01
4,54869368.0,Yoga,2022-02-10,2022-02-14
5,40718726.0,Genghis Khan and the Making of the Modern World,2022-02-15,2022-02-23
6,58966904.0,Les Grands jours qui ont changé l'Amérique,2022-02-24,2022-03-02
7,36205412.0,"Angela Merkel, l'ovni politique",2022-03-03,2022-02-09
8,318431.0,Long Walk to Freedom,2022-03-03,2022-03-11
9,12283366.0,Les services secrets chinois : De Mao à nos jours,2022-03-13,2022-03-21
10,43890142.0,Un printemps à Téhéran (French Edition),2022-03-22,2022-03-24
11,48589917.0,La Republique de Chine: Histoire Generale de l...,2022-03-28,2022-05-05
12,76401.0,Bury My Heart at Wounded Knee: An Indian Histo...,2022-04-05,2022-04-10
13,2212686.0,"Young Stalin (Joseph Stalin, #1)",2022-04-13,2022-04-29
14,19183700.0,La Fin de l'homme rouge,2022-05-02,2022-05-17
15,56750097.0,The Burgundians: A Vanished Empire,2022-05-18,2022-06-16
16,57833635.0,Somnolences,2022-06-17,2022-06-17
17,58561459.0,"À la table des tyrans: Mao, Hitler, Bokassa, S...",2022-06-26,2022-06-28
18,282108.0,Stalin: The Court of the Red Tsar,2022-07-04,2022-07-18
19,60898797.0,Taïwan face à la Chine,2022-07-19,2022-07-27
20,33877608.0,Eat the Buddha: Life and Death in a Tibetan Town,2022-07-30,2022-08-06
21,53349836.0,Mémoires de guerre Tome 1: 1919 - 1941 (Texto),2022-08-06,2022-08-19
22,30983387.0,"The Girl with the Dragon Tattoo (Millennium, #1)",2022-08-20,2022-08-23
23,40106669.0,"The Girl Who Played with Fire (Millennium, #2)",2022-08-24,2022-08-30
24,33288926.0,The Girl Who Kicked the Hornet's Nest,2022-09-02,2022-09-10
25,60638014.0,Mobutu,2022-09-13,2022-09-18
26,26535513.0,Storytelling with Data: A Data Visualization G...,2022-09-18,2022-09-24
27,58625120.0,"Mémoires de guerre : Tome 2, Février 1941-1945...",2022-09-25,2022-10-08
28,60731116.0,L'Art de la guerre,2022-10-09,2022-10-13
29,52709651.0,Une vie comme les autres,2022-10-17,2022-10-26
30,49151008.0,"Made in China: A Prisoner, an SOS Letter, and ...",2022-10-29,2022-10-31
31,61330158.0,Disparaître,2022-11-01,2022-11-03
32,57330020.0,MBS: The Rise to Power of Mohammad Bin Salman,2022-11-05,2022-11-13
33,43868109.0,Empire of Pain: The Secret History of the Sack...,2022-11-16,2022-11-28
34,61217741.0,On était des loups,2022-12-01,2022-12-03
35,62995876.0,Rupert Murdoch. L'empereur des médias qui mani...,2022-12-05,2022-12-09
36,53176763.0,"Three Tigers, One Mountain: A Journey through ...",2022-12-11,2022-12-24
37,1848.0,Wild Swans: Three Daughters of China,2022-12-26,2022-01-15
38,816085.0,Harvest Home,2022-12-30,2022-01-01
39,58938609.0,Hidden Pictures,2023-01-22,2023-01-23
40,51285366.0,The House of Kennedy,2023-01-24,2023-01-31
41,16286.0,The Magus,2023-01-31,2023-02-06
42,18114322.0,The Grapes of Wrath,2023-02-07,2023-02-16
43,122716306.0,Poutine ou l'obsession de la puissance,2023-02-18,2023-02-19
44,56269283.0,Wildland: The Making of America's Fury,2023-02-19,2023-03-07
45,60882951.0,Le Mage du Kremlin,2023-02-24,2023-02-24
46,4406.0,East of Eden,2023-03-07,2023-03-22
47,243705.0,The Collector,2023-03-22,2023-03-26
48,NaN,Come as You Are,2023-03-27,2023-04-11
49,40961621.0,"King Leopold's Ghost: A Story of Greed, Terro...",2023-04-12,2023-04-22
50,131942420.0,The Fisherman,2023-04-23,2023-04-27

In [ ]:
import requests

asin = "B005ODY2YI"
api_key = "AIzaSyD6HOZiIGEQgQYQd9lVoDqcBfFMqi15dHQ"

# Make the API request
response = requests.get(f"https://www.googleapis.com/books/v1/volumes?q=asin:{asin}&key={api_key}")

# Check if the request was successful
if response.status_code == 200:
    # Parse the JSON response and extract the title of the book
    data = response.json()
    title = data["items"][0]["volumeInfo"]["title"]
    print(title)
else:
    print("Error:", response.status_code)

Error: 403

In [ ]:
gr_df.sort_values('Date started')

,start_timestamp,end_timestamp,number_of_page_flips,Date started
ASIN,,,,
B005ODY2YI,2022-12-26T18:23:35Z,2022-12-26T18:41:27Z,4.0,2022-12-26 18:23:35+00:00
B0048EK3VK,2022-12-26T18:41:58Z,2022-12-29T16:08:30Z,26.0,2022-12-26 18:41:58+00:00
B09WDY29NM,2023-02-07T20:13:29Z,2023-02-25T18:56:37Z,352.0,2023-02-07 20:13:29+00:00
B09G6WDZ9J,2023-02-09T20:38:40Z,2023-02-16T11:31:00Z,752.0,2023-02-09 20:38:40+00:00
B08R2L2YM2,2023-02-19T21:03:34Z,2023-03-07T09:50:15Z,986.0,2023-02-19 21:03:34+00:00
B09W2TF86M,2023-03-07T09:50:34Z,2023-03-23T00:02:24Z,1342.0,2023-03-07 09:50:34+00:00
B0048EK42S,2023-03-23T01:59:41Z,2023-03-27T05:03:52Z,445.0,2023-03-23 01:59:41+00:00
FXENY64FAQ3IBOXHJUGOA6XJNVDLJMCD,2023-03-27T09:05:23Z,2023-04-12T10:12:07Z,744.0,2023-03-27 09:05:23+00:00
B004KZOWEG,2023-04-12T10:12:25Z,2023-04-23T01:57:42Z,776.0,2023-04-12 10:12:25+00:00
B0C2K71L2W,2023-04-23T13:53:14Z,2023-04-23T15:30:15Z,24.0,2023-04-23 13:53:14+00:00

In [ ]:
pd.merge(df, gr_df, on = 'Date started', how = 'outer')

ValueError: You are trying to merge on datetime64[ns] and datetime64[ns, UTC] columns. If you wish to proceed you should use pd.concat

# OffScreen

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("exports/offscreen_export/2023-04-27 00:12:52 +0000-Pickup.csv")

In [ ]:
def row_expander_seconds(row):
    lower_bound = (row['start']-pd.Timedelta(seconds = 30)).round('T')
    upper_bound = (row['end']-pd.Timedelta(seconds = 30)).round('T')
    rows_needed = (int((upper_bound-lower_bound).total_seconds()/60))+1
    if rows_needed ==1:
        date_df = pd.DataFrame(columns=['date', 'screen_time'])
        new_row = {'date': lower_bound, 'screen_time' : row["duration_s"], 'pickups' : 1}
        date_df = date_df.append(new_row, ignore_index=True)
        return date_df
    dates = pd.date_range(lower_bound, upper_bound, freq='T')
    date_df = pd.DataFrame({'date': dates})
    for minute in range(1, rows_needed+1, 1):
        if minute == 1:
            seconds = (lower_bound + pd.Timedelta(minutes = 1) - row["start"]).total_seconds()
            pickup = 1
        elif minute != rows_needed:
            seconds = 60
            pickup = 0
        else:
            seconds = (row["end"] - upper_bound).total_seconds()
            pickup = 0
        date_df.loc[minute-1,'screen_time'] = seconds
        date_df.loc[minute-1,'pickups'] = pickup
    return date_df

def expand_df(df):
    df['start'] = pd.to_datetime(df['start']) + pd.Timedelta(hours = 8)
    df['end'] = pd.to_datetime(df['end']) + pd.Timedelta(hours = 8)
    df['duration_s'] = (df.end - df.start).dt.total_seconds().astype(float)
    new_df = pd.DataFrame(columns=['date', 'screen_time', 'pickups'])
    #old_df = pd.read_csv(path, sep = '|').rename(columns = {name_val : 'val'})
    #new_df = pd.concat([new_df, old_df], ignore_index=True)
    #df = df[df["@startDate"]>max(old_df["date"])].reset_index(drop=True)
    print(f'{df.shape[0]} new rows to expand')
    for _, row in df.iterrows():
        new_df = pd.concat([new_df, row_expander_seconds(row)], ignore_index=True)
    new_df['date'] = pd.to_datetime(new_df['date'])
    new_df = new_df.groupby('date').sum().reset_index()
    new_df
    return new_df

In [ ]:
df

,id,deviceId,start,end,isIgnoredForSleepTime
0,A3AEFAEB-6DF5-4381-BD9C-6FA7AF6263BE,1BDEA1A1-C549-49B6-9789-60B1A22F8F8C,2023-04-25 07:06:28 +0000,2023-04-25 07:06:41 +0000,False
1,CACD423C-59A7-4C5B-86EB-E655462621EE,1BDEA1A1-C549-49B6-9789-60B1A22F8F8C,2023-04-25 07:21:28 +0000,2023-04-25 07:21:36 +0000,False
2,18081DBC-0ADC-497C-9ACC-6AC31B067D8A,1BDEA1A1-C549-49B6-9789-60B1A22F8F8C,2023-04-25 23:23:31 +0000,2023-04-25 23:24:16 +0000,False
3,8EF8917F-D930-4B3D-B229-4687052471E0,1BDEA1A1-C549-49B6-9789-60B1A22F8F8C,2023-04-26 09:38:15 +0000,2023-04-26 09:38:27 +0000,False
4,3D29F625-2385-4F01-8536-B38750944DF5,1BDEA1A1-C549-49B6-9789-60B1A22F8F8C,2023-04-26 14:37:02 +0000,2023-04-26 14:37:27 +0000,False
...,...,...,...,...,...
110,3438CD57-1B48-47F4-BDA4-B1EB7889946C,1BDEA1A1-C549-49B6-9789-60B1A22F8F8C,2023-04-27 00:12:42 +0000,2023-04-27 00:12:48 +0000,False
111,13B78682-FA71-47AA-8AFA-F01FE4935541,1BDEA1A1-C549-49B6-9789-60B1A22F8F8C,2023-04-25 05:23:16 +0000,2023-04-25 05:23:53 +0000,False
112,8F2A94F2-F9C1-47ED-A1B8-EA6956C56C2E,1BDEA1A1-C549-49B6-9789-60B1A22F8F8C,2023-04-26 13:39:30 +0000,2023-04-26 13:41:48 +0000,False
113,D6951F28-CA12-4D50-BBF1-7B8ED2896721,1BDEA1A1-C549-49B6-9789-60B1A22F8F8C,2023-04-25 11:41:30 +0000,2023-04-25 11:41:48 +0000,False
114,5789F190-1799-46A9-90FE-C12371155BA5,1BDEA1A1-C549-49B6-9789-60B1A22F8F8C,2023-04-26 07:43:38 +0000,2023-04-26 07:47:33 +0000,False

In [ ]:
df

,id,deviceId,start,end,isIgnoredForSleepTime,duration_s
0,A3AEFAEB-6DF5-4381-BD9C-6FA7AF6263BE,1BDEA1A1-C549-49B6-9789-60B1A22F8F8C,2023-04-25 23:06:28+00:00,2023-04-25 23:06:41+00:00,False,13.0
1,CACD423C-59A7-4C5B-86EB-E655462621EE,1BDEA1A1-C549-49B6-9789-60B1A22F8F8C,2023-04-25 23:21:28+00:00,2023-04-25 23:21:36+00:00,False,8.0
2,18081DBC-0ADC-497C-9ACC-6AC31B067D8A,1BDEA1A1-C549-49B6-9789-60B1A22F8F8C,2023-04-26 15:23:31+00:00,2023-04-26 15:24:16+00:00,False,45.0
3,8EF8917F-D930-4B3D-B229-4687052471E0,1BDEA1A1-C549-49B6-9789-60B1A22F8F8C,2023-04-27 01:38:15+00:00,2023-04-27 01:38:27+00:00,False,12.0
4,3D29F625-2385-4F01-8536-B38750944DF5,1BDEA1A1-C549-49B6-9789-60B1A22F8F8C,2023-04-27 06:37:02+00:00,2023-04-27 06:37:27+00:00,False,25.0
...,...,...,...,...,...,...
110,3438CD57-1B48-47F4-BDA4-B1EB7889946C,1BDEA1A1-C549-49B6-9789-60B1A22F8F8C,2023-04-27 16:12:42+00:00,2023-04-27 16:12:48+00:00,False,6.0
111,13B78682-FA71-47AA-8AFA-F01FE4935541,1BDEA1A1-C549-49B6-9789-60B1A22F8F8C,2023-04-25 21:23:16+00:00,2023-04-25 21:23:53+00:00,False,37.0
112,8F2A94F2-F9C1-47ED-A1B8-EA6956C56C2E,1BDEA1A1-C549-49B6-9789-60B1A22F8F8C,2023-04-27 05:39:30+00:00,2023-04-27 05:41:48+00:00,False,138.0
113,D6951F28-CA12-4D50-BBF1-7B8ED2896721,1BDEA1A1-C549-49B6-9789-60B1A22F8F8C,2023-04-26 03:41:30+00:00,2023-04-26 03:41:48+00:00,False,18.0
114,5789F190-1799-46A9-90FE-C12371155BA5,1BDEA1A1-C549-49B6-9789-60B1A22F8F8C,2023-04-26 23:43:38+00:00,2023-04-26 23:47:33+00:00,False,235.0

In [ ]:
expand_df(df).pickups.sum()

115 new rows to expand

115.0

In [ ]:
df.sort_values('start')

,id,deviceId,start,end,isIgnoredForSleepTime,duration_s,start_h,start_d
22,EB35D872-F6BC-47A3-BE77-40CD960496AC,1BDEA1A1-C549-49B6-9789-60B1A22F8F8C,2023-04-26 13:08:30+00:00,2023-04-26 13:10:26+00:00,False,116.0,2023-04-25 13:00:00+00:00,2023-04-25
105,F8B34641-9978-4A41-AE61-E3B859A45220,1BDEA1A1-C549-49B6-9789-60B1A22F8F8C,2023-04-26 13:10:40+00:00,2023-04-26 13:11:22+00:00,False,42.0,2023-04-25 13:00:00+00:00,2023-04-25
104,FBECEC3A-AA10-4A7C-B8B4-1D078C667C5A,1BDEA1A1-C549-49B6-9789-60B1A22F8F8C,2023-04-26 13:11:38+00:00,2023-04-26 13:12:10+00:00,False,32.0,2023-04-25 13:00:00+00:00,2023-04-25
91,D1B1103E-400F-4647-A93A-95C7134DEA9E,1BDEA1A1-C549-49B6-9789-60B1A22F8F8C,2023-04-26 13:15:34+00:00,2023-04-26 13:16:26+00:00,False,52.0,2023-04-25 13:00:00+00:00,2023-04-25
26,0F0F98C5-6F34-4D40-A8F3-5170B5E48D45,1BDEA1A1-C549-49B6-9789-60B1A22F8F8C,2023-04-26 13:18:53+00:00,2023-04-26 13:20:36+00:00,False,103.0,2023-04-25 13:00:00+00:00,2023-04-25
...,...,...,...,...,...,...,...,...
66,4BA43474-7EEE-4844-B1B0-C111C3659264,1BDEA1A1-C549-49B6-9789-60B1A22F8F8C,2023-04-28 07:29:42+00:00,2023-04-28 07:30:02+00:00,False,20.0,2023-04-27 07:00:00+00:00,2023-04-27
88,AD65304E-648F-4D29-A219-BC7859C2F486,1BDEA1A1-C549-49B6-9789-60B1A22F8F8C,2023-04-28 07:42:58+00:00,2023-04-28 07:43:14+00:00,False,16.0,2023-04-27 08:00:00+00:00,2023-04-27
20,5E61D9B3-725C-4790-8AF0-D8776343974A,1BDEA1A1-C549-49B6-9789-60B1A22F8F8C,2023-04-28 07:45:27+00:00,2023-04-28 07:45:56+00:00,False,29.0,2023-04-27 08:00:00+00:00,2023-04-27
70,A394BB4A-0CBF-43B0-9F62-33DFE35F032F,1BDEA1A1-C549-49B6-9789-60B1A22F8F8C,2023-04-28 08:03:00+00:00,2023-04-28 08:08:15+00:00,False,315.0,2023-04-27 08:00:00+00:00,2023-04-27
110,3438CD57-1B48-47F4-BDA4-B1EB7889946C,1BDEA1A1-C549-49B6-9789-60B1A22F8F8C,2023-04-28 08:12:42+00:00,2023-04-28 08:12:48+00:00,False,6.0,2023-04-27 08:00:00+00:00,2023-04-27

In [ ]:
expand_df(df).sort_values('date')

115 new rows to expand

                         date  screen_time
42  2023-04-26 13:08:00+00:00    39.545455
43  2023-04-26 13:09:00+00:00    39.545455
44  2023-04-26 13:10:00+00:00    39.545455
245 2023-04-26 13:11:00+00:00    24.705882
244 2023-04-26 13:12:00+00:00    20.869565
..                        ...          ...
155 2023-04-28 08:05:00+00:00    50.400000
156 2023-04-28 08:06:00+00:00    50.400000
157 2023-04-28 08:07:00+00:00    50.400000
158 2023-04-28 08:08:00+00:00    50.400000
257 2023-04-28 08:13:00+00:00     5.454545

[269 rows x 2 columns]

In [ ]:
df

,id,deviceId,start,end,isIgnoredForSleepTime,duration_s
0,A3AEFAEB-6DF5-4381-BD9C-6FA7AF6263BE,1BDEA1A1-C549-49B6-9789-60B1A22F8F8C,2023-04-25 15:06:28+00:00,2023-04-25 15:06:41+00:00,False,13.0
1,CACD423C-59A7-4C5B-86EB-E655462621EE,1BDEA1A1-C549-49B6-9789-60B1A22F8F8C,2023-04-25 15:21:28+00:00,2023-04-25 15:21:36+00:00,False,8.0
2,18081DBC-0ADC-497C-9ACC-6AC31B067D8A,1BDEA1A1-C549-49B6-9789-60B1A22F8F8C,2023-04-26 07:23:31+00:00,2023-04-26 07:24:16+00:00,False,45.0
3,8EF8917F-D930-4B3D-B229-4687052471E0,1BDEA1A1-C549-49B6-9789-60B1A22F8F8C,2023-04-26 17:38:15+00:00,2023-04-26 17:38:27+00:00,False,12.0
4,3D29F625-2385-4F01-8536-B38750944DF5,1BDEA1A1-C549-49B6-9789-60B1A22F8F8C,2023-04-26 22:37:02+00:00,2023-04-26 22:37:27+00:00,False,25.0
...,...,...,...,...,...,...
110,3438CD57-1B48-47F4-BDA4-B1EB7889946C,1BDEA1A1-C549-49B6-9789-60B1A22F8F8C,2023-04-27 08:12:42+00:00,2023-04-27 08:12:48+00:00,False,6.0
111,13B78682-FA71-47AA-8AFA-F01FE4935541,1BDEA1A1-C549-49B6-9789-60B1A22F8F8C,2023-04-25 13:23:16+00:00,2023-04-25 13:23:53+00:00,False,37.0
112,8F2A94F2-F9C1-47ED-A1B8-EA6956C56C2E,1BDEA1A1-C549-49B6-9789-60B1A22F8F8C,2023-04-26 21:39:30+00:00,2023-04-26 21:41:48+00:00,False,138.0
113,D6951F28-CA12-4D50-BBF1-7B8ED2896721,1BDEA1A1-C549-49B6-9789-60B1A22F8F8C,2023-04-25 19:41:30+00:00,2023-04-25 19:41:48+00:00,False,18.0
114,5789F190-1799-46A9-90FE-C12371155BA5,1BDEA1A1-C549-49B6-9789-60B1A22F8F8C,2023-04-26 15:43:38+00:00,2023-04-26 15:47:33+00:00,False,235.0

In [ ]:
df['start_h'] = df['start'].dt.round('H')
df['start_d'] = df['start'].dt.date

In [ ]:
df[['start_d', 'duration_s']].groupby('start_d').sum()

            duration_s
start_d
2023-04-25      3004.0
2023-04-26      5466.0
2023-04-27       721.0

# Open AI tests

## Nutrilio

In [5]:
import pandas as pd
import datetime
import os
from openai import OpenAI
from datetime import datetime
from dotenv import load_dotenv
load_dotenv()

True

In [6]:
api_key = os.environ['OpenAI_Key']
client = OpenAI(api_key = api_key)

In [7]:
def get_response(client, system_prompt, user_prompt):
  # Assign the role and content for each message
  messages = [{"role": "system", "content": system_prompt},
      		  {"role": "user", "content": user_prompt}]
  response = client.chat.completions.create(
      model="gpt-3.5-turbo", messages= messages, temperature=0)
  return response.choices[0].message.content

In [9]:
get_response(client,"You are a sarcastic chatbot", "Tell me a joke")

"Sure, here's one for you: Why don't scientists trust atoms? Because they make up everything!"

In [11]:
df = pd.read_csv("../test.csv", sep = '|')

/Users/valen/.pyenv/versions/3.8.13/envs/lewagon/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3457: DtypeWarning: Columns (11,18,23) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [17]:
def generate_calory_needs():
    """Generates the calory needs of a person based on the variables declared above"""
    #Calculate the BMR using the Harris-Benedict equation
    bmr = 88.36 + (13.4 * weight_kg) + (4.8 * height_cm) - (5.7 * age)
    # Calculate the daily calorie needs by multiplying the BMR by the activity factor
    daily_calorie_needs = round(bmr * activity_factor)
    # Calculate the calorie breakdown for each meal and snack
    breakfast_calories = round(0.2 * daily_calorie_needs)
    morning_snack_calories = round(0.1 * daily_calorie_needs)
    lunch_calories = round(0.3 * daily_calorie_needs)
    afternoon_snack_calories = round(0.1 * daily_calorie_needs)
    dinner_calories = round(0.3 * daily_calorie_needs)
    night_snack_calories = round(0.05 * daily_calorie_needs)
    # Create a dictionary to store the calorie breakdown
    calorie_breakdown = {
        'Breakfast': breakfast_calories,
        'Morning snack': morning_snack_calories,
        'Lunch': lunch_calories,
        'Afternoon snack': afternoon_snack_calories,
        'Dinner': dinner_calories,
        'Night snack': night_snack_calories}
    return calorie_breakdown

def generate_dict_ingredients():
    """Generates a dictionnary containing all the information about each individual ingredient in the work file"""
    meal_input_df = pd.read_excel('../files/work_files/nutrilio_work_files/nutrilio_meal_score_input.xlsx', sheet_name='Sheet1')
    dict_ingredients = {}
    for _, row in meal_input_df.iterrows():
        dict_ingredients[row['Ingredient']] = {'Score' : row['Score'],
                                               'kcal' : row['kcal'],
                                               'Category' : row['Category'],
                                               'Quantity': {'A Little' : row['A little'],
                                                            'Medium' : row['Medium'],
                                                            'A Lot' : row['A lot']}}
    return dict_ingredients

In [19]:
def get_response(client, system_prompt, user_prompt):
  # Assign the role and content for each message
  messages = [{"role": "system", "content": system_prompt},
      		  {"role": "user", "content": user_prompt}]
  response = client.chat.completions.create(
      model="gpt-3.5-turbo", messages= messages, temperature=0)
  return response.choices[0].message.content

In [20]:
def prompt_new_ingredients(ingredient):
    """Generates a ChatGPT prompt to get info's about new ingredients added in the Nutrilio app"""
    system_prompt = """You are a helpful chat assistant with knowledge in nutrition and health, 
    that answers question on certain ingredients and their overall healthiness. 
    You are able to understand french, chinese pinyin and english alike."""
    user_prompt = f"""Please output the following info, separated by commas, for
    the ingredient delimited by triple backticks:
    1. The ingredient name
    2. The overall healthiness of this ingredient, from 1 (worst) to 10 (best), in column "Score"
    3. The kcal intake for 100g of this ingredient
    4. The ingredient category of the ingredient, within this list : ['Meat','Vegetables',
    'Fruits','Carbs','Dairy','Sauces/Spices', 'Veggie alternative', 'Fish', 'Meal category', 
    'Sweets']
    Please just answer with only the information, separated with comma.
    Below are examples of how your answer should look like:
    Ingredient 1: "Cholocate bar" Output: Chocolate bar, 2, 546, Sweets
    Ingredient 2: "Fruit salad" Output: Fruit salad, 9, 63, Fruits
    Ingredient 3: "Hot pot" Output: Hot pot, 6, 37, Meal category
    Ingredient 4: "Cholocate bar" Output: Baozi, 6, 275, Carbs
    Now provide the same for the following ingredient ```{ingredient}```"""
    return get_response(client, system_prompt, user_prompt)
prompt_new_ingredients("Black peper sauce")

'Black pepper sauce, 5, 250, Sauces/Spices'

In [12]:
df.columns

Index(['Unnamed: 0', 'Full Date', 'Date', 'Weekday', 'Time', 'Daily Summary',
       'Water (ml)', 'Weight (kg)', 'Amount', 'Amount_text',
       ...
       'Family meeting_social_activity', 'Friends meeting_social_activity',
       'Party_social_activity', 'food_list', 'drinks_list',
       'body_sensations_list', 'dreams_list', 'work_content_list',
       'self_improvement_list', 'social_activity_list'],
      dtype='object', length=346)

## Kindle

In [1]:
import pandas as pd
import datetime
import os
from openai import OpenAI
from datetime import datetime
from dotenv import load_dotenv
load_dotenv()

True

In [2]:
api_key = os.environ['OpenAI_Key']
client = OpenAI(api_key = api_key)

In [3]:
def get_response(client, system_prompt, user_prompt):
  # Assign the role and content for each message
  messages = [{"role": "system", "content": system_prompt},
      		  {"role": "user", "content": user_prompt}]
  response = client.chat.completions.create(
      model="gpt-3.5-turbo", messages= messages, temperature=0)
  return response.choices[0].message.content

In [11]:
def prompt_book_title(book_title):
    """Generates a ChatGPT prompt to get correct title out of Amazon scraped """
    system_prompt = """You are a helpful librarian that is knowledgeable on all types of books.
    You can speak French, English and Dutch. You are very laconic and only answer the question asked and nothing else"""
    user_prompt = f"""I am trying to retrieve book titles by scraping Amazon on their ASIN 
    numbers, but the result sometimes contains the title along with a promotional message or the edition of the book. 
    Please me to extract the book title from the result delimited by triple backticks ```{book_title}```. 
    Please just answer with only the title and nothing else.
    Below are examples of how your answer should look like (don't include them in your answer):
    1. Input: "Atonement, the no1 best seller" Your answer : "Atonement"
    2. Input: "The girl with all the Gifts: The most Original thriller you will read this year" Your answer : "The girl with all the Gifts"
    """
    return get_response(client, system_prompt, user_prompt)
prompt_book_title("A Pale view of Hills (Vintage International)")

'A Pale view of Hills'

# New apple health

In [1]:
import pandas as pd
import os
import xmltodict
import subprocess

# Disable pandas warning about chained assignment
pd.options.mode.chained_assignment = None  # default='warn'

# Dictionary mapping column names to their respective identifiers in the export data


def clean_import_file():
    """Function to clean the import file by removing certain lines that are creating bugs"""
    path = '../files/exports/apple_exports/apple_health_export/export.xml'
    new_path = '../files/exports/apple_exports/apple_health_export/cleaned_export.xml'
    command = f"sed -e '156,211d' {path} > {new_path}"
    subprocess.run(command, shell=True)

def apple_df_formatting(path):
    """Function to format the Apple export XML file into a DataFrame"""
    with open(path, 'r') as xml_file:
        input_data = xmltodict.parse(xml_file.read())
    records_list = input_data['HealthData']['Record']
    df = pd.DataFrame(records_list)
    df.to_csv('../files/exports/apple_exports/apple_health_export/cleaned_export.csv', sep='|', index=False)
    return df

def select_columns(df, name_val):
    """Function to select columns from the DataFrame based on the column name value"""
    path = f'files/processed_files/apple_{name_val}.csv'
    df = df[df['@type'] == dict_identifier[name_val]].reset_index(drop=True)
    df["@value"] = df["@value"].astype(float)
    df.rename(columns={'@startDate': 'date', '@sourceName': 'source', '@value': name_val}, inplace=True)
    new_df = df[['date', name_val]].groupby('date').mean().reset_index()
    new_df.drop_duplicates(inplace=True)
    new_df.to_csv(path, sep='|', index=False)
    return new_df

def expand_df(df, name_val, aggreg_method='sum'):
    """Function to expand the DataFrame by adding rows for each minute within the given time range"""
    path = f'files/processed_files/apple_processed_files/apple_{name_val}.csv'
    df = df[df['@type'] == dict_identifier[name_val]].reset_index(drop=True)
    df["@value"] = df["@value"].astype(float)
    new_df = pd.DataFrame(columns=['date', 'val', 'source'])
    old_df = pd.read_csv(path, sep='|').rename(columns={name_val: 'val'})
    old_df['date'] = pd.to_datetime(old_df['date'])
    new_df = pd.concat([new_df, old_df], ignore_index=True)
    df = df[df["@startDate"] > max(old_df["date"])].reset_index(drop=True)
    print(f'{df.shape[0]} new rows to expand for {name_val}')
    for _, row in df.iterrows():
        new_df = pd.concat([new_df, row_expander_minutes(row, aggreg_method)], ignore_index=True)
    print(f'{df.shape[0]} rows expanded for {name_val} \n')
    new_df = new_df[['date', 'val']].groupby('date').mean().rename(columns={'val': name_val}).reset_index()
    new_df['date'] = pd.to_datetime(new_df['date'], utc=True)
    new_df.drop_duplicates(inplace=True)
    new_df.to_csv(path, sep='|', index=False)
    return new_df

def row_expander_minutes(row, aggreg_method):
    """Function to expand a single row into multiple rows, each representing a minute"""
    minute_diff = (row['@endDate'] - row['@startDate']).total_seconds() / 60
    if minute_diff <= 1:
        date_df = pd.DataFrame(columns=['date', 'val', 'source'])
        new_row = {'date': row['@startDate'], 'val': row["@value"], 'source': row['@sourceName']}
        date_df = date_df.append(new_row, ignore_index=True)
        return date_df
    dates = pd.date_range(row['@startDate'], row['@endDate'] - pd.Timedelta(minutes=1), freq='T')
    date_df = pd.DataFrame({'date': dates})
    if aggreg_method == 'sum':
        date_df['val'] = row["@value"] / minute_diff
    elif aggreg_method == 'avg':
        date_df['val'] = row["@value"]
    date_df['source'] = row['@sourceName']
    return date_df

def process_apple_export():
    """Function to process the Apple export and generate the final processed DataFrame"""
    path_cleaned_xml = 'files/exports/apple_exports/apple_health_export/cleaned_export.xml'
    path_csv_export = 'files/exports/apple_exports/apple_health_export/cleaned_export.csv'
    if not os.path.isfile(path_csv_export):
        if not os.path.isfile(path_cleaned_xml):
            clean_import_file()
        apple_df_formatting(path_cleaned_xml)
    df = pd.read_csv(path_csv_export, sep='|', low_memory=False)
    df['@startDate'] = pd.to_datetime(df['@startDate']).dt.floor("T")
    df['@endDate'] = pd.to_datetime(df['@endDate']).dt.floor("T")
    df_step_count = expand_df(df, 'step_count', 'sum')
    df_step_length = expand_df(df, 'step_length', 'sum')
    df_walking_dist = expand_df(df, 'walking_dist', 'sum')
    df_flights_climbed = expand_df(df, 'flights_climbed', 'sum')
    df_resting_energy = expand_df(df, 'resting_energy', 'sum')
    df_active_energy = expand_df(df, 'active_energy', 'sum')
    df_walking_speed = expand_df(df, 'walking_speed', 'avg')
    df_heart_rate = select_columns(df, 'heart_rate')
    df_audio_exposure = expand_df(df, 'audio_exposure', 'avg')
    apple_df = df_step_count.merge(df_step_length, how='outer', on='date') \
        .merge(df_walking_dist, how='outer', on='date') \
        .merge(df_flights_climbed, how='outer', on='date') \
        .merge(df_resting_energy, how='outer', on='date') \
        .merge(df_active_energy, how='outer', on='date') \
        .merge(df_walking_speed, how='outer', on='date') \
        .merge(df_heart_rate, how='outer', on='date') \
        .merge(df_audio_exposure, how='outer', on='date')
    for col in list(apple_df.columns[1:]):
        apple_df[col] = apple_df[col].astype(float)
    apple_df.sort_values('date', inplace=True)
    apple_df.to_csv('files/processed_files/apple_processed.csv', sep='|', index=False)

In [6]:
clean_import_file()

In [6]:
path_cleaned_xml = '../files/exports/apple_exports/apple_health_export/cleaned_export.xml'
path_csv_export = '../files/exports/apple_exports/apple_health_export/cleaned_export.csv'
if not os.path.isfile(path_csv_export):
    if not os.path.isfile(path_cleaned_xml):
        clean_import_file()
    apple_df_formatting(path_cleaned_xml)
df = pd.read_csv(path_csv_export, sep='|', low_memory=False)
df['@startDate'] = pd.to_datetime(df['@startDate']).dt.floor("T")
df['@endDate'] = pd.to_datetime(df['@endDate']).dt.floor("T")

In [7]:
df["@type"].unique()

array(['HKQuantityTypeIdentifierDietaryWater',
       'HKQuantityTypeIdentifierBodyMassIndex',
       'HKQuantityTypeIdentifierHeight',
       'HKQuantityTypeIdentifierBodyMass',
       'HKQuantityTypeIdentifierHeartRate',
       'HKQuantityTypeIdentifierBodyFatPercentage',
       'HKQuantityTypeIdentifierLeanBodyMass',
       'HKQuantityTypeIdentifierStepCount',
       'HKQuantityTypeIdentifierDistanceWalkingRunning',
       'HKQuantityTypeIdentifierBasalEnergyBurned',
       'HKQuantityTypeIdentifierActiveEnergyBurned',
       'HKQuantityTypeIdentifierFlightsClimbed',
       'HKQuantityTypeIdentifierDistanceCycling',
       'HKQuantityTypeIdentifierRestingHeartRate',
       'HKQuantityTypeIdentifierHeadphoneAudioExposure',
       'HKQuantityTypeIdentifierWalkingDoubleSupportPercentage',
       'HKQuantityTypeIdentifierWalkingSpeed',
       'HKQuantityTypeIdentifierWalkingStepLength',
       'HKQuantityTypeIdentifierWalkingAsymmetryPercentage',
       'HKDataTypeSleepDurationGoal',
       'HKQuantityTypeIdentifierAppleWalkingSteadiness',
       'HKCategoryTypeIdentifierSleepAnalysis',
       'HKCategoryTypeIdentifierHeadphoneAudioExposureEvent'],
      dtype=object)

In [9]:
def select_columns(df, name_val, data_type):
    """Function to select columns from the DataFrame based on the column name value"""
    path = f'../files/processed_files/apple_{name_val}.csv'
    df = df[df['@type'] == dict_identifier[name_val]].reset_index(drop=True)
    df["@value"] = df["@value"].astype(data_type)
    df.rename(columns={'@startDate': 'date', '@sourceName': 'source', '@value': name_val}, inplace=True)
    if data_type == float:
        df = df[['date', name_val]].groupby('date').mean().reset_index()
    elif name_val == "sleep_analysis":
        df = df[['date', name_val]].groupby('date').max().reset_index()
        df["sleep_analysis"] = df["sleep_analysis"].map(dict_sleep_analysis)
    df.drop_duplicates(inplace=True)
    df.to_csv(path, sep='|', index=False)
    return df

In [17]:
dict_identifier = {
    'step_count': 'HKQuantityTypeIdentifierStepCount',
    'step_length': 'HKQuantityTypeIdentifierWalkingStepLength',
    'walking_dist': 'HKQuantityTypeIdentifierDistanceWalkingRunning',
    'flights_climbed': 'HKQuantityTypeIdentifierFlightsClimbed',
    'walking_speed': 'HKQuantityTypeIdentifierWalkingSpeed',
    'heart_rate': 'HKQuantityTypeIdentifierHeartRate',
    'audio_exposure': 'HKQuantityTypeIdentifierHeadphoneAudioExposure',
    'resting_energy': 'HKQuantityTypeIdentifierBasalEnergyBurned',
    'active_energy': 'HKQuantityTypeIdentifierActiveEnergyBurned',
    'body_weight' : 'HKQuantityTypeIdentifierBodyMass',
    'sleep_analysis' : 'HKCategoryTypeIdentifierSleepAnalysis',
    'body_fat_%' : 'HKQuantityTypeIdentifierBodyFatPercentage'
}

In [11]:
df_step_count = pd.read_csv("../files/processed_files/apple_processed_files/apple_step_count.csv", sep = '|')

In [12]:
df_step_length = pd.read_csv("../files/processed_files/apple_processed_files/apple_step_length.csv", sep = '|')

In [18]:
df_body_mass_percentage = select_columns(df, 'body_fat_%', float)
df_body_mass_percentage

                        date  body_fat_%
0  2024-01-27 12:35:00+01:00       0.210
1  2024-01-27 12:36:00+01:00       0.210
2  2024-01-28 22:53:00+01:00       0.209
3  2024-01-29 07:32:00+01:00       0.211
4  2024-01-29 15:28:00+01:00       0.183
5  2024-01-29 17:07:00+01:00       0.201
6  2024-01-29 22:01:00+01:00       0.210
7  2024-01-30 07:18:00+01:00       0.208
8  2024-01-30 14:10:00+01:00       0.205
9  2024-01-31 23:14:00+01:00       0.210
10 2024-02-01 22:43:00+01:00       0.214
11 2024-02-02 07:32:00+01:00       0.211
12 2024-02-02 17:44:00+01:00       0.203
13 2024-02-02 22:24:00+01:00       0.209
14 2024-02-03 03:05:00+01:00       0.210
15 2024-02-03 09:31:00+01:00       0.211
16 2024-02-04 17:07:00+01:00       0.214
17 2024-02-04 17:36:00+01:00       0.214
18 2024-02-04 21:29:00+01:00       0.215
19 2024-02-05 07:02:00+01:00       0.211
20 2024-02-06 00:12:00+01:00       0.208
21 2024-02-06 22:26:00+01:00       0.216
22 2024-02-07 07:49:00+01:00       0.207
23 2024-02-08 07:08:00+01:00       0.208
24 2024-02-08 17:39:00+01:00       0.205
25 2024-02-08 22:03:00+01:00       0.211
26 2024-02-09 07:47:00+01:00       0.209
27 2024-02-10 10:58:00+01:00       0.209
28 2024-02-11 01:21:00+01:00       0.214
29 2024-02-11 11:02:00+01:00       0.211
30 2024-02-11 21:00:00+01:00       0.210
31 2024-02-12 07:28:00+01:00       0.207
32 2024-02-13 06:48:00+01:00       0.211
33 2024-02-13 22:38:00+01:00       0.212
34 2024-02-14 06:48:00+01:00       0.209
35 2024-02-15 06:47:00+01:00       0.210
36 2024-02-15 17:48:00+01:00       0.201
37 2024-02-16 07:48:00+01:00       0.209
38 2024-02-17 15:11:00+01:00       0.206
39 2024-02-18 22:59:00+01:00       0.211
40 2024-02-19 06:47:00+01:00       0.214
41 2024-02-19 23:03:00+01:00       0.205
42 2024-02-20 17:54:00+01:00       0.202
43 2024-02-20 23:40:00+01:00       0.209
44 2024-02-21 07:20:00+01:00       0.211
45 2024-02-21 22:44:00+01:00       0.211
46 2024-02-22 06:53:00+01:00       0.211
47 2024-02-23 18:03:00+01:00       0.202
48 2024-02-23 22:23:00+01:00       0.214
49 2024-02-24 08:33:00+01:00       0.211

In [13]:
df_step_length

                            date  step_length
0      2021-06-16 15:29:00+00:00        17.20
1      2021-06-16 15:30:00+00:00        17.20
2      2021-06-16 15:31:00+00:00        17.20
3      2021-06-16 15:32:00+00:00        17.20
4      2021-06-16 15:33:00+00:00        17.20
...                          ...          ...
58169  2024-03-11 16:39:00+00:00        21.75
58170  2024-03-11 18:32:00+00:00        59.00
58171  2024-03-11 19:33:00+00:00        74.00
58172  2024-03-11 19:34:00+00:00        74.00
58173  2024-03-11 20:40:00+00:00        59.00

[58174 rows x 2 columns]

In [14]:
apple_df = df_step_count.merge(df_step_length, how='outer', on='date')

In [15]:
df_body_weight = select_columns(df, 'body_weight', float)

In [16]:
df_body_weight

                        date  body_weight
0  2016-12-13 22:06:00+01:00        76.00
1  2019-01-21 19:59:00+01:00        78.00
2  2019-01-21 20:02:00+01:00        78.00
3  2019-04-28 20:54:00+01:00        78.00
4  2019-10-13 23:00:00+01:00        78.00
..                       ...          ...
59 2024-02-21 22:44:00+01:00        78.00
60 2024-02-22 06:53:00+01:00        77.45
61 2024-02-23 18:03:00+01:00        76.30
62 2024-02-23 22:23:00+01:00        78.05
63 2024-02-24 08:33:00+01:00        77.15

[64 rows x 2 columns]

In [27]:
df_sleep_analysis[df_sleep_analysis.sleep_analysis=="Unspecified"]

                         date sleep_analysis
0   2018-10-26 18:48:00+01:00    Unspecified
1   2018-11-05 16:30:00+01:00    Unspecified
2   2018-11-11 12:44:00+01:00    Unspecified
3   2018-12-02 19:16:00+01:00    Unspecified
4   2018-12-10 16:07:00+01:00    Unspecified
..                        ...            ...
975 2023-12-27 00:44:00+01:00    Unspecified
976 2023-12-27 01:04:00+01:00    Unspecified
977 2023-12-27 14:30:00+01:00    Unspecified
979 2023-12-27 17:03:00+01:00    Unspecified
980 2023-12-27 21:56:00+01:00    Unspecified

[687 rows x 2 columns]

In [22]:
df_sleep_analysis = select_columns(df, 'sleep_analysis', str)

In [21]:
dict_sleep_analysis = {
    "HKCategoryValueSleepAnalysisAsleepUnspecified" : "Unspecified",
    "HKCategoryValueSleepAnalysisInBed" : "In bed",
    "HKCategoryValueSleepAnalysisAsleepDeep" : "Deep sleep",
    "HKCategoryValueSleepAnalysisAsleepREM" : "REM sleep",
    "HKCategoryValueSleepAnalysisAsleepCore" : "Core sleep",
    "HKCategoryValueSleepAnalysisAwake" : "Awake"
}

In [41]:
df_sleep_analysis

                          date sleep_analysis
0    2018-10-26 18:48:00+01:00    Unspecified
1    2018-11-05 16:30:00+01:00    Unspecified
2    2018-11-11 12:44:00+01:00    Unspecified
3    2018-12-02 19:16:00+01:00    Unspecified
4    2018-12-10 16:07:00+01:00    Unspecified
...                        ...            ...
1911 2024-02-18 07:53:00+01:00      REM sleep
1912 2024-02-18 08:22:00+01:00     Core sleep
1913 2024-02-18 08:23:00+01:00      REM sleep
1914 2024-02-18 08:24:00+01:00     Core sleep
1915 2024-02-18 08:33:00+01:00      REM sleep

[1916 rows x 2 columns]

In [40]:
df[df["@type"] == "HKCategoryTypeIdentifierSleepAnalysis"]

,@type,@sourceName,@sourceVersion,@unit,@creationDate,@startDate,@endDate,@value,MetadataEntry,@device
1149735,HKCategoryTypeIdentifierSleepAnalysis,Polar Flow,373,NaN,2018-10-26 07:56:57 +0100,2018-10-26 18:48:00+01:00,2018-10-26 20:53:00+01:00,HKCategoryValueSleepAnalysisAsleepUnspecified,NaN,NaN
1149736,HKCategoryTypeIdentifierSleepAnalysis,Polar Flow,373,NaN,2018-11-05 11:25:47 +0100,2018-11-05 16:30:00+01:00,2018-11-05 19:10:00+01:00,HKCategoryValueSleepAnalysisAsleepUnspecified,NaN,NaN
1149737,HKCategoryTypeIdentifierSleepAnalysis,Polar Flow,374,NaN,2018-11-14 19:48:10 +0100,2018-11-11 12:44:00+01:00,2018-11-11 17:26:00+01:00,HKCategoryValueSleepAnalysisAsleepUnspecified,NaN,NaN
1149738,HKCategoryTypeIdentifierSleepAnalysis,Polar Flow,380,NaN,2018-12-02 12:24:56 +0100,2018-12-02 19:16:00+01:00,2018-12-02 22:42:00+01:00,HKCategoryValueSleepAnalysisAsleepUnspecified,NaN,NaN
1149739,HKCategoryTypeIdentifierSleepAnalysis,Polar Flow,380,NaN,2018-12-10 17:55:20 +0100,2018-12-10 16:07:00+01:00,2018-12-10 20:10:00+01:00,HKCategoryValueSleepAnalysisAsleepUnspecified,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
1151837,HKCategoryTypeIdentifierSleepAnalysis,Connect,2,NaN,2024-02-18 14:55:47 +0100,2024-02-18 08:22:00+01:00,2024-02-18 08:23:00+01:00,HKCategoryValueSleepAnalysisAsleepCore,NaN,NaN
1151838,HKCategoryTypeIdentifierSleepAnalysis,Connect,2,NaN,2024-02-18 14:55:47 +0100,2024-02-18 08:23:00+01:00,2024-02-18 08:24:00+01:00,HKCategoryValueSleepAnalysisAsleepREM,NaN,NaN
1151839,HKCategoryTypeIdentifierSleepAnalysis,Connect,2,NaN,2024-02-18 14:55:47 +0100,2024-02-18 08:24:00+01:00,2024-02-18 08:33:00+01:00,HKCategoryValueSleepAnalysisAsleepCore,NaN,NaN
1151840,HKCategoryTypeIdentifierSleepAnalysis,Connect,2,NaN,2024-02-18 14:55:47 +0100,2024-02-18 08:33:00+01:00,2024-02-18 09:43:00+01:00,HKCategoryValueSleepAnalysisAsleepREM,NaN,NaN
1151841,HKCategoryTypeIdentifierSleepAnalysis,Connect,2,NaN,2024-02-18 14:55:47 +0100,2024-02-18 00:28:00+01:00,2024-02-18 09:43:00+01:00,HKCategoryValueSleepAnalysisInBed,NaN,NaN

In [12]:
df[df["@type"] == "HKQuantityTypeIdentifierBodyMass"]

,@type,@sourceName,@sourceVersion,@unit,@creationDate,@startDate,@endDate,@value,MetadataEntry,@device
91,HKQuantityTypeIdentifierBodyMass,Health,10.1.1,kg,2016-12-13 22:06:06 +0100,2016-12-13 22:06:00+01:00,2016-12-13 22:06:00+01:00,76,NaN,NaN
92,HKQuantityTypeIdentifierBodyMass,Polar Flow,390,kg,2019-01-21 20:00:55 +0100,2019-01-21 19:59:00+01:00,2019-01-21 19:59:00+01:00,78,NaN,NaN
93,HKQuantityTypeIdentifierBodyMass,Polar Flow,390,kg,2019-01-21 20:02:39 +0100,2019-01-21 20:02:00+01:00,2019-01-21 20:02:00+01:00,78,NaN,NaN
94,HKQuantityTypeIdentifierBodyMass,Polar Flow,408,kg,2019-04-29 17:11:11 +0100,2019-04-28 20:54:00+01:00,2019-04-28 20:54:00+01:00,78,NaN,NaN
95,HKQuantityTypeIdentifierBodyMass,Polar Flow,466,kg,2019-10-20 22:53:20 +0100,2019-10-13 23:00:00+01:00,2019-10-13 23:00:00+01:00,78,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
244,HKQuantityTypeIdentifierBodyMass,EufyLife,20,kg,2024-02-09 08:19:27 +0100,2024-02-08 07:08:00+01:00,2024-02-08 07:08:00+01:00,76.5,NaN,NaN
245,HKQuantityTypeIdentifierBodyMass,EufyLife,20,kg,2024-02-09 08:19:27 +0100,2024-02-09 07:47:00+01:00,2024-02-09 07:47:00+01:00,76.5,NaN,NaN
246,HKQuantityTypeIdentifierBodyMass,EufyLife,20,kg,2024-02-09 08:19:27 +0100,2024-02-07 07:49:00+01:00,2024-02-07 07:49:00+01:00,76.45,NaN,NaN
247,HKQuantityTypeIdentifierBodyMass,EufyLife,20,kg,2024-02-09 08:19:27 +0100,2024-02-06 22:26:00+01:00,2024-02-06 22:26:00+01:00,78.3,NaN,NaN
248,HKQuantityTypeIdentifierBodyMass,EufyLife,20,kg,2024-02-09 08:19:27 +0100,2024-02-08 17:39:00+01:00,2024-02-08 17:39:00+01:00,76.6,NaN,NaN

In [ ]:
&